### ISSUE TITLE
Investigate capability to read radar fields.

### ISSUE THREAD

**Issue by fionaRust** [metoppv/improver#108]
As a developers of IMPROVER we want access to Radar data so that we can begin to develop nowcasting

Related issues: #84

It was decided that this was better as the approach isn't agreed yet.

Acceptance criteria:
 * Spend no longer than 3 days investigating the functionality required in #84 : Capability to read radar fields for nowcasting
 * Write up findings on this ticket to cover work completed and flag up any problems

**Comment by MoseleyS** [comment]
https://exxreldocs:8099/display/TEPPV/MetDB+Radar+data
The above page shows the result of extrating and plotting gridded radar data from the MetDB (the code is linked from there too).
The upshot is that the 5km resolution radar data available from the MetDB are not sufficient for running a UK nowcast on a 2km standard grid.

**Comment by gavinevans** [comment]
Ok. After looking at your script for pulling back data from MetDB, I can understand that the data isn't on a sufficient resolution. Thanks for posting the code on the wiki page, although just to point out I assume that the script that you ran is a little different from the script on the wiki page, as I wouldn't have thought the `datashape` variable had been defined. Please update the issue when any progress is made. Thanks!

**Comment by MoseleyS** [comment]
Code corrected - you were right. `datashape` was being defined, but I had posted the code lines in the wrong order.

**Comment by MoseleyS** [comment]
Choices. We can ask for the data we need to be made available through MetDB or we can wait to see how the Service Hub will deliver these data. The latter is the preferred T&E method. If we need to demonstrate any Nowcast capability this year using a non-Service-Hub approach, we might as well use the simpler work-around of ingesting the current operational data used by the UK Nowcast.

Therefore, no further work is required on this ticket. It has absorbed about 1.5 days of effort. A slide has been added to the sprint demo presentation.

**Comment by gavinevans** [comment]
This looks fine. I'm happy for this issue to be closed.

**Comment by fionaRust** [comment]
Closing as no more work to be done right now.
