### ISSUE TITLE
Command line interface for weighted blending function

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#110]
As the product owner I want a Command Line Interface for the functionality to generate weights for blending forecasts #106 

Related issues: #106 

Acceptance criteria:
 * A CLI for the blending weights function #106   
* A CLI acceptance test
* Accepted method for I/O of blending weights data

**Comment by fionaRust** [comment]
@benfitzpatrick  We need some input from you to help make a decision about this.

**Comment by benfitzpatrick** [comment]
What's the problem?

**Comment by meabhnicguidhir** [comment]
The issue above has been resolved for now:
* For now, argparse's subparser option won't be used as it makes the help output messy.
* Sub-options (cval, yoval etc) which are not compatible with the main option (linear, nonlinear) they are entered with will result in an error being raised.

@benfitzpatrick to raise a follow on technical issue to investigate the optimal way of handling multiple options and sub-options in CLIs.

**Comment by benfitzpatrick** [comment]
Follow-on issue is #139.

**Comment by meabhnicguidhir** [comment]
**Branch for this Work**
https://github.com/meabhnicguidhir/improver/tree/weighted_blending_cli

**CLI Content**
* user specifies input file, output file and coordinate over which the cube should be blended (ex: 'time' if time-lagging is to be carried out'). The user may also specify a function to apply to this coordinate after the blending has occurred (ex: for time-lagging, may wish to change time coordinate to midpoint of time-range over which lagging was carried out). This function is input as a string.
* user specifies one of ```--linear``` or ```--nonlinear``` options for weights calculation. The user may optionally specifiy values for the factors used by each of these methods (```--cval``` for non-linear blending and  ```--y0val``` and at most one of  ```--ynval, --slope``` for linear weights blending).
* one of ChooseDefaultWeightsLinear or ChooseDefaultWeightsNonLinear is called based on the inputs above.
the weights from this calculation are passed into BasicWeightedAverage and the cube is collapsed over the coordinate specified and if a coordinate adjusting function is specified, this is applied.

**BATS Tests**
* Input data was generated from archive enukx thickness_of_rainfall_amount data. Data from 3 cycle times was converted to probabilities at thresholds of 4-12mm.
* Test 00 and 01: test the null args and help outputs.
* Tests 02 and 03: acceptance tests for the linear and nonlinear options without any sub-option arguments.
* Test 04: checks that the correct error is raised when ```improver weighted-blending``` is called with both ```--linear``` and ```--nonlinear``` options.
* Tests 05 and 06: acceptance tests for the linear and nonlinear weights calculations when all of their sub-options are specified.
* Test 07: acceptance test for case where the coordinate adjustment function is used
* Test 08: checks the correct error is raised when the ```--linear``` options is used with both ```--ynval``` and ```--slope``` sub-options specified.

*Other Tests which may be required*
* possibly a test for ```--linear``` with sub-options for ```--nonlinear``` (```--cval```) and/or vice versa.

**Comment by carolinejjones** [comment]
This issue ticket replaces #16 therefore closing #16

**Comment by fionaRust** [comment]
Pr #140 merged and slide created so closing this story
