### ISSUE TITLE
Full suite scoping and discussion

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#111]
As the IMPROVER technical architect I want some preliminary approaches to the full IMPROVER suite solution to be scoped out and discussed so that the initial approach can be decided.

See the technical demo report on Confluence.

Acceptance criteria:
 * Investigate Cylc suite solutions to writing the full IMPROVER suite(s) at a high structural level
 * Spend no more than 13 person-days on this
 * Discuss approach regularly with interested developers (at the moment Ben, Tomek, Aaron)
 * ~Agree approach and present it to rest of team with documentation in Confluence~ (moved to later multi-model suite ticket #153)

**Comment by bayliffe** [comment]
- [x] I need to add a slide.
