### ISSUE TITLE
improver percentile: use custom numpy.percentile for speed

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#113]
As an IMPROVER developer I want to use a percentile aggregator based on numpy.percentile so that my acceptance tests run faster and my future suite utilities run in a timely fashion.

numpy.percentile is something like 50x faster than the scipy routine Iris uses, although it is less flexible.

Related issues: #69 

Acceptance criteria:
 * Write a new percentile aggregator that uses numpy.percentile, replacing the use of the `iris.analysis.PercentileAggregator` in the percentile plugin.
 * Add some unit tests for the aggregator
 * Check old and new unit tests pass
 * Check CLI acceptance tests either pass or are within sensible tolerances and need updating
 * Manually test several different diagnostics and numbers of realizations, to check the resulting output is similar, whilst documenting any significant differences.
 * Ensure treatment of 0% and 100% bins are the same or document differences.

**Comment by bayliffe** [comment]
Please note: I have created a PR in the iris project to provide a keyword argument switch between the scipy and numpy methods. This will allow us to continue with the current percentile routine, simply adding a percentile_method kwarg to the cube.collapsed call.

https://github.com/SciTools/iris/pull/2682

```
result = cube.collapsed(self.collapse_coord,
                        iris.analysis.PERCENTILE,
                        percent=self.percentiles,
                        percentile_method='fast')
```

**Comment by fionaRust** [comment]
The above PR has been merged into Iris 2 and we will be able to use it once we have access to a new version of Iris for testing. Then our plugins can be updated to use the new functionality.
