### ISSUE TITLE
How to cite Improver properly?

### ISSUE THREAD

**Issue by jodemaey** [metoppv/improver#1153]
Hi,

If one want to cite Improver in a scientific publication (other than simply providing the github link), how to do it properly?

Sorry if it is not the right place to ask that (or if it has already been asked).

Thank you in advance,

Jonathan Demaeyer

**Comment by benfitzpatrick** [comment]
Hi Jonathan,

We're setting up a DOI - we should be able to embed that in the README on the next release. In terms of actual papers to cite, we're yet to finish the big scientific or technical ones, sadly!

Cheers,

Ben

**Comment by jodemaey** [comment]
Thanks Ben. May I ask when will that next release be approximately ?

**Comment by LaurenceBeard** [comment]
Hi Jonathan,
 We aim to do another release next week, to sync the code with another (suite) repository.

Cheers, Laurence

**Comment by jodemaey** [comment]
Great! Thank you.

**Comment by benfitzpatrick** [comment]
Sorry for the delay @jodemaey - https://github.com/metoppv/improver/pull/1220 has created a DOI badge in the README based on our latest release, linking through to https://zenodo.org/record/3744431#.Xo2z-ohKhhE.

**Comment by jodemaey** [comment]
Thank you.
