### ISSUE TITLE
Wind downscaling: remove unused functionality

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#121]
As an IMPROVER developer I want to remove unused wind downscaling flexibility so that my code is cleaner

Related issues: #67 

One example: Current implementation of wind downscaling has an optional input of wind speed heights in a cube. If we are using data on the standard grids, then the data will always be on the standard heights. The code should use the height coordinate of the wind speed cube instead of a separate cube of heights.

Acceptance criteria:
 * Remove RMDI handling in wind downscaling - should just handle NaN
 * Do not allow separate heights cube (see above)
 * Remove other unused code as you see fit, provided it is not used in the acceptance tests
 * Update existing unit tests - they should still pass if they are testing the normal usage, if not remove them
 * Acceptance tests should still pass

**Comment by arh89** [comment]
Reopening as height levels cube is still being passed into the CLI - this complicates the clize interface as the `height_levels` cube is the only input which is not positional. Removing this will simplify the CLI and better fit with the new convention.
