### ISSUE TITLE
WindDirection - make multiple outputs optional

### ISSUE THREAD

**Issue by LaurenceBeard** [metoppv/improver#1213]
Currently the WindDirection unconditionally returns 3 cubes, where only one of which contains the wind direction (the other two are used for diagnostic purposes). Refactor the wind direction code to remove these extraneous cubes from the return.

**Comment by LaurenceBeard** [comment]
While this has been fixed at the cli level, the plugin remains an anomaly. It would be best to remove these extra returns, or make them an option

**Comment by fionaRust** [comment]
@bayliffe will do a PR. @LaurenceBeard can review

**Comment by gavinevans** [comment]
The generation of the additional outputs from the wind direction plugin has now been removed in https://github.com/metoppv/improver/pull/1759 (related to https://github.com/metoppv/mo-blue-team/issues/299), so this issue can now be closed.
