### ISSUE TITLE
Ensure all plugins inherit from BasePlugin

### ISSUE THREAD

**Issue by LaurenceBeard** [metoppv/improver#1217]
Follows on from metoppv/improver#910
We need to ensure that all plugins inherit from BasePlugin.

`[~/improver/lib/improver]$ grep --exclude-dir=tests -rP ^class.*:$ * | grep -v BasePlugin | grep -v PostProcessingPlugin` to see all not conforming, of these:

Not plugins:
improver/blending/weighted_blend.py:class PercentileBlendingAggregator:
improver/blending/weights.py:class WeightsUtilities:
improver/cli/__init__.py:class HelpForNapoleonDocstring(HelpForAutodetectedDocstring):
improver/cli/__init__.py:class DocutilizeClizeHelp(ClizeHelp):
improver/cli/__init__.py:class ObjectAsStr(str):
improver/ensemble_copula_coupling/ensemble_copula_coupling.py:class ConvertLocationAndScaleParameters():
improver/lapse_rate.py:class SaveNeighbourhood:
improver/utilities/warnings_handler.py:class ManageWarnings:
improver/wind_calculations/wind_downscaling.py:class RoughnessCorrectionUtilities:

Could possibly be converted to a plugin:
improver/nbhood/circular_kernel.py:class CircularNeighbourhood:
improver/nbhood/circular_kernel.py:class GeneratePercentilesFromACircularNeighbourhood:
improver/nbhood/square_kernel.py:class SquareNeighbourhood:

So possibly not much left to do here, worth a double check
Acceptance criteria:
See GitHub ticket.

**Comment by LaurenceBeard** [comment]
It seems the CircularNeighbourhood/SquareNeighbourhood are outliers in that they are called from BaseNeighbourhoodProcessing using the run method.
https://github.com/metoppv/improver/blob/61af5af88fadb9508f23ac274aead5731106ff45/improver/nbhood/nbhood.py#L151
I'm not sure if this abstraction is useful, or if this bit of code needs a broader rethink

**Comment by neilCrosswaite** [comment]
CircularNeighbourhood/SquareNeighbourhood aren't plugins they are objects called by a plugin.

**Comment by fionaRust** [comment]
@LaurenceBeard  and @neilCrosswaite a long time ago I looked at ways to simplify the neighbourhood processing code. It was never prioritised but here is the ticket in case it is useful. IMPRO-460

**Comment by LaurenceBeard** [comment]
OK, I will close this one if we have another ticket covering this particular issue.
