### ISSUE TITLE
Can I get some test data?

### ISSUE THREAD

**Issue by NMC-DAVE** [metoppv/improver#1236]
Hi:
    I am weather forecaster, and I wang to test the IMPROVER software. Where can I find some data to test the IMPROVER CLI. Thanks very much!
    Dave

**Comment by fionaRust** [comment]
Hi Dave,

We use standardised Met Office data for IMPROVER, which is available for all our main models with a delay on Amazon web services (https://registry.opendata.aws/uk-met-office/). There are some examples on how to use the data here: https://github.com/MetOffice/aws-earth-examples. The example notebook also gives you a good idea of what our standard model data looks like: https://github.com/MetOffice/aws-earth-examples/blob/master/examples/1.%20Getting%20Started.ipynb. 

Hope that gives you something to get started with. Let us know how you get on with your testing of IMPROVER.

Fiona

**Comment by NMC-DAVE** [comment]
Hi Fiona:
    Very thanks for your reply.
Dave

**Comment by fionaRust** [comment]
Hi Dave,

I'm going to close this issue now. Feel free to contact us again if you need any more help.

Fiona
