### ISSUE TITLE
Burn down Charts

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#126]
As project manager I want the ability to track the burn down for the sprint so that I can predict the likelihood of achieving the sprint goal.

Optional extra information text goes here
Use an integration for GitHub like ZenHub or Jira to provide this functionality

Acceptance criteria:
 * Burn down is displayed in chart form - outstanding work on the vertical axis with time along the horizontal 
 * Burn down is automatically generated instead of manually. *

**Comment by bayliffe** [comment]
There is a need for us to record some internal information (e.g. file paths/system info) and for a much better way of recording the development of suites than is currently possible using GitHub. I would like to advocate for the use of Jira for our epic/story/issue development, with the pull-requests on GitHub serving as a means of externally displaying the development that is underway. I'm not sure if this is an unpopular suggestion, but I would like to discuss it if possible.

**Comment by benfitzpatrick** [comment]
Happy to move this discussion offline, where I think it belongs.

This ticket does not talk about migrating to JIRA - it uses it as an example.

This would remove the possibility of collaboration. It would effectively close-source IMPROVER, so I am very much against it. Well written code does not need hardcoded user or system or filepath information.

ZenHub looks much better than JIRA in my opinion.

The question of suites is somewhat separate. Closed source GitHub or JIRA or SRS are OK ways of developing suites if we really want. That remains an open question.

**Comment by fionaRust** [comment]
@seanpcoultas  Can we close this now?

**Comment by fionaRust** [comment]
Completed by the use of Jira for burndown charts.
