### ISSUE TITLE
Implement compression control

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#1268]
We need to add an option across all CLIs/CLI functions to enable or disable compression.

At the moment compression is hardcoded to on in the save utilities module - but it has performance implications and isnt always desirable.

We have a couple of generic options such as `--profile` already.

Acceptance criteria:
See GitHub ticket.

**Comment by LaurenceBeard** [comment]
The current point at which Chunking is determined: https://github.com/metoppv/improver/blob/master/improver/utilities/save.py#L103
