### ISSUE TITLE
Ancillaries: investigate internal hosting

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#127]
As an IMPROVER developer I want to find out if I can store or get new ancillaries in a standard in-house way.

(Do not post internal specifics on the issue)

Acceptance criteria:

 * Investigate in house ancillary hosting
 * Report to rest of dev team
 * Dont write internal stuff on this issue

**Comment by fionaRust** [comment]
Some progress has been made towards this, see Jira ticket IMPRO-208

**Comment by bayliffe** [comment]
The creation of ancillaries was covered to some extent in IMPRO-192. Note that we still need to work on a centralised hosting solution rather than the currently hard coded /store directory.
