### ISSUE TITLE
Generate acceptance test metadata

### ISSUE THREAD

**Issue by tjtg** [metoppv/improver#1273]
As a first step towards #1218, add a plugin/CLI which creates cubes/netCDF files similar to the netCDF file inputs to IMPROVER.
This issue tackles metadata only - the output cube can be filled with zeros or masked/missing data indicators.

There is some existing functionality to generate data cubes for testing in [improver_tests/set_up_test_cubes.py](https://github.com/metoppv/improver/blob/master/improver_tests/set_up_test_cubes.py) which may be able to be generalised and a plugin/CLI interface added to call it. If this code is used as a base, it should be migrated from `improver_tests` into `improver` to avoid `improver` depending on `improver_tests`.

The data types/parameters available should cover all NWP model and radar data used as inputs to IMPROVER. As this issue is metadata-only, the change required is likely to be string-based naming only, rather than needing to generate different data depending on the parameter name.

A default grid domain for code-generated acceptance tests will need to be chosen. The metadata generation code should have the ability to be re-configured for other grids and numbers of ensemble members easily.

A proposal for the default grid setup (open to comments/suggestions):
- Regularly spaced latitude/longitude - easier data handling and visualisation
- Approximately 2km x 2km resolution - similar to high-resolution local NWP models
- Latitudes/longitudes away from poles and not located in the UK or Australia - poles can be difficult to handle, generic location avoids country specific testing
- Grid size between Wales (~20,000 km^2) and Tasmania (~60,000 km^2) - large enough to avoid boundary effects, but keep data size small so that test cases run quickly
- (optional) 8 ensemble members - sufficient to form a sensible probability distribution to be able to test percentile/threshold data representations
- (optional) 10 pressure/altitude levels - sufficient for level based plugins eg. snow falling level to be tested

**Comment by TomekTrzeciak** [comment]
In offline discussion about possible interface two options were considered:
  
  1. A routine along the lines of `set_up_variable_cube` that could be made into CLI via clize. The interface would look something like this:
```
improver gen-meta-cube \
    --name=<output-var-name>
    [--spatial-grid=<name>] \
    [--time=<date-time-string>] \
    [--realizations=<csvlist>] \
    [--attributes=<jsonfile>] \
    [more options ...]
    [--output=<filename>]
```

Pros:
 - simple and relatively quick to implement
 - might be all we need, at least to begin with

Cons:
 - limited (can't construct arbitrary cubes)
 - not possible to round trip between metadata dump and creation of template cube

  2. A more generic routine that would be driven by metadata dump in some format (e.g. JSON) as a template plus options to override entries in the input template. The interface could look something like this:
```
improver gen-meta-cube \
    [<inputjson> [<inputjson> [...]]]
    --name=<output-var-name>
    [--coord=<varname>=[<scalar>|<csvlist>|<range>]] \
    [--attr=<varname>:<attrname>=<value>] \
    [more options ...]
    [--output=<filename>]
```
Multiple input JSON files could be overlayed on top of each other (could be used to store grid definitions).

Pros:
 - generic - could in principle handle arbitrary output
 - could easily round trip between metadata dump and creation of the template cube (e.g. could be used to create template cubes from KGO metadata)

Cons:
 - harder to implement (no python tools to work with standard text NetCDF representation like CDL)
 - no access to lower-level iris read interfaces to allow reading from custom objects, would likely require writing NetCDF file out and reading it back in with iris (inefficient)
 - more logic required to ensure valid output is created (e.g., only one coord system is specified)

In terms of python friendly formats I've found [cf-json](http://cf-json.org/) and 3rd-party python package implementing it: https://github.com/metocean/cf-json (supports xarray, but not iris).

Upon reflection, I think the choice between solution 1 & 2 is not so crucial at this point. If we go with 1, it wouldn't be much code to replace it with 2 in the future if we want to.

In regards to writing our own dumper and reader routine - IMO it wouldn't take much code to implement something like cf-json or similar.
