### ISSUE TITLE
Threshold: agree and apply correct naming convention

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#130]
As an IMPROVER data user I want the threshold plugin to correctly produce probability metadata when it is applied.

Related issues: #91, #54, #98  

For example, `thickness_of_rainfall_amount` might become e.g. `probability_of_rainfall_amount_above_threshold` with a threshold value (naming to be decided). It will not be so neat for cubes with realization dimensions. When they are fed in (normally what we would expect), unless we collapse over realization (which is really a blend step) then we'll still have realization mixed with 'probability'.

Acceptance criteria:
 * Apply temporary metadata conventions to the plugin and add unit tests to capture this
 * Move threshold plugin out of utilities.

**Comment by benfitzpatrick** [comment]
I would go for a variable (cube) name of `probability_of_X_above_threshold` and `probability_of_X_below_threshold`, where threshold is given as a dimensional coordinate - either `realization, threshold, x, y` or `threshold, x, y`.

Example CF names from http://cfconventions.org/Data/cf-standard-names/44/build/cf-standard-name-table.html:
```
number_of_days_with_air_temperature_above_threshold		
number_of_days_with_air_temperature_below_threshold		
number_of_days_with_lwe_thickness_of_precipitation_amount_above_threshold		
number_of_days_with_surface_temperature_below_threshold	
number_of_days_with_wind_speed_above_threshold
```

Examples from NetCDF-U (https://portal.opengeospatial.org/files/46702):
```
prob_greater_than_limit
```

**Comment by fionaRust** [comment]
**NOTE:** This is very strongly linked to issue #91 about agreeing netCDF conventions for lots of different situations and should not be done until metadata conventions have been agreed.

**Comment by wxtim** [comment]
Pull request #269 created. There are some outstanding issues with testing that the metadata works properly when concatenating cubes.

**Comment by fionaRust** [comment]
All complete, slide added. Well done :)
