### ISSUE TITLE
Implement the optical flow algorithm for radar precipitation

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#132]
Stephen Moseley as Nowcasting Lead Scientist wants to have the capability to extrapolate radar precipitation rate fields forward in time to use for nowcasting. 

Related issues: Part I #167. Part II #168. Part III #169.

- [x] Part I #167 contains:
 * Method to derive advection velocities using Martina's STEPS Python optical flow method (see Stephen's homespace `from_Martina/Decomposition_2017.py`: Class `OFC` (550 lines))
 * Method to derive advection velocities using OpenCV optical flow code. `flow = cv2.calcOpticalFlowFarneback(frame1, frame2, 0.5, 3, 15, 3, 5, 1.2, 0)`
 * Demonstrate difference in advection velocities between these two methods.

- [ ] Part II #168 contains:
 * Method to derive the mean advection velocities between two consecutive pairs of data (time 1 -> time 2 and time 2 -> time 3).
 * Method to calculate orographic precipitation enhancement (porting `steps_core_orogenh.cpp` method `ComputeEnhancements`).
 * Method to create an extrapolation forecast using advection velocities.

- [ ] Part III #169 contains:
 * Method to insert or remove the impact of orographic precipitation enhancement from STEPS `ComputeEnhancements` C++ method.
 * Modify method to create an extrapolation forecast using advection velocities to use orographic enhancement data.

Acceptance criteria:
 * Have plugin(s) which can use these algorithms.
 * Unit testing
 * Demonstration showing how the two orographic enhancement methods compare.

**Comment by fionaRust** [comment]
No longer using these epics and all outstanding work is covered by other tickets so closing.
