### ISSUE TITLE
not able to start to work with IMPROVER 

### ISSUE THREAD

**Issue by BehSabzi** [metoppv/improver#1321]
Hi, 
I'm new here. I wonder if you help me out. I searched quite a lot bu I didn't find the answer, though I thought it wasn't serious. Anyway, while I try to run any of the codes, I face this error:

ModuleNotFoundError: No module named 'improver'.

Thanks in advance

**Comment by BehSabzi** [comment]
I clone in the same adress that I had the environment (...\anaconda3\envs\improver). I don't have the abovementioned error, but I had another one : 
ImportError: cannot import name 'PostProcessingPlugin'

**Comment by tjtg** [comment]
These errors are likely to be due to some kind of path problem. We don't currently package IMPROVER for installation via pip or conda, so it will need to be run from the directory where you cloned the repository, or by providing the full path to the `bin/improver` top level shell script.

I've added an example of how to install dependencies and run some basic IMPROVER commands in the [Running at your site](https://github.com/metoppv/improver/wiki/Running-at-your-site#basic-step-by-step-usage-example) page on the wiki.

**Comment by BehSabzi** [comment]
Thanks for your response. I learned something new.

While I followed the steps from [Running at your site](https://github.com/metoppv/improver/wiki/Running-at-your-site#basic-step-by-step-usage-example), I face some issues (I have Windows on my machine):
I wrote the following lines in Anaconda prompt
`git clone https://github.com/metoppv/improver.git improver`
`cd improver`
`conda env create -f environment.yml`
`conda activate improver`

then, here I didn't know what do 
`bin/improver threshold --help`
`bin/improver threshold --threshold-values=273.15,280,290 /path/to/your/data/air_temperature.nc`
mean, (I wonder if you tell me that), so I skipped them. Then, I ran `conda install -c conda-forge iris-sample-data`. Then, since I use Spyder I install Spyder in this new environment as well.
Then after I opened Spyder and ran the provided example:
`import iris`
`cube = iris.load(iris.sample_data_path("E1_north_america.nc"))[0]`
`print(cube)`
It was ok, but while I ran this command 
`output = improver.cli.threshold.process(cube, threshold_values=[273.15, 280.0, 290.0])`
I got this error :

   File "<ipython-input-6-4e3b98be2d20>", line 1, in <module>
          output = improver.cli.threshold.process(cube, threshold_values=[273.15, 280.0, 290.0])

    AttributeError: module 'improver' has no attribute 'cli'

I wonder if you help me in this case too.

**Comment by tjtg** [comment]
Sorry, I did the importing wrong in the instructions I'd put on the wiki previously. I've made an [update to the import](https://github.com/metoppv/improver/wiki/Running-at-your-site/_compare/246294b259eccea54b66553d58599201d3a412f3...1a74649ae9bf48f06df1c08365232e45dcaa4a74) used in the [Python example](https://github.com/metoppv/improver/wiki/Running-at-your-site#basic-step-by-step-usage-example) which should fix that.
The top level `improver/__init__.py` currently doesn't import all the sub-packages and make them available after doing `import improver` which caused my previous method to not work.

`bin/improver` refers to the top-level wrapper shell script [in the repository](https://github.com/metoppv/improver/blob/master/bin/improver). That script is the usual way to run IMPROVER as a command, such as part of a larger scale workflow via Cylc. The wrapper script provides a point for any required setup to be done before running Python, such as [Environment Modules](https://modules.readthedocs.io/en/latest/) which is commonly used on HPC systems.

`/path/to/your/data/air_temperature.nc` refers to a NetCDF file containing air temperature data to process. You can provide your own NetCDF file or see [input data](https://github.com/metoppv/improver/wiki/Running-at-your-site#input-data) on the wiki for  info about how to get suitable files from Met Office weather models. Files from [iris-sample-data](https://github.com/SciTools/iris-sample-data/tree/master/iris_sample_data/sample_data) will also be suitable for use with some IMPROVER plugins.

**Comment by BehSabzi** [comment]
Thanks for your comment and follow-up.

Like the previous trial, I took steps considering new importing `import improver.cli as imprcli`. However, I got the error again:

> ModuleNotFoundError: No module named 'improver.cli'


Thanks.

**Comment by BehSabzi** [comment]
I tried again, it worked. In fact, it works as far as I keep the path the same as where I've already cloned the package :)
