### ISSUE TITLE
Cache reset

### ISSUE THREAD

**Issue by BelligerG** [metoppv/improver#1339]
The current method for resetting the cache in github is to alter an environment variable: https://github.com/metoppv/improver/pull/1334

This means that if a reset is required, a pull request must be merged for potentially no code changes. It would be much nicer if we could reset the cache without having to alter the yml file at all. Something along the lines of using a secret (as suggested by @tjtg), however, there is an issue with using secrets in workflows on PRs from forks (see https://github.com/metoppv/improver/pull/1334#issuecomment-697186980).

**Comment by cpelley** [comment]
Looks like this issue should be closed
