### ISSUE TITLE
Adaptive neighbourhood functionality

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#134]
As the product owner I would like to be able to define appropriate neighbourhood sizes at every grid square on-the-fly so that they are more appropriate for the weather of the day

Related issues: Builds on #104. Follow-on work in #170.

There is documentation on the approach and algorithm.

This involves two user stories.
* Create plugin for the algorithm. #199
* Implement infrastructure to run the algorithm. #200
* Modify square neighbourhood algorithm to use new array of radii. #207

**Comment by fionaRust** [comment]
Closed on Jira due to tickets being restructured and epic no longer being required.

**Comment by bayliffe** [comment]
Use of Epics resumed. This Epic needed as a parent for adaptive neighbourhooding.
