### ISSUE TITLE
Use of percentiles

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#138]
As the product owner I want IMPROVER to be able to deal with percentiles as well as probabilities for neighbourhood processing and blending.

Related issues: #69 - import percentile conversion (I think is the most relevant)

This user story assumes it is possible to generate percentiles from ensemble members at each grid square.

Three options:
1. Compute percentiles across ensemble members and neighbourhoods simultaneously
2. Compute percentiles across members and then apply neighbourhood processing in an appropriate way
3. Compute percentiles across neighbourhoods and then across ensemble members in an appropriate way

- [ ] Write a strategy for the use of percentiles with neighbourhood processing and blending
- [ ] #166 Build the capability to blend percentiles from two distributions using Caroline's method 
- [ ] Build the capability to extract percentiles from a square neighbourhood

Acceptance criteria:
 * Have a written strategy for percentiles going forward that includes percentile calculations with neighbourhoods and blending percentiles from two distributions (<= 5 days)
 * Have the capability to find percentiles from neighbourhoods
* Have the capability to blend percentiles using Caroline's method (From StaGE Plugin.) (5 days)
 * Unit tests
 * Plugins for the code blocks

**Comment by bayliffe** [comment]
Replaced with #166 and #175
