### ISSUE TITLE
Run tests on Github Actions using multiple conda environments

### ISSUE THREAD

**Issue by tjtg** [metoppv/improver#1381]
It would be useful to run the test suite on Github Actions with a variety of conda environments to avoid becoming unintentionally coupled to specific library versions by only testing with a single version.

Suggested environments:
- Python 3.6, Iris 2.2 (similar to current environment.yml in top level directory)
- Python 3.8, Iris 2.4 (a newer, but not latest version)
- Latest available version of all dependencies

A few libraries will need to have exactly pinned versions, even in the environment that uses all latest versions. For example, newer black 20.8b0 changes some code formatting.

**Comment by lucyleeow** [comment]
Potentially we could add an environment with minimal dependencies (e.g., without any optional dependencies like pysteps, once we've removed it - #1384).

**Comment by dmentipl** [comment]
Implemented in #1392.
