### ISSUE TITLE
Make pysteps dependency optional

### ISSUE THREAD

**Issue by tjtg** [metoppv/improver#1384]
IMPROVER currently depends on [pysteps](https://pysteps.github.io/) - it is listed in the conda [environment file](https://github.com/metoppv/improver/blob/master/environment.yml) and some unit tests will fail if it is not available.

It would be useful to make pysteps an optional dependency, so that tests which use pysteps functionality are skipped if it is not available.
Pysteps is only used by a subset of CLIs and these will fail with an ImportError if it is not available. I think the current behaviour here is OK, as the ImportError exception trace is clear enough at explaining what needs to be done to resolve the error.

**Comment by MoseleyS** [comment]
Hi @tjtg (cc @cgsandford )
Please can you explain why is this wanted? Is Pysteps causing issues for you at BoM? As far as we are concerned, Pysteps (or at lest, bits of it) is now a compulsory module to allow us to run our nowcast methods.

**Comment by tjtg** [comment]
As you've mentioned, pysteps is required by nowcasting code in IMPROVER. However, we're not currently using the nowcasting components of IMPROVER at BoM. 
Pysteps is a moderately sized library, but it pulls in some larger dependencies such as OpenCV (eg. libopencv is [about 30MB compressed](https://anaconda.org/conda-forge/libopencv/files) or 110MB uncompressed). Making dependencies optional helps reduce the size of python environments (eg. pip or conda), associated network downloads and time taken for conda to do its dependency solving.

The intention here is that installation of pysteps shouldn't be required unless the nowcasting part of IMPROVER is being used. This would make pysteps similar to timezonefinder in IMPROVER such as https://github.com/metoppv/improver/blob/8da46d9acddcf1abf4ff32052797f367931847ce/improver_tests/generate_ancillaries/test_GenerateTimezoneMask.py#L45 and https://github.com/metoppv/improver/blob/8da46d9acddcf1abf4ff32052797f367931847ce/improver/generate_ancillaries/generate_timezone_mask.py#L94

With issue #1381, we should still make sure that at least one of the environment specifications continues to include pysteps so that all the code is still covered by the test suite on Github actions.

**Comment by lucyleeow** [comment]
Closed by #1389
