### ISSUE TITLE
CLI: better option engine or usage

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#139]
As an IMPROVER CLI developer I want to know how to parse and generate help for options in the best way possible so that my CLI is easy to understand and develop.

Acceptance criteria:
 * Investigate alternative option parsers, with focus on handling different sets of exclusive options
 * Also investigate how to do this with argparse 
 * Spend no more than 5 days on this
 * Report back

Additional investigations added by Fiona after developer catch up:
* Investigate using a directory tree structure of CLIs to handle cases where we have exclusive options.
* Investigate using dictionaries of options specific to exclusive options that we could pass into the plugins. Be aware of security concerns.

**Comment by gavinevans** [comment]
@LaurenceBeard has pointed out that we're currently using a mixture of the default argparse functionality, as well as wrapping the argparse functionality [argparser.py](https://github.com/metoppv/improver/blob/master/lib/improver/argparser.py). If, after investigating this issue, we're sticking with `argparse` then we should decide whether we're going to use [argparser.py](https://github.com/metoppv/improver/blob/master/lib/improver/argparser.py) within all CLIs. @benfitzpatrick

**Comment by LaurenceBeard** [comment]
clize work has superseded this
