### ISSUE TITLE
Missing dependencies in setup.cfg

### ISSUE THREAD

**Issue by dmentipl** [metoppv/improver#1435]
It seems that there are several packages missing from `setup.cfg` which are non-optional, i.e. they are explicitly imported in IMPROVER modules without, for example, using importlib. Here is the list as far as I can tell:

- cartopy
- cf_units
- dask
- netCDF4
- pytz

These are also missing from the Conda environment files (except pytz), and from the [conda-forge feedstock](https://github.com/conda-forge/improver-feedstock).

**Comment by lucyleeow** [comment]
Just to add to this, although these are dependencies of packages that are listed, it may not be best to rely on them being pulled in by another package and to explicitly include them as dependencies.

cc @tjtg

**Comment by dmentipl** [comment]
Closed in #1436
