### ISSUE TITLE
Probability of occurrence within a distance of a grid square

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#145]
As the product owner I want IMPROVER to have the capability to compute the probability of something occurring within a specified distance of each grid square.

This is important functionality for determining if showers, or high precipitation totals or lightning strikes are around even if the probability at a particular location/grid square is small. It will be used to help produce weather symbols and for first guess warnings of severe weather. It is also going to be important for first guess warning information for high-impact weather such as flood-producing rainfall totals or severe wind gusts.
Documentation can be found in 
[rain_in_vicinity_050717.pdf](https://github.com/metoppv/improver/files/1125038/rain_in_vicinity_050717.pdf)

Related issues: #73, #74 

- [ ] Calculate the highest fraction in a square locality around each grid square
- [ ] Input the output from above into neighbourhood processing (#73 & #74) to give the probability of an occurrence within the vicinity of each grid square

Acceptance criteria:
 * Capability to find the maximum value in a square vicinity
 * Capability to feed maxima field into neighbourhood processing
 * Sufficiently fast
 * Unit tests
 * Plugins

**Comment by gavinevans** [comment]
I currently have two alternate methods for performing the `Occurrence within vicinity` calculation.
Two loops:
```python
        max_cube = cube.copy()
        max_cube.data = np.zeros(cube.data.shape)
        ylen = len(max_cube.coord(axis="y").points)
        xlen = len(max_cube.coord(axis="x").points)
        for y_index in range(len(cube.coord(axis="y").points)):
            for x_index in range(len(cube.coord(axis="x").points)):
                if y_index-grid_cell_y < 0:
                    lower_y_index = 0
                else:
                    lower_y_index = y_index-grid_cell_y
                if x_index-grid_cell_x < 0:
                    lower_x_index = 0
                else:
                    lower_x_index = x_index-grid_cell_x
                if y_index+grid_cell_y > ylen:
                    upper_y_index = ylen
                else:
                    upper_y_index = y_index+grid_cell_y+1
                if x_index+grid_cell_x > xlen:
                    upper_x_index = xlen
                else:
                    upper_x_index = x_index+grid_cell_x+1
                max_cube.data[y_index, x_index] = np.max(
                    cube.data[..., lower_y_index:upper_y_index,
                              lower_x_index:upper_x_index])
```

One loop:
```python
        max_cube = cube.copy()
        ylen = len(max_cube.coord(axis="y").points)
        xlen = len(max_cube.coord(axis="x").points)
        column_indices, row_indices = np.where(max_cube.data>0)
        for y_index, x_index in zip(column_indices, row_indices):
            if y_index-grid_cell_y < 0:
                lower_y_index = 0
            else:
                lower_y_index = y_index-grid_cell_y
            if x_index-grid_cell_x < 0:
                lower_x_index = 0
            else:
                lower_x_index = x_index-grid_cell_x
            if y_index+grid_cell_y > ylen:
                upper_y_index = ylen
            else:
                upper_y_index = y_index+grid_cell_y+1
            if x_index+grid_cell_x > xlen:
                upper_x_index = xlen
            else:
                upper_x_index = x_index+grid_cell_x+1
            # For binary values, this works:
            max_cube.data[lower_y_index:upper_y_index,
                          lower_x_index:upper_x_index] = np.max(
                cube.data[..., lower_y_index:upper_y_index,
                          lower_x_index:upper_x_index])
            # For non-binary values, this is needed:
            max_value = (
               np.max(
                   cube.data[..., lower_y_index:upper_y_index,
                             lower_x_index:upper_x_index]))
            mask = max_cube.data[lower_y_index:upper_y_index,
                                 lower_x_index:upper_x_index] < max_value
            max_cube.data[lower_y_index:upper_y_index,
                          lower_x_index:upper_x_index][mask] = np.max(
                cube.data[..., lower_y_index:upper_y_index,
                          lower_x_index:upper_x_index])
```

For a cube with 1000x1000 for projection_y_coordinate x projection_x_coordinate, where the data is zeroes apart from:
data[0, 1] = 1.0
data[2, 3] = 1.0

Timing comparison
Two loop:
```bash
real	0m15.846s
user	0m14.840s
sys	0m0.228s
```
One loop:
```bash
real	0m4.154s
user	0m3.155s
sys	0m0.210s
```

For a cube with 1000x1000 for projection_y_coordinate x projection_x_coordinate, where the data is all ones.
Timing comparison
Two loop:
```bash
real	0m15.656s
user	0m14.749s
sys	0m0.224s
```

One loop handling binary events only:
```bash
real	0m21.268s
user	0m20.228s
sys	0m0.258s
```

One loop handling non-binary events:
```bash
real	0m41.422s
user	0m40.457s
sys	0m0.286s
```

**Comment by gavinevans** [comment]
Preferable solution:

```python
        max_cube = cube.copy()
        max_cube.data = (
            scipy.ndimage.filters.maximum_filter(cube.data, size=grid_cells))
```
For a cube with 1000x1000 for projection_y_coordinate x projection_x_coordinate, where the data is zeroes apart from:
data[0, 1] = 1.0
data[2, 3] = 1.0
A distance of 1 grid cell is used.
```bash
real	0m4.194s
user	0m3.180s
sys	0m0.234s
```

For a cube with 1000x1000 for projection_y_coordinate x projection_x_coordinate, where the data is all ones. A distance of 1 grid cell is used.
```bash
real	0m4.072s
user	0m3.186s
sys	0m0.201s
```

**Comment by gavinevans** [comment]
Follow-on tickets required:
- Support finding the maximum value within a circular vicinity. This would involve using the `footprint` argument for the `scipy.ndimage.filters.maximum_filter` and specifying a circular area, most likely in a very similar way to as done in the `apply_circular_kernel` method. It might be best to factor out the relevant section from `apply_circular_kernel`, so that this can be used in multiple places.

**Comment by gavinevans** [comment]
Follow-on work:
- Move `vicinity.py` to a more suitable long-term home. This might become more obvious as functionality, such as #202 is developed.

**Comment by bayliffe** [comment]
Thanks Gavin.
