### ISSUE TITLE
Move wiki to docs

### ISSUE THREAD

**Issue by dmentipl** [metoppv/improver#1451]
I propose moving the wiki to a "developer guide" section in the docs, which would then be available on at [improver.readthedocs.io](https://improver.readthedocs.io).

The content of the wiki is useful for developers. Moving it under source control means that changes to it require review, thus checking that the content is relevant and correct.

I have a branch on my fork demonstrating this:

https://github.com/dmentipl/improver/tree/wiki_in_docs

To test this, you can clone my fork, check out the "wiki_in_docs" branch, build the docs with

```bash
make -C doc html
```

and open `doc/build/html/index.html` in a browser and explore from there.

**Comment by gavinevans** [comment]
Thanks @dmentipl. Just to mention, that we had a chat about this in the IMPROVER blue team and we're happy with this proposal.  We'd be happy to review a PR associated with this.

**Comment by dmentipl** [comment]
Thanks @gavinevans. I have created a PR for this: #1456.

**Comment by dmentipl** [comment]
Resolved in #1456.
