### ISSUE TITLE
Follow on Documentation for Land Sea Aware Regridding

### ISSUE THREAD

**Issue by owena11** [metoppv/improver#1457]
As discussed on #1438, a ticket to cover additional documentation to go in a follow on PR. Discussed that following a similar style to the existing documentation for [improver.calibration.ensemble_calibration](https://improver.readthedocs.io/en/latest/improver.calibration.ensemble_calibration.html#ensemble-model-output-statistics-emos) and [improver.utilities.indexing_operation](https://improver.readthedocs.io/en/latest/improver.utilities.indexing_operations.html) would be a sensible way forward. 

Particularly  covering:
- Triangle Interpolation derivation - enough that someone can work out what is intended without having to work out  what's being calculated in the code, (Or pointing to further references) 
- Cases covered by the algorithm, when it branches into the Bi-linear / Triangle interpolation / IDW - To give someone an way of approaching the code without much prior knowledge of the intended techniques.

We should make sure that docstrings and comments in the code align with any new documentation or diagrams added.

Also update docstrings to use type annotation format and check docstrings are clear.

**Comment by fionaRust** [comment]
We should ensure that behaviour is documented. I would like to review the documentation

**Comment by fionaRust** [comment]
Thanks Julian. I'm happy the work on this ticket has been done now, so I'm closing this ticket.
