### ISSUE TITLE
Integration of verification suite and simple evaluation suite.

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#148]
A component of Epic #141

As a verification scientist I want a single suite that can retrieve level 1 data and process it with Improver plugins, calling verification for each stage in the chain to monitor performance.

Related issues: #149 

The developer will need to collaborate with Ric Crocker from the verification team. We want to test the resulting Improver evaluation suite using 1 month of historical data.

Acceptance criteria:
 *  Add verification tasks at the end of the processing chain of the simple evaluation suite to loop over each processing stage including Level 1 data:
     1. An ECC call will be required to convert Improver percentile output into ensemble member data immediately before verification.
     2. Probability output is out of scope for this ticket but will be introduced when probability metadata is clarified.
 * Modify the suite to run on HPC(s) if not already.
 * Modify the suite to include housekeeping (except for Verification tracking databases)
 * 1 Month trial run to be performed using wind processing chain (February).
 * Work with Roger Harbord to plot output and check it looks sensible/complete.
 * Note any bottlenecks in running the one month trial.
 * Signed off by verification team.

NB Verification will perform a more detailed scientific analysis of output outside of this ticket.

**Comment by jflowerdew** [comment]
Just to be clear, verification involves:
- One nctoff and ModelToFDB task per stage of IMPROVER output (for all variables simultaneously), on each cycle where IMPROVER produces output
- A set of observation retrieval tasks each hour, followed by a set of verification tasks for each stream of IMPROVER output
- Housekeeping tasks about once per day

For details, see Ric's suite mi-as726

**Comment by gavinevans** [comment]
This issue is complete.
