### ISSUE TITLE
Check units in transform_grid_to_lat_lon

### ISSUE THREAD

**Issue by lucyleeow** [metoppv/improver#1514]
`transform_grid_to_lat_lon` currently does not check the units of `x` and `y` before using them:

https://github.com/metoppv/improver/blob/e7240bd57c4770033328dcdbf0eb13118edfff30/improver/utilities/spatial.py#L514-L515

This is not a problem for files coming out of stage but could be if this utility function is used for other files, e.g., we ran into a problem with radar grid using kms. We could add a conversion to metres in this function.

cc @tjtg

**Comment by tjtg** [comment]
There's an assumption in this code that the cube X and Y coordinate units match with the (cartopy/pyproj) coordinate system units. For lots of projections that'll be in metres, but some others (eg. PlateCarree) will be in degrees.

It may be possible to retrieve the coordinate system units and then use Iris `convert_units` to make the units match what's expected. However, I had a quick look at doing this and it's not as simple as I had hoped - there seems to be lots of "we use the defaults" all the way down the stack from iris -> cartopy -> pyproj -> proj.
The underlying [proj library docs](https://proj.org/usage/projections.html#units) say:
> The default unit for projected coordinates is the meter. A few special projections deviate from this behavior, most notably the latlong pseudo-projection that returns degrees. 

I couldn't easily work out which projections are the "special" ones that have non-metres units from the proj library documentation or the code. For example, there's no mention of units in either [aea](https://github.com/OSGeo/PROJ/blob/master/src/projections/aea.cpp) or [latlong](https://github.com/OSGeo/PROJ/blob/master/src/projections/latlong.cpp) code.

This should probably be posted as an issue on metoppv/improver, but I expect it'll end up settling on "your data should be standardised to use SI base units, this is not an improver problem".

**Comment by bayliffe** [comment]
With newer packages (specifically cartopy) we can do something like the following:
```
# Ensure the coordinate points are in the same units as the default for
# the associated coordinate system to ensure correct transformation.
crs_default_unit, = set([axis.unit_name for axis in source_crs.axis_info])
cube = cube.copy()
for axis in ["x", "y"]:
    cube.coord(axis=axis).convert_units(crs_default_unit)
```
This ensures that the units of the cube coordinate are consistent with the default for its coordinate system; these should be compatible as we cannot have an e.g. PlateCarree projection with coordinate units of metres. The transformation will then always give the same output regardless of the coordinate units on the input cube.

However, in the package versions we are constrained to use by HPC limitations I cannot ascertain the default units of the proj4 projection from the cube's coordinate system. I'll keep playing with this to see if I can come up with a nice solution.

**Comment by bayliffe** [comment]
@tjtg this is the best I can do until we can access the default units of a given projection which will require a newer version of proj.

PR: https://github.com/metoppv/improver/pull/1715
