### ISSUE TITLE
Site-specific lapse rate adjustment of PDF

### ISSUE THREAD

**Issue by Kat-90** [metoppv/improver#1516]
## User story  

As an IMPROVER customer I want the best site-specific temperature forecast I can receive, with consistently processed percentiles available to me.

## Description  

At present, IMPROVER is only capable of applying temperature lapse rate corrections to “deterministic” forecasts, where this has meant the 50th percentile only to this point. This limitation means that the adjustment is disabled in the current Beta release. By the time of operational release we need to be able to adjust the entire PDF using a lapse rate to produce multi-percentile, lapse rate adjusted screen temperature forecasts. A simplistic approach is envisaged for this year which involves shifting the entire distribution in line with change to the median that the lapse rate correction makes. Better approaches likely exist, but this will ensure the percentiles remain monotonically ordered and is simple to implement. Work required under this component is: 

- Removal of current enforcement that limits the application to single percentiles. 

- Extension of functionality to enable application to each percentile efficiently.

## Acceptance criteria:  

Lapse rate adjustment of site-specific temperature forecasts can be applied to multiple percentiles.
Lapse rate adjustment of site-specific temperature forecasts is re-enabled in the live suites or the necessity is recorded in release notes.

**Comment by Kat-90** [comment]
http://fcm1/rose-bush/cycles/khurst/?suite=lapse_rate_4

Linked suite PR: https://github.com/MetOffice/improver_suite/pull/977

**Comment by Kat-90** [comment]
Acceptance test data found in branch IMPRO-2162 in improver_tests/spot-extract/

**Comment by Kat-90** [comment]
Update since 12/8:

Changes have been tested in both trial and realtime modes. 

A bug in the plugin causing the user specified title to be overwritten has been fixed by changing the class from PostProcessingPlugin to BasePlugin.

An acceptance test has now also been added to show the lapse rate adjustment of an input with multiple percentiles.

**Comment by MoseleyS** [comment]
Acceptance test data also merged.
