### ISSUE TITLE
Remove upward flux from UV index plugin

### ISSUE THREAD

**Issue by Kat-90** [metoppv/improver#1529]
## User story
As a developer, I want to calculate daytime maximum UV index data for the global grid so that MVP is reached.

## Description  
Currently, the code adds together the downward and upward UV flux before calculating the UV index. The code should just use the downward UV flux. This confusion appears to have arisen from the current SSPS code where the sum of UV net flux (which is a mislabelled downward flux) and UV upward flux are used (UV upward flux is a negative value there). Both SSPS and IMPROVER are currently wrong (confirmed by Simon Jackson).

## Acceptance criteria:

* Fix calculation of UV radiation flux bug in the plugin.

**Comment by Kat-90** [comment]
PR is linked to this ticket.

Acceptance test data can be found in: /data/users/khurst/improver_test/uv-index/

**Comment by MoseleyS** [comment]
Hi @Kat-90 
Please can you commit your acceptance test data changes to a new branch? It'll make it easier for me to test.
Thanks

**Comment by Kat-90** [comment]
Acceptance test data changes have now been committed to branch IMPRO-1529
