### ISSUE TITLE
Full suites development: semi-functional multi-model draft

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#153]
As an IMPROVER suite developer I want to draft a suite so that design decisions can be validated and lessons learnt.

Work on multi-model suite, including lessons learnt from #68 and #111:
 * Add skeleton tasks for the UK deterministic and ensemble for a range of Level 1 diagnostics (temperature, wind speed, surface pressure) from the archive
 * Skeleton tasks should have input and output directories set just like #68
 * Skeleton tasks for the ensemble could run `improver percentile` or `improver threshold`
 * Include model-and-cycle-time-decoupled blending tasks -in a separate include file- (may want to run them completely separately in real time)
 * Blending tasks can time lag blend ensemble data if you have time
 * Spend no more than 13 days on this.
 * Verification is out of scope

**Comment by gavinevans** [comment]
This issue has been superseded by an internal issue.
