### ISSUE TITLE
ResolveWindComponents auxiliary coordinate errors with Iris >2.2

### ISSUE THREAD

**Issue by tjtg** [metoppv/improver#1534]
Current StaGE NWP data includes a status flag variable/auxiliary coordinate on pressure level parameters such as `wind_speed_on_pressure_levels` and `wind_direction_on_pressure_levels`. This status flag indicates whether or not the pressure level is above the topography level (earth surface).

When using IMPROVER with newer Iris versions, this status flag auxiliary coordinate causes [compare_coords](https://github.com/metoppv/improver/blob/44fb70ec1798dc347d6b2b272edf0e9a09a09629/improver/wind_calculations/wind_components.py#L209) to find mismatched coordinates as the auxiliary coordinate `standard_name` is different for wind speed status flag and wind direction status flag.
This looks to be the relevant change in Iris: SciTools/iris#3393 - included in Iris 2.3.0

This issue was originally uncovered as part of Iris 3 support work: https://github.com/metoppv/improver/pull/1507#issuecomment-880613853

**Comment by tjtg** [comment]
There are three possible fixes that I can think of:
- Add an "ignore aux coords" option to the compare_coords function. I think the intention here is to check dimension and maybe scalar coordinates.
- Drop the explicit check using compare_coords in ResolveWindComponents. If the cubes don't sufficiently match, it'll produce an error later anyway. "easier to ask forgiveness rather than permission"
- Add code in ResolveWindComponents to drop any status flag auxiliary coordinate from the input. It looks like the status flag isn't being used here. I'm not sure if any downstream plugins do use it, but that appears unlikely as Iris 2.2 is making a mess of status flag metadata when saving out, so the status flag may not be in a usable state for anything downstream as it currently is.

This will need someone with knowledge and context to decide what the appropriate way to fix this issue is.
Whichever fix is chosen, the acceptance test data should also be updated so that the data set is representative of current NWP data sets that is being used as input to IMPROVER.

**Comment by MoseleyS** [comment]
Another option is to add a specific check for these status flag aux coords in the `compare_coords` method.

I'm not keen on the "ignore aux coords" option as we would expect aux coords to match for these cubes and if they don't, something is wrong.

Not checking the coords at all means relying on the lengths of each coord, while bearing in mind that length-1 coords may be automatically broadcast. Also, a failure from mismatched lengths will likely result in an Exception that isn't immediately obvious to overcome. I'm not keen on this approach either.

I quite like the "discard these specific coords" option. I had thought that we should do this in the `load_cube` method, but perhaps it is better to do it where we need it.

**Comment by cgsandford** [comment]
Having discussed this with Stephen, it seems like what's happening here is that Iris3 is mis-interpreting a NetCDF flag and translating it into something inappropriate.  Which would imply that this is a bug in Iris3 and should be raised as an issue on that repo.

If that is the case (and I appreciate I may have misinterpreted), then I accept we can't just wait for that issue to be fixed on the iris end, and I'd suggest we do something in the improver load wrapper to convert the coordinate to the correct interpretation (an attribute on a pressure coordinate?) on load.

If this is not an iris "bug" but a "feature", then I suggest a good way to handle it would be the option to exclude specific coordinates by name, passed to the "compare_coords" method.  This would allow us to exclude only this particular bit of metadata from the comparison, but to include other auxiliary coordinates that need to match (for example, scalar time).

**Comment by MoseleyS** [comment]
Following this morning's discussion, I now know from @benfitzpatrick  and @bjwheltor that 

- StaGE is adding these coords to indicate grid points whose data have been generated by interpolation in the UM, because that point is below the model orography for that pressure level.
- Therefore, the meta-data associated with the coords is correct and there is no bug in Iris.

With this additional information, we agreed to modify the `compare_coords` function to ignore these specific coords. It occurs to me now that we could actually check the coords, because we expect them to match in all details except for the coord name. This would be even better, if it is not too difficult to achieve.

**Comment by bayliffe** [comment]
PR: https://github.com/metoppv/improver/pull/1535

This has been tested in the following way:
- change applied to Daniel's Iris 3 branch.
- the im1517 acceptance test data that goes with the iris 3 branch was used.
- the improver py37 environment was used.

Under these conditions the tests all passed. The `resolve-wind-components` CLI was tested in isolation under the same conditions using inputs provided by @neilCrosswaite, with it failing in the expected manner prior to the change, and succeeding after the change.
