### ISSUE TITLE
Increase robustness of ConvertLocationAndScaleParametersToPercentiles plugin

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#1536]
As an IMPROVER developer I would like to increase the robustness of the ConvertLocationAndScaleParametersToPercentiles plugin by tidying up a couple of issues so that the code is easier to maintain and performs consistently for a user.

Issues:

1. @ThomasGregory reported that it is currently possible for the [template_slice](https://github.com/metoppv/improver/blob/master/improver/ensemble_copula_coupling/ensemble_copula_coupling.py#L894) variable to be undefined, if the realization or percentile coordinate on the template cube is not a dimension coordinate i.e. if there is only one realization or percentile. Given that only a slice of the template cube is used as the template, it should be possible to support providing a cube with a scalar realization or percentile coordinate. 
2. To avoid rounding issues, it shouldn't be necessary to [divide the percentiles by 100](https://github.com/metoppv/improver/blob/master/improver/ensemble_copula_coupling/ensemble_copula_coupling.py#L849) and then later [multiply the percentiles by 100](https://github.com/metoppv/improver/blob/master/improver/ensemble_copula_coupling/ensemble_copula_coupling.py#L881). Instead, [percentiles as fractions](https://github.com/metoppv/improver/blob/master/improver/ensemble_copula_coupling/ensemble_copula_coupling.py#L559) should be computed in a separate variable to avoid the re-conversion introducing rounding issues.

Acceptance criteria:
 * Support for using a cube with a scalar realization or percentile as a template cube, with a suitable unit test
 * Avoidance of unnecessary conversion of floating point values.

**Comment by fionaRust** [comment]
PR merged
