### ISSUE TITLE
datetime_to_iris_time bug

### ISSUE THREAD

**Issue by neilCrosswaite** [metoppv/improver#1540]
As a developer I want the temporal datetime_to_iris_time to work with cftime.datetime so that the nowcasting works with iris3

Related issues: #1437 

As part of the upgrade to Iris 3, a few bug have been found.
cftime.datetime is now unable to return the float of time since epoch.

An environment can be sourced from the #1507 PR.

A quick fix was put in to look for other errors it turned the `cftime.datetime` into a `datetime.datetime` but I don't know how robust this implementation is in the grander scheme of things.
```diff
diff --git a/improver/utilities/temporal.py b/improver/utilities/temporal.py
index 203e588e..7d0dcc3e 100644
--- a/improver/utilities/temporal.py
+++ b/improver/utilities/temporal.py
@@ -155,7 +155,8 @@ def datetime_to_iris_time(dt_in: datetime) -> float:
     Returns:
         Time since epoch in the seconds as desired dtype.
     """
-    result = dt_in.replace(tzinfo=timezone.utc).timestamp()
+    dt = datetime.strptime(f'{dt_in}', '%Y-%m-%d %H:%M:%S')
+    result = dt.replace(tzinfo=timezone.utc).timestamp()
     return np.int64(result)
```

Acceptance criteria:
 * The function stays the same but is given a datetime as is given in the type hinting.
 * OR
 *  The function can deal with a cftime.datetime

**Comment by MoseleyS** [comment]
You can convert the object to a datetime object like this:
```
    if isinstance(d, cftime.DatetimeGregorian):
        d = dt.datetime(d.year, d.month, d.day, d.hour, d.minute, d.second)
```

**Comment by gavinevans** [comment]
Pull request to @dmentipl's Iris 3 branch: https://github.com/dmentipl/improver/pull/1

**Comment by bayliffe** [comment]
PR merged.
