### ISSUE TITLE
Remove references to scipy's truncnorm

### ISSUE THREAD

**Issue by BelligerG** [metoppv/improver#1567]
The current implementation of scipy's truncnorm distribution has some performance issues which makes https://github.com/metoppv/improver/blob/47f9e103c63f890bfbb24d5e08d9d01d041514f7/improver/ensemble_copula_coupling/ensemble_copula_coupling.py#L1111 incredibly slow. Currently we've got round this by pinning an older version of scipy.

We can, however, recreate a truncnorm distribution using `scipy.stats.norm`, which doesn't appear to have the same issues by using something like:

![image](https://user-images.githubusercontent.com/44228125/134851684-ebc7132d-1904-42b8-a653-8f505c43f499.png)
![image](https://user-images.githubusercontent.com/44228125/134851699-fd25fafe-e3e5-4385-8270-4685c1a0b727.png)

At the same time, it may be possible to do some optimising, considering the cache sizes.

**Comment by cpelley** [comment]
Thanks @BelligerG, looks like you have done much of the leg work :)

Hacked something together something quick that seems to work (not with the interface we want):

```python
import numpy as np
from scipy.stats import norm, truncnorm


class TruncNorm():
    def __init__(self, a, b, loc, scale):
        self._a = a
        self._b = b
        self._loc = loc
        self._scale = scale
        self._norm = norm(loc, scale)
        self._clip_a = self._clipval(a)
        self._clip_b = self._clipval(b)
        # https://www.real-statistics.com/normal-distribution/truncated-normal-distribution/
        self._denominator = (self._norm.cdf(self._clip_b) -
                             self._norm.cdf(self._clip_a))

    def _clipval(self, val):
        # "a" and "b" are defined over the domain of the standard normal.
        # To convert clip values for a specific mean and standard deviation
        # See https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.truncnorm.html
        return (val * self._scale) + self._loc

    def __call__(self, x):
        x = np.asarray(x)
        res = self._norm.pdf(x) / self._denominator
        res[x < self._clip_a] = 0
        res[x > self._clip_b] = 0
        return res


if __name__ == "__main__":
    loc = 0
    scale = 3
    a = -1
    b = 3
    x = list(range(-10, 11))
    tnorm = truncnorm(a, b, loc, scale)
    tar = tnorm.pdf(x)
    res = TruncNorm(a, b, loc, scale)(x)

    print(max(abs(res - tar)))
```

stdout:
```
2.7755575615628914e-17
```

It would be good to understand how you came to the conclusion that "truncnorm" was to blame, then ideally we could look at how we might potentially create a new performance test as part of our acceptance testing? - this way we wouldn't have to wait so long to run the suite to find out (we could iterate faster)

I see we call the original "truncnorm", "cdf" (cumulative distribution function) and "sf" (survival function) methods.  We would have to be able to do the same here.

**Comment by cpelley** [comment]
I'll take a little look at whether we can simply take a copy of the `truncnorm` from the older version of scipy to use with the more recent scipy just in case before going further.

**Comment by cpelley** [comment]
So it works.  I have a branch taking just what we need from 1.3.3 for the truncnorm (commit [here](https://github.com/cpelley/improver/commit/a2269417b300177f253f946bda71741e5bde8546)).
Tested it and it performs much better.

I'll make it so this version takes priority over the one in scipy then run the tests and put up for review & discussion.

**Comment by BelligerG** [comment]
This looks like a really good solution, I was worried about copyright, but if it's already done in iris with the copyright tags, that sounds good!

I found it was the truncnorm by profiling it:

![image](https://user-images.githubusercontent.com/44228125/136032836-bf5c9e70-83fc-4e63-b6d1-bdd57708b829.png)

**Comment by cpelley** [comment]
Thanks @BelligerG.
Haven't had to do profiling in a couple of years in Python but I used to use sampling based profiler [kapture](https://github.com/SciTools-incubator/kapture) that might be of interest??

**Comment by cpelley** [comment]
I extended the above implementation to include "cdf" and "sf" methods (of course it would need some extensive testing).
I stopped short of including the "ppf" method, which is the inverse of the "cdf" (wasn't immediately obvious to me how to do it).
I have put on hold for now for https://github.com/metoppv/improver/pull/1576 since that provides a more immediate solution.

**Comment by BelligerG** [comment]
> Thanks @BelligerG. Haven't had to do profiling in a couple of years in Python but I used to use sampling based profiler [kapture](https://github.com/SciTools-incubator/kapture) that might be of interest??

Potentially :-) it's not something I've come across before, I'll take a look, cheers!
