### ISSUE TITLE
mask slowdown issue

### ISSUE THREAD

**Issue by cpelley** [metoppv/improver#1579]
Currently the nightly suite run demonstrates issues with some commands involving mask handling.

ppdev suite [output](http://fcm1/rose-bush/view/ppdev?&suite=imengluk_midnight&no_fuzzy_time=0&path=log/job/20211006T1800Z/impr_engluk_pressrhlight_PT0120H/01/job-timings.tsv#146):

```
MEM		INPUT		OUTPUT		CPU		TIME		USER		SYS		COMMAND
534816		84391		13683		99%		0:04.61		4.07		0.52		improver regrid --regrid-mode nearest --regridded-title...
632688		1717887		11174		99%		3:24.80		196.23		8.30		improver regrid --regrid-mode nearest-with-mask --land-sea-mask-vicinity 25000 --regridded-title...
```

Note the difference in run-time between the two.

**Comment by cpelley** [comment]
So looking further, I see we do a cubelist merge, but the issue with chunksizes originates at the very step of loading the cubes. 
 Seems this is due to a difference in behaviour of iris in choosing 'suitable chunksizes':
https://scitools-iris.readthedocs.io/en/latest/whatsnew/2.3.html (iris code [changes](https://github.com/SciTools/iris/pull/3361/files)).

**Comment by cpelley** [comment]
From our chat Monday, it seemed that it might be acceptable for now, to read the data into memory on load.
I'm not familiar with `clize` or to a great extent of Python typing, but it looks as though options for `load_cube`  in particular `no_lazy_load` are not exposed to the CLI.

https://github.com/metoppv/improver/blob/43054bd803f6789c1cee3e36d3b31c495489e3e2/improver/utilities/load.py#L114-L118

The load is achieved through typing via the clize value_converter decorator.

https://github.com/metoppv/improver/blob/43054bd803f6789c1cee3e36d3b31c495489e3e2/improver/cli/weighted_blending.py#L40-L41

I think ideally this should be exposed to any of the commands (`weighted-blending`, `regrid` or otherwise) performing a load.
Then perhaps we can apply this argument within the improver-suite for the cases effected.

We could expose this to the top-level `improver` CLI but perhaps that would be nasty to then have it as a global var.

Any suggestions?

Cheers

**Comment by cpelley** [comment]
Thanks @PaulAbernethy, should I assign the "Project" -> repositories -> "Green team"?

**Comment by cpelley** [comment]
> If you didn't want to expose the option...

Well actually, I think having it as an **option** would be ideal :) but I couldn't immediately see a way to do this neatly across all application CLIs while retaining the approach we have using positional arguments (`cli.inputcubes`).
I think it would be great to have lazy or not lazy on a both per command and per input file basis.
Having it configurable would mean being able to specify the behaviour within the suite, which would be neat.

```
improver <commandA> <input-file1> <input-file2> --no-lazy ...
```

> ...you could always set cli.inputcubes for those CLIs as a new type of object defined in improver/improver/cli/__init__.py and pass the no_lazy_load option?

If you mean defining a new type (for example `improver.cli.inputcube_nolazy`), then having the CLI for the `weighted-blending` and `regrid` use this new nolazy type then that sounds reasonable except this would effect calls where we don't need to apply this behavioural workaround (unmasked data for example).  Also, there are at at least two interfaces right now effected by this performance degradation.  That is the `regrid` and `weighted-blending`.  I'm not familiar enough with the code/suite just yet to determine whether this issue is restricted to just those two, or whether there are more to come.  That is, configuring this within the suite allows it to be controlled.

Hmmm.  Tell you what, I'll put together my "nasty" solution as a PR, then we can discuss the pros/cons and perhaps better alternatives via clize or otherwise.

Thanks @BelligerG

**Comment by BelligerG** [comment]
> Hmmm. Tell you what, I'll put together my "nasty" solution as a PR, then we can discuss the pros/cons and perhaps better alternatives via clize or otherwise:

Sounds good, it was just a quick alternative :-)

**Comment by cpelley** [comment]
The issue with regrid is two-fold:

The first and most significant is that we are currently calling `AdjustLandSeaPoints.correct_where_input_true`, once for land and once for ocean, for EACH x-y slice of the input cube ("multi-realization data").  This then unnecessarily re-evaluates an unstructured nearest neighbour problem via calls to [scipy.interpolate.griddata](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html) for each of these slices.  Nearest neighbour calculations need only be calculated once for land and once for ocean...

https://github.com/metoppv/improver/blob/1088b59c1fe32a8bfab267b6be956b737633a966/improver/regrid/landsea.py#L260

The second 'issue' is then where dask rears its head, which is that we create these x-y slices as well as create various copies.  Due to the change in chunking rules for NetCDF in recent iris, we are then hit (as with the weighted blending) with an unnecessary read from disk bottleneck.

Based on some quick changes locally: caching the nearest neighbour regridder by utilising ckdtree and also realising the data on load, I can confirm we can go from ~2m40s to <15s
