### ISSUE TITLE
Status report for cf conventions for probabilistic data

### ISSUE THREAD

**Issue by fionaRust** [metoppv/improver#159]
As a developers of IMPROVER we want a status report for cf conventions for probabilistic data so that we understand the issues with cf conventions. This will provide information to the next set of investigations into cf standards for probabilistic data.

Related issues: Epic #91 

This story is the first step towards agreeing metadata for certain types of data within IMPROVER. We first want to understand the problems with cf standards for percentiles, probabilities and thresholds within IMPROVER.

Acceptance criteria:
 * Produce a status report of where things are with regards cf conventions for percentiles, probabilities, and threshold data. 
* Highlight where conventions exist and where they don't and how they could be interpreted.
 * Provide examples of how cubes may look as appropriate
 * Talk to Mark Hedley, read the cf conventions and read the report produced by the Americans on cf standards for probabilistic data.
* Spend no more than 8 days on this?

**Comment by Katie-Howard** [comment]
I have written a first draft of the report. It still has a few things to confirm or add to it (basically the names of possible people to work with - I'm waiting for Mark Hedley to confirm spellings and contacts, etc). The report looks like it's 19 pages long, but a lot of that is appendices with examples of what metadata might look like, and also references, etc. 

I've attached a copy of the report, and also the documents that @bayliffe sent me about WISPS. Let me know what you think, and I'll redraft when I've got all your comments.

[#159 CF status report v2.docx]
[WISPS MOS Equation File 0 1.pdf](https://github.com/metoppv/improver/files/1172375/WISPS.MOS.Equation.File.0.1.pdf)
[WISPSNetCDFEncodingv0.1.docx](https://github.com/metoppv/improver/files/1172376/WISPSNetCDFEncodingv0.1.docx)
[WISPSOverviewv0.1.docx](https://github.com/metoppv/improver/files/1172377/WISPSOverviewv0.1.docx)


(https://github.com/metoppv/improver/files/1172374/159.CF.status.report.v2.docx)

**Comment by bayliffe** [comment]
@Katie-Howard : Laurence is going to go through this document as a second review, so expect some further comments from him.

**Comment by Katie-Howard** [comment]
I've done another update incorporating the feedback I was given. It is again on our temporary conventions page.

**Comment by bayliffe** [comment]
Good work, thanks Katie.
