### ISSUE TITLE
Weighted blend plugin CLI

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#16]
As an IMPROVER suite developer, I want a weighted mean blending plugin command line interface for using it so that I can experiment with time lag weights.

Acceptance criteria:
 * Include command line interface script as in #5
 * Create technical tests for the Command Line Interface (CLI)
 * Use the Command Line Interface to test on some real data to generate known good output.

**Comment by carolinejjones** [comment]
@benfitzpatrick , @TomekTrzeciak I'm hijacking this issue to cover the CLI for Blending. I hope that is OK.

**Comment by carolinejjones** [comment]
Closing this ticket as it is a duplicate of #110
