### ISSUE TITLE
improver tests: pep8 Python in bin files

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#160]
As an IMPROVER developer I want pep8 _and pylint_ to be run on Python files under `bin/` so that I can be more confident my Python scripts conform to the standards.

Related issues@ #179 

Acceptance criteria:
 * Amend `improver tests` to test `pep8` and _`pylint`_ on Python scripts under the `bin` directory

**Comment by fionaRust** [comment]
We should also update codacy to check the additional files too.

**Comment by fionaRust** [comment]
Closed by #223
