### ISSUE TITLE
Lazy VS no lazy optimisation

### ISSUE THREAD

**Issue by cpelley** [metoppv/improver#1612]
A number of calls have already been shown to perform much worse with use of lazy loading since the iris-dask change of behaviour of chunking.

More info https://github.com/metoppv/improver/issues/1579#issuecomment-939875297

This issue is in capturing the differences observed when using lazy and non-lazy loading in our latest environment.
Potentially we can then selectively choose which calls should be made non-lazy.

**Comment by cpelley** [comment]
Some early rough data coming in, looking at some limited run from `imengluk`:

```
label:		column_name
command0:	--use-compress-program=pigz
command1:	apply-lapse-rate
command2:	apply-night-mask
command3:	apply-reliability-calibration
command4:	combine --operation
command5:	combine --operation --new-name
command6:	combine --operation --new-name --broadcast-to-threshold
command7:	convection-ratio --model-id-attr
command8:	extract --constraints --constraints
command9:	feels-like-temp --model-id-attr
command10:	generate-realizations
command11:	interpolate-using-difference
command12:	lightning-from-cape-and-precip --model-id-attr
command13:	nbhood --neighbourhood-output --neighbourhood-shape --radii --halo-radius
command14:	nbhood --neighbourhood-output --neighbourhood-shape --radii --lead-times --halo-radius
command15:	nbhood --neighbourhood-output --neighbourhood-shape --radii --lead-times --halo-radius --remask
command16:	nbhood-land-and-sea --radii
command17:	nbhood-land-and-sea --radii --lead-times
command18:	phase-change-level --phase-change --grid-point-radius
command19:	phase-change-level --phase-change --horizontal-interpolation --grid-point-radius
command20:	phase-probability --radius
command21:	recursive-filter
command22:	regrid --regrid-mode --land-sea-mask-vicinity --regridded-title
command23:	regrid --regrid-mode --regridded-title
command24:	relabel-to-period --period
command25:	shower-condition-probability --cloud-threshold --convection-threshold --model-id-attr
command26:	sleet-probability
command27:	standardise --attributes-config
command28:	standardise --new-name
command29:	temp-lapse-rate --dry-adiabatic --model-id-attr
command30:	threshold --collapse-coord --comparison-operator --threshold-units --threshold-config
command31:	threshold --collapse-coord --comparison-operator --threshold-units --threshold-values
command32:	threshold --comparison-operator --threshold-units --threshold-config
command33:	time-lagged-ensembles
command34:	uv-index --model-id-attr
command35:	weighted-blending --coordinate --cycletime --y0val --ynval --weighting-method
command36:	weighted-blending --coordinate --weighting-method --y0val --ynval
command37:	wet-bulb-temperature --convergence-condition
command38:	wet-bulb-temperature-integral
command39:	wind-direction
```

![image](https://user-images.githubusercontent.com/2071643/140785653-1283989e-9760-4e30-a94a-729d5a857c9a.png)

We can see there are performance implications going in either way.

**Comment by tjtg** [comment]
The first listed item `command0: --use-compress-program=pigz` looks like that's a `tar` command rather than an `improver` command.

There's a noticeable change in run time for this `tar` command (9.9 vs 11.8, ~19% difference) that shouldn't be affected by iris/dask options.

**Comment by cpelley** [comment]
> The first listed item...

Thanks for your interest @tjtg.  Yes it is a tar command - I have updated the above to make things clearer (now appears as the last command39).

> Is there some other variability or overhead included in these results, such as HPC job submission?

The timings are extracted from each jobs `job-timings.tsv`.  I'm not sure why they differ but possibly there is a significant difference between the files involved.  For now I think I will be constraining the investigation to the lazy vs no lazy loading but I'll take note - it would certainly be good to understand whether the variability can be explained by the operation or not.

**Comment by cpelley** [comment]
Adding more model runs to the mix to get more information on candidate calls of likely benefit to nolazy loads:
![image](https://user-images.githubusercontent.com/2071643/140967426-e93870ab-67b3-49fc-8adf-6942cc11b38d.png)

Some actually perform much worse without lazy loading.
We also naturally preclude those calls where an out of memory results (higher dimensional cases).

The following function calls then demonstrate the greatest improvement from non-lazy loading:

149% improver interpolate-using-difference
73% improver nbhood-land-and-sea --radii
117% improver phase-change-level --phase-change --grid-point-radius
124% improver phase-change-level --phase-change --horizontal-interpolation --grid-point-radius
41% improver phase-mask --model-id-attr
36% improver regrid --regrid-mode --land-sea-mask-vicinity --regridded-title
45% improver spot-extract --extract-percentiles --new-title
27% improver standardise --attributes-config
24% improver standardise --attributes-config --coords-to-remove
26% improver standardise --attributes-config --new-name --new-units --coords-to-remove
170% improver wet-bulb-temperature --convergence-condition
140% improver wet-bulb-temperature-integral
24% improver wind-direction
64% improver wxcode --wxtree

**Comment by cpelley** [comment]
Interesting that with running the suites for 6hours that we no longer see certain calls identified in the above tables:
```
Difference	avt lazy(s)	avt nolazy(s)	ncalls lazy	ncalls nolazy	Command
149%		72		10		1075		188		improver interpolate-using-difference
172%		137		10		1075		188		improver wet-bulb-temperature --convergence-condition
143%		23		3		1075		188		improver wet-bulb-temperature-integral
34%		9		6		1043		144		improver wind-direction
```

**Comment by cpelley** [comment]
Let's see performance varies across those commands identified above when we include all command variants.
This might help in understanding how to best apply the no-lazy load on a problem by problem basis.

```
  min % diff	min t lazy(s)	min t nolazy(s)	mean % diff	mean t lazy(s)	mean t nolazy(s) max % diff	max t lazy(s)	max t nolazy(s)	ncalls lazy	ncalls nolazy	Command
* 119%		34		8		129%		83		17		93%		103		37		980		1120		improver blend-adjacent-points --coordinate --central-point --blend-time-using-forecast-period --units --width
* 25%		129		99		24%		139		109		28%		168		126		17		21		improver nowcast-accumulate --attributes-config --max-lead-time
  7%		8		8		4%		28		30		9%		53		48		973		1112		improver phase-change-level --phase-change
* 124%		12		2		113%		16		4		105%		26		8		102		38		improver phase-change-level --phase-change --grid-point-radius
  2%		5		5		3%		22		23		33%		47		33		973		1112		improver phase-change-level --phase-change --horizontal-interpolation
* 130%		12		2		118%		17		4		106%		25		7		102		38		improver phase-change-level --phase-change --horizontal-interpolation --grid-point-radius
* 50%		13		8		64%		36		18		21%		51		41		2021		2554		improver wxcode --wxtree
```

We can see that all commands except the `phase-change-level` seem to be called with one combination of keyword arguments.  Furthermore, the `phase-change-level` command calls don't seem to show a significant difference in performance for those command variances not benefiting from the no-lazy load.  This means that we could simply switch these over to a no-lazy load without conditionals (straight forward code change).
