### ISSUE TITLE
ECC bounds check - ensure error message prints the data value rather than the bounds value

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#1621]
While investigating extreme values from the MOGREPS-G model in PS45, @MoseleyS spotted that the error messages were apparently printing the bounds value rather than the data value that exceeded the bound. It is not clear if this happens each time.

Acceptance Criteria

- At least one unit test confirms that the error message includes the exceeding data value, rather than these being lost in the Regex match.

**Comment by bayliffe** [comment]
Exceptions raised in suite logs related to ECC bounds exceedence:

> ValueError: Forecast values exist that fall outside the expected extrema values that are defined as bounds in ensemble_copula_coupling/constants.py. Applying the extrema values as end points to the distribution would result in non-monotonically increasing values. The defined extremes are [173.15 333.15], whilst the following forecast values exist outside this range: [333.82812].

> ValueError: Forecast values exist that fall outside the expected extrema values that are defined as bounds in ensemble_copula_coupling/constants.py. Applying the extrema values as end points to the distribution would result in non-monotonically increasing values. The defined extremes are [173.15 333.15], whilst the following forecast values exist outside this range: [337.51562].

These exceptions do not show the behaviour described by this ticket.
