### ISSUE TITLE
Update Leigh's breaking-changes Doc

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#1622]
We need to ensure that all our meta-data changes, including changes to supplied parameters and time-steps, are documented for the 1.0.0 release so that the ServiceHub team know what to expect.

The information needs to go on this [OneNote page](https://metoffice-my.sharepoint.com/personal/leigh_holly_metoffice_gov_uk/_layouts/OneNote.aspx?id=%2Fpersonal%2Fleigh_holly_metoffice_gov_uk%2FDocuments%2FIMPROVER%20Team&wd=target%28Go%20Live.one%7C88D059F2-E05E-4851-9150-43297993900C%2FLive%20release%20comms%20for%20SH%5C%2FUsers%7C6E1CD9B3-1A67-4FCB-A094-1FC4E3E92934%2F%29)

**Comment by fionaRust** [comment]
We ended up putting all the information about the changes in this spreadsheet on sharepoint. https://metoffice.sharepoint.com/:x:/r/sites/scienceimproverservice/Docs/IMPROVER%20OS45%20sent%20diagnostics%20and%20breaking%20changes.xlsx?d=w58537751764d41a4b805c588147ad1aa&csf=1&web=1&e=jyUixm&isSPOFile=1
