### ISSUE TITLE
Improve Pylint scores 

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#164]
As an IMPROVER developer, I want every module to be at least acceptable (`>=8`) to Pylint so that I know all my code is good, not just good as an average.

Ahead of this work, we need to decide whether we want to allow two-letter variable names, which are currently lowering the pylint scores. We also need to confirm that we're not trying to fix every pylint warning, specifically those warnings related to interfaces e.g. too many variables being passed to a function, which may reduce the readability of the code. The focus is to obtain pylint scores >= 8.

Acceptance criteria:
 * Run `improver tests pylint` and address obvious issues, using best judgement for things like naming quibbles
 * Run `pylint --rcfile=/some/path/to/improver/etc/pylintrc` on each improver lib module and check that the score is 8 or better. If not, either correct the code, or make sure there are good reasons for it and report those on this issue.

**Comment by bayliffe** [comment]
Completed.
