### ISSUE TITLE
1.0.4 release

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#1649]
We'd like to cut a new release of metoppv/improver to incorporate a metadata consistency fix for weather symbols.

[Release checklist](https://github.com/metoppv/improver/blob/master/doc/source/Code-Style-Guide.rst#making-a-new-release):
- [x] Inform the core developers across institutions and wait for approval.
- [x] On the command line, check out the commit on master that you want to tag. For a given version such as 1.1.0, run: git tag -a 1.1.0 -m "IMPROVER release 1.1.0". Then run: git push upstream 1.1.0.
- [x] Go to Draft a new release page. Select your new tag under 'tag version'. The release title should be the version number (e.g., 1.1.0). Publish the release after adding any description text.
- [x] Update the version number and sha256 checksum in the meta.yaml file of the conda-forge recipe by opening a pull request in the improver-feedstock repository. A pull request may be opened automatically for you, in which case just check it. The checksum of the compressed .tar.gz IMPROVER source code can be obtained via openssl sha256 <file name>. Currently the people with write access to the improver-feedstock repository are @benfitzpatrick, @PaulAbernethy, @tjtg and @lucyleeow. You can ping one of these people to merge your pull request.

**Comment by tjtg** [comment]
1.0.4 has been released - see [release on github](https://github.com/metoppv/improver/releases/tag/1.0.4) and corresponding [conda-forge package](https://anaconda.org/conda-forge/improver/files?version=1.0.4).
