### ISSUE TITLE
Generate percentiles from neighbourhood.

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#166]
As an Improver developer I will need to blend percentile data created from collapsed realizations, collapsed neighbourhoods, and from multiple models.

For a discussion of the method, see [Combining_Probabilities.pdf](https://github.com/metoppv/improver/files/1128018/Combining_Probabilities.pdf)

Prerequisite #175 

Acceptance criteria:
* Build the capability to extract percentiles from a neighbourhood.
* Create a plugin that can be used to blend percentile data (from StaGE plugin?), including that extracted from neighbourhoods.
* Test the method against direct percentile calculation from all source data and document the degree of disparity.

**Comment by carolinejjones** [comment]
I'm looking at this as part of #176

**Comment by bayliffe** [comment]
Simon is having a look through the document provided.

**Comment by carolinejjones** [comment]
Pull request #212 for plugin to blend percentile data

**Comment by fionaRust** [comment]
Original PR written by Stephen: #213 
New PR to supersede Stephen's written by Gavin:  #259 
Refactoring PR: #247 - merged

**Comment by fionaRust** [comment]
All PR's merged, slides done, Nigel is happy testing has been completed.
