### ISSUE TITLE
Add freezing rain plugin and CLI

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#1660]
As an IMPROVER science lead, I want a plugin and CLI to generate probabilities of freezing rain so that it can form part of an IMPROVER suite chain producing a blended level-3 freezing rain product.

Related issues: https://github.com/metoppv/mo-blue-team/issues/225

Only one temperature threshold is required, 273.15K. We want to multiply the probability of being **below** this threshold (data are above the threshold) by the sum of the rain and sleet probabilities for each rain/sleet threshold.

Acceptance criteria:
 * CLI accepts inputs in any order of: probability of rain (rate or accumulation), probability of sleet (rate or accumulation), probability of screen temperature (instantaneous or minimum-over-time). We could consider accepting any cube with temperature in the title, in case another developer wants to put in surface temperature.
 * Plugin rejects inputs that are not temporally consistent (all instantaneous, or all over identical time window)
 * Plugin rejects inputs that do not have consistent realization coords (but should run with and without this)
 * Plugin returns a single cube of probability of freezing rain with title `probability_of_lwe_freezing_rainfall_rate_above_threshold` and threshold coord name `lwe_freezing_rainfall_rate` (and equivalent for accumulations). The units and threshold values are inherited from the rain and sleet cubes, which must match. The cube passes the `inspect-metadata` CLI without errors.
* Acceptance test uses data for a real freezing rain case. If it helps, widespread freezing rain was forecast for Sunday 14th Feb 2021 (from 10th) and possibly also across northern areas on 15th Jan 2022 (forecast from 13th). Another freezing rain case predicted by UKV/UKPP for Mon 29th Nov 2021 from Thu 25th Nov.

**Comment by bayliffe** [comment]
Two cache building suites launched to gather data ready for building acceptance tests:
http://fcm1/rose-bush/cycles/ppdev/?suite=uk_freezing_rain_cache (20210210T1200Z --> 20210210T2300Z)
http://fcm1/rose-bush/cycles/ppdev/?suite=gl_freezing_rain_cache (20210210T1200Z --> 20210210T1800Z)

Intended freezing rain period is 13th/14th February 2021.

**Comment by bayliffe** [comment]
### First output
The calculation `(P(sleet rate) + P(rain rate)) x P(temp < 0C)` that we are using for our new diagnostic, using MOGREPS-UK inputs, gives a signal for some freezing rain this afternoon in Scotland. GPP does not give a signal using the same inputs, as can be seen below.

GPP output for 15Z 25/02/2022 at T+12:
![image](https://user-images.githubusercontent.com/28042362/155699596-8efdea16-132a-4771-b029-776a99abb1f8.png)

New diagnostic output for 15Z 25/02/2022 at T+12:
![frz_rain_rate_same_scale](https://user-images.githubusercontent.com/28042362/155699928-8c6cf5a0-c277-4a4c-af89-04649d96f187.png)

**Comment by bayliffe** [comment]
### Issues encountered

Stephen's envisaged plan for the freezing rain diagnostic was as follows:

![image](https://user-images.githubusercontent.com/28042362/156158321-592e01fb-939a-4c8c-a239-3e0fd69cc468.png)

One significant issue with this plan is a mismatch in the ensemble members. The `tempminmem1h` step provides 18 members, whilst the `precipphase` steps provide only 3 members. As such the diagram needs modification to remove the freezing rain blendcycles step, and instead include a time lagged ensemble step for the rain and sleet diagnostics following `precipphase` but prior to the calculation of the freezing rain diagnostic.

This is conceptually simple enough. The time lagging applied to the precip phases should mirror what has been done to the raw temperature forecasts passed into ECC. As such we should still be matching related ensemble members, though we need to check. The more tricky issue is that this step begins to become very memory hungry. The inputs to the freezing rain CLI will be:

rain / sleet cubes: `18x23x970x1042`
temperature cube: `18x970x1042`

This is quite a lot of data to handle. In a simple schematic we would create a freezing rain diagnostic with shape `18x23x970x1042` and pass this to `realization_collapse`. However that involves a lot of data in memory and IO. As such I will redesign the freezing rain plugin to slice over realizations of rain / sleet / temperature, to accumulate the probabilities for each precip threshold, and then average this data by the number of contributing ensemble members. This fixes the various contributing cycles as equally weighted, but it also massively reduces the data in memory and the amount of IO. It removes the `realization collapse` step from the chain as well.

**Comment by bayliffe** [comment]
### Acceptance test data

I've generated freezing rain diagnostics using the proposed method over the 13th and 14th February 2021, with the forecasts produced on the 10th. The 14th was proposed in the description, and the 13th also has a record of freezing rain in [Roger Brugge's weather diary](http://www.met.reading.ac.uk/~brugge/diary2021.html#202102). I include 3-hourly output over the two days below. This is not a "freezing rain" signal, but rather a precipitation falling through a cold lower atmosphere diagnostic; this has been decided as the right approach for now, though it gives a fairly widespread signal in the plots below; thresholds of 0, 0.1, and 1mm are shown left to right.

![frzrain01](https://user-images.githubusercontent.com/28042362/156993446-d87d6bea-cf8c-4da2-a8f2-a104530c714e.png)
![frzrain02](https://user-images.githubusercontent.com/28042362/156993449-58ffa413-eaf0-44d9-b6f2-9c6fc27b8dec.png)
![frzrain03](https://user-images.githubusercontent.com/28042362/156993455-63043171-22ab-40c8-a700-fd4684862409.png)
![frzrain04](https://user-images.githubusercontent.com/28042362/156993458-01b5d837-dbd8-4d05-ba35-558db6410508.png)
![frzrain05](https://user-images.githubusercontent.com/28042362/156993416-669de526-9d10-4e60-993c-6e94028d2b88.png)
![frzrain06](https://user-images.githubusercontent.com/28042362/156993423-38f4f9dc-d7d4-464e-b9be-65659fb1767e.png)
![frzrain07](https://user-images.githubusercontent.com/28042362/156993425-b9ab7d9f-f1cc-4b7b-8051-8601b9dbc6ed.png)
![frzrain08](https://user-images.githubusercontent.com/28042362/156993428-3e20481c-79bb-461a-b168-9fbe15810895.png)
![frzrain09](https://user-images.githubusercontent.com/28042362/156993430-c91a5cfe-d332-4e96-b004-9f9a34d7f599.png)
![frzrain10](https://user-images.githubusercontent.com/28042362/156993432-247d0836-3bce-4d84-9966-2f38916d9475.png)
![frzrain11](https://user-images.githubusercontent.com/28042362/156993434-253dd76b-1cb3-4152-8715-2faab8de0f84.png)
![frzrain12](https://user-images.githubusercontent.com/28042362/156993436-1b66c800-b75c-4135-b70b-81a995871e52.png)
![frzrain13](https://user-images.githubusercontent.com/28042362/156993438-95c31599-ec90-452f-b254-69afae84d468.png)
![frzrain14](https://user-images.githubusercontent.com/28042362/156993440-3d3ec6de-374d-4871-b8f2-ddb935c115dd.png)
![frzrain15](https://user-images.githubusercontent.com/28042362/156993441-9f2d6a57-9f1b-42be-85df-ef4ad4c091dd.png)
![frzrain16](https://user-images.githubusercontent.com/28042362/156993444-e9be11c7-65b8-4c65-aaab-a0211fd6fa19.png)

**Comment by bayliffe** [comment]
### Acceptance test data 3-hour period

Below is plotted the acceptance test data produced using ENGLUK over a 3-hour period, with this period spanning 03Z to 06Z on Sunday 14th February 2021.

![acc_test_3h_rain](https://user-images.githubusercontent.com/28042362/157002024-1d119b98-5c60-4ff3-a6da-2d00d7117380.png)
![acc_test_3h_sleet](https://user-images.githubusercontent.com/28042362/157001990-1f2eade9-8450-4328-8a29-b54d8490d0e6.png)
![acc_test_3h_temp](https://user-images.githubusercontent.com/28042362/157002075-40477be8-8a82-4f8b-93a5-158a16205867.png)
![acc_test_3h_kgo](https://user-images.githubusercontent.com/28042362/157002090-16fa1015-c2e1-420d-8ff3-764bc62458de.png)

**Comment by bayliffe** [comment]
In the case of the KGO, the columns represent the realizations; I've included more the mogreps-g just to highlight that it is more than a 3-member ensemble.

**Comment by bayliffe** [comment]
All plots above have been updated following a bug fix to the plugin; prior to this a smaller number of realizations for any diagnostic was being accommodated by broadcasting. This did not ensure that realizations were matching.

**Comment by MoseleyS** [comment]
Acceptance test data merged
