### ISSUE TITLE
regrid nearest with mask fails for input grid extent less than target grid extent

### ISSUE THREAD

**Issue by anja-bom** [metoppv/improver#1718]
When running land-sea-aware regridding there is an issue where the input grid-extent is smaller than the target grid-extent ( there are output points where no mapping to input points)

Command run:
```
improver regrid --regrid-mode nearest-with-mask input.nc output_grid.nc input_landmask.nc --output output.nc
```
input_landmask.nc and input.nc have grid extents **smaller** than that of output_grid.nc

The error:
```
improver/utilities/spatial.py", line 458, in maximum_within_vicinity
    unmasked_cube_data[cube.data.mask] = -np.inf
OverflowError: cannot convert float infinity to integer
```
The `-np.inf` does not convert to an integer, replacing this with a regular number (eg. netcdf fill-value for integers) would solve the issue.

Acceptance criteria:
 * Agreed approach to handling initialisation of unmasked_cube_data 
 * Code changes so CLI runs successfully independent of size of relevant extents of initial and target grids
 * All acceptance and unit tests pass with code-changes implemented.

**Comment by tjtg** [comment]
It would also be worthwhile to add unit and/or acceptance tests for this case where the input grid is smaller than the output grid.
