### ISSUE TITLE
Enhancement to phase chains to get hail-melt level (and ice-pellet level) and a hail-melted mask.

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#1743]
For the Hail from Global Data work, we need the `phase-change-level` and `phase-probability` CLIs and associated Plugins modified to calculate melting hail data, which will occur when the melting integral reaches 5000. K m.

Also consider how easy it would be to calculate an ice pellet level, that is, the point at which rain would freeze into ice pellets, this is a negative melting value which isn't currently calculated. We need to know  the equivalent integral for sub-zero temperatures in the case where snow HAS melted into either sleet or rain so that if a warm layer of air exists above a very cold layer, then ice pellets can be diagnosed instead of freezing rain. I'm not sure what this freezing threshold should be yet.

Acceptance criteria:
 * CLIs that can calculate a hail melting altitude and a hail melting mask, with acceptance tests showing this
 * Any thoughts on calculating an ice pellet level

**Comment by mspelman07** [comment]
I've updated the plugins to calculate the melting hail data see metoppv/improver#1762

In terms of the Ice pellet level, depending on how accurate you want to be, you could assume the melting/freezing process is reversible without any losses in energy. This could then just involve adding in an extra case to the plugins (where you say the ice would melt if it was falling upwards away from the ground so it'll freeze if it falls towards the ground). However this wouldn't be taking into account the latent heat or any other energy losses so this might not be accurate enough. I don't know if you could include the additional energy needed to freeze in the threshold value by needing a higher threshold to provide the needed energy?
