### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ColemanTom** [metoppv/improver#1744]
I was looking at the [contributing document](https://github.com/metoppv/improver/blob/master/CONTRIBUTING.md#contributing-code-or-reviewing) and noticed two links (e.g. definition of done,  and guidance for reviewing code) are broken.

Acceptance criteria:
 * Definition of done link is accurate
 * Guidance for reviewing code is accurate

**Comment by MoseleyS** [comment]
Note that the Guidance for Reviewers refers to Travis, which should be Continuous Integration.
