### ISSUE TITLE
Strategy for blending and processing percentiles.

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#175]
As the product owner I want IMPROVER to be able to deal with percentiles as well as probabilities for neighbourhood processing and blending.

Consider three approaches:
1. Compute percentiles across ensemble members and neighbourhoods simultaneously
2. Compute percentiles across members and then apply neighbourhood processing in an appropriate way
3. Compute percentiles across neighbourhoods and then across ensemble members in an appropriate way

Acceptance criteria:
 * Write a strategy for the use of percentiles with neighbourhood processing and blending.
 * Include discussion of percentile calculations with neighbourhoods.
 * Include discussion of blending percentiles from two distributions.
 * Make reference to and discuss the three approaches listed above.

**Comment by carolinejjones** [comment]
Updated with changes suggested by Simon.

**Comment by bayliffe** [comment]
Document produced fulfilling the brief. Ready to close.
