### ISSUE TITLE
Strategy for blending UKV and Mogreps-UK

### ISSUE THREAD

**Issue by carolinejjones** [metoppv/improver#176]
the product owner I want IMPROVER to be able to blend time-lagged UKV forecasts with time-lagged MOGREPS-UK forecasts

Related issues: #166 

Develop the strategy for blending UKV probabilities/percentiles with MOGREPS-UK probabilities/percentiles for a single validity time.

Acceptance criteria:
 * Written strategy document
* Revise epic ticket #136 to reflect strategy
 * Update [Documentation on Blending](https://github.com/metoppv/improver/files/1041960/timelag_blending_function_NR310517.pdf )

**Comment by carolinejjones** [comment]
Revised documentation has been created IMPRO-185

**Comment by carolinejjones** [comment]
#136 has been revised to reflect strategy.

**Comment by bayliffe** [comment]
Shares document with #175 . Complete.
