### ISSUE TITLE
Help auto-detect improver licence

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#1776]
Our licence for this repository is BSD 3 clause, but I think it isn't being picked up automatically by GitHub (e.g. on the right hand status bar). GitHub uses https://github.com/licensee/licensee to autodetect - tweak the header of the text so that it is correctly auto detected.

**Comment by cpelley** [comment]
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license for more info.
