### ISSUE TITLE
Set the radii of the neighborhood

### ISSUE THREAD

**Issue by NMC-DAVE** [metoppv/improver#1793]
hi guys，
      In improver，the radii of the neighborhood must be in meters. So can I set the radii in the number of grid points directly?  I can use the NBhood function to the lon/later projection. Thanks very much! 
                   Dave

**Comment by bayliffe** [comment]
Dave,

We have not implemented an option to set the number of grid points directly as this must be used with caution. Whilst it would be fine on a regional equal areas projection, i.e. a Lambert azimuthal equal area projection, it would require more thought on a global Plate Carree projection.

Consider the diagram below. The red box shows an area defined on a Plate Carree grid using a number of grid boxes, i.e. 7 grid boxes in latitude and 7 in longitude. This has been reprojected onto an equal areas projection in this diagram. You can see that the area in the north (top) of the red box is smaller than the area in the south (bottom). This means that if we applied neighbourhood processing in this way we would bias our probabilities towards the equator. The effect would be small using a small neighbourhood radius, but could become important if the radius were large (hundreds of km). For example, you might increase the probability of achieving warm temperatures further north than is realistic.

![lat_lon_example](https://user-images.githubusercontent.com/28042362/187414502-e9808e09-513e-41e6-be4b-1c6746e7bd2f.jpg)

Defining the radii as a distance allows (potentially) for the correct neighbourhood shape to be defined to avoid the introduction of a bias. We don't currently have code to do this within IMPROVER as we use a fast method for use with a square kernel which would not be applicable and would make the neighbourhooding prohibitively slow. We do not apply neighbourhood processing to our global domain at present for this reason.

If you were happy with the risks involved, please feel free to raise a pull request that implements the option to use a grid-point radius in the neighbourhooding and we will review it. We have made one such [extension before to the OccurrenceWithinVicinity plugin](https://github.com/metoppv/improver/blob/1987d17c58bb926b36cf8983c7d0bd2f1530d5e5/improver/utilities/spatial.py#L395).

Regards.

**Comment by NMC-DAVE** [comment]
Thanks very much, bayliffe. I will use the map projection transform for converting lagoon to equal area.
