### ISSUE TITLE
How to use nbhood functions?

### ISSUE THREAD

**Issue by NMC-DAVE** [metoppv/improver#1799]
Hi,
    I try to use the "nbhood" functions in IMPROVER, and have
some questions:
    1) If I want to calculate the neighborhood probabilities, do I 
have to use the threshold function to get binary fields?
    2) If calculating the neighborhood percentiles, the input cube
is the original data or thresholded data?
   3) So far, do "nbhood" functions support the ‘‘neighborhood maximum
ensemble probability’’ (NMEP) ([Schwartz et al, 2017](https://journals.ametsoc.org/view/journals/mwre/145/9/mwr-d-16-0400.1.xml))?
   4) Is there any plan to support the neighborhood probability
with ensemble agreement scale ([Blake et al, 2018](https://journals.ametsoc.org/view/journals/wefo/33/4/waf-d-18-0035_1.xml))
   Thanks very much.
                                                                                      Dave

**Comment by MoseleyS** [comment]
Hello @NMC-DAVE. Thanks for your questions.

1) If I want to calculate the neighborhood probabilities, do I
have to use the threshold function to get binary fields?

Yes, this is the only method for converting data in diagnostic-space into probability-space.

2) If calculating the neighborhood percentiles, the input cube
is the original data or thresholded data?

The input data must be thresholded first.

3) So far, do "nbhood" functions support the ‘‘neighborhood maximum
ensemble probability’’ (NMEP) ([Schwartz et al, 2017](https://journals.ametsoc.org/view/journals/mwre/145/9/mwr-d-16-0400.1.xml))?

IMPROVER does support NMEP. This is defined as an occurrence-in-vicinity - for example, to calculate the probability of heavy precipitation occurring within 10km of a point. As this is related to the threshold, it is the `improver threshold` command that contains these options, not `improver nbhood`.

4) Is there any plan to support the neighborhood probability
with ensemble agreement scale ([Blake et al, 2018](https://journals.ametsoc.org/view/journals/wefo/33/4/waf-d-18-0035_1.xml))

Yes, this is something that we would like to support. We have a plan to use inter-member comparisons (Fraction Skill Score) to determine the local neighbourhood radius. At the moment, we do not have the resources to work on this.

Regards.
Stephen

**Comment by NMC-DAVE** [comment]
Thanks very much.
