### ISSUE TITLE
Factor out useful SpotData utilities

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#180]
As an IMPROVER developer, I want to be able to harvest the array of utilities that have been developed for SpotData so that these utilities can be easily used by other modules within IMPROVER.

Discuss any potential overlap with those working on #317 

Please note that ther are likely to be >20 SpotData utilities that need to be considered. It would be sensible to extract these in a piecemeal fashion, with small PRs covering each change.
Likely candidates:

1. def _build_coordinate
(note: a version of build_coordinate based but not identical _build_coordinate has been added to utilities/cube_manipulation.py for #209 )

Acceptance criteria:
 * Ensure that all utilities from SpotData that have a general application have been moved to be top-level utilities.
 * Use multiple PRs to ensure easy review.
 * Ensure that the SpotData functionality remains unchanged after refactoring.
 * Ensure unit tests are moved.

**Comment by carolinejjones** [comment]
Edited description to add that a version of build_coordinate based but not identical _build_coordinate has been added to utilities/cube_manipulation.py for #209

**Comment by gavinevans** [comment]
PRs now merged.
