### ISSUE TITLE
Remove local time zone code from IMPROVER

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#1834]
IMPROVER currently contains code for creating composite fields that include data valid at the same local-time across the given domain. For example, a composite global field might be created that shows the temperature across the globe at 12pm local time on a given date for each grid point.

This ticket proposes the removal of this functionality as it is not in use as far as we are aware.

Acceptance criteria:
- remove [TimezoneExtraction](https://github.com/metoppv/improver/blob/5aa88631d315489c2ae7adc26a57a2e5e938d953/improver/utilities/temporal.py#L321 )plugin and associated unit tests
- remove the [GenerateTimezoneMask](https://github.com/metoppv/improver/blob/5aa88631d315489c2ae7adc26a57a2e5e938d953/improver/generate_ancillaries/generate_timezone_mask.py#L65) ancillary creation plugin and associated unit tests
- remove the [map-to-timezones CLI](https://github.com/metoppv/improver/blob/master/improver/cli/map_to_timezones.py), associated acceptance tests, and test data
- remove the [generate-timezone-mask-ancillary CLI](https://github.com/metoppv/improver/blob/master/improver/cli/generate_timezone_mask_ancillary.py), associated acceptance tests, and test data

**Comment by bayliffe** [comment]
Acceptance test data: `/data/users/mspelman/acceptance_test_data` (branch: impro1834_remove_time_zone)

**Comment by bayliffe** [comment]
Acceptance test data branch: impro1834_remove_time_zone

**Comment by MoseleyS** [comment]
Passing back to @bayliffe to glance at the post-review changes before merging.

**Comment by bayliffe** [comment]
Merged along with acceptance test data changes.
