### ISSUE TITLE
Percentile resampling modified to constrain output percentiles

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#1835]
The `generate-realizations` CLI allows for probabilities or percentiles to be converted to realizations using ensemble copula coupling (ECC). If percentile inputs are provided these are resampled to give equally spaced percentiles prior to the use of ECC. The number of percentiles is equivalent in the outputs to the inputs. This can lead to sampling percentiles that are not captured by the input distribution, which then relies upon interpolation between the lowest available percentile in the input and the ECC bounds to populate these extreme percentiles. These can therefore contain forecast data that is not representative of the conditions.

Acceptance criteria:
- resampling percentile data is constrained to ensure that the resampled percentiles fall within the range for which data is available.
- realizations generated by the `generate-realizations` CLI are checked to ensure they subsequently contain sensible values.

**Comment by MoseleyS** [comment]
Adding this constraint is easy enough, but we then fall foul of a check in Rebadge Percentiles As Realizations because the percentiles are not evenly spaced. Instead, we probably need to calculate a 1st and 99th percentile along with all the others.

**Comment by MoseleyS** [comment]
Here's an image generated from data where 36 realizations of `tempminmem3h` were generated from percentiles starting at the 5th, were aggregated into min-over-12h, then converted to the 5th percentile again:
![image](https://user-images.githubusercontent.com/23079172/202484587-9653f712-f343-433e-93aa-7bc5c7eec50c.png)

The following image comes from a test suite where two extra percentiles (1st and 99th) were added. After the second cycle (so 36 members available), the same processing step yields this:

![temperature_5_percentile](https://user-images.githubusercontent.com/23079172/202487502-02174aed-4596-4662-ae33-7e4efa416951.png)

- The suite changes are very simple: https://github.com/MetOffice/improver_suite/pull/1518
- Test suite: http://fcm1/cylc-review/cycles/cfst/?suite=imengl_temp_percs (note that I accidentally left feels-like temperature active, which caused the errors in this suite)

Finally, just to make sure that the 12-hour minimum temperature were not adversely affected, here's the 1st percentile of that:

![temperature_min12_1_percentile](https://user-images.githubusercontent.com/23079172/202489479-dfe52dd3-afd0-44d3-8a69-33b02cd746d6.png)

**Comment by MoseleyS** [comment]
IMPROVER PR https://github.com/metoppv/improver/pull/1836 prevents this being allowed in the future. This needs testing with all the suites as it might trigger a failure somewhere unexpected.

**Comment by MoseleyS** [comment]
Full suite tests. MOGREPS-G and MOGREPS-UK start from 18Z 17th Nov and will end after 06Z 18th. UKVX starts from 00Z 18th and will end after 09Z. MIX TBC

- http://fcm1/cylc-review/cycles/cfst/?suite=imengl_full
- http://fcm1/cylc-review/cycles/cfst/?suite=imengluk_full
- http://fcm1/cylc-review/cycles/cfst/?suite=imenukx_full
- http://fcm1/cylc-review/cycles/cfst/?suite=imukvx_full
- http://fcm1/cylc-review/cycles/cfst/?suite=immix_full

**Comment by gavinevans** [comment]
Just as a comment following our discussion, it would be worth testing any amendments or alternative implementations to https://github.com/metoppv/improver/pull/1836 with an environment with `numba` in it, as the interpolation involved in the `ResamplePercentiles` plugin can either use `numba` or `numpy`.

**Comment by MoseleyS** [comment]
All changes merged or closed. Ticket complete.
