### ISSUE TITLE
Conservation of dimensionality when using Neighbourhooding.

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#185]
As a user of Improver I want cubes to which I apply neighbourhooding to return from the plugin with the same dimensionality as they had when they entered.

Single value dimension coordinates are currently being demoted to scalar coordinates, thus the cube data has a different shape upon return.

Acceptance criteria:
 * Ensure dimension coordinates in returned cubes match the input cube.

**Comment by bayliffe** [comment]
Lovely stuff.

**Comment by fionaRust** [comment]
Closed by pr #227
