### ISSUE TITLE
Apply a neighbourhood mask

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#188]
Prerequisite: #202, (Done) #231 (Done) 
Related issues: #104 (Done) (containing #73 (Done), #74 (Done)), #187 (Done) 
Mask array for topography from #43 (Done)
Follow-on issue: #283 

As the product owner I want IMPROVER to have the capability to use neighbourhoods that mask out inappropriate regions (because they are the wrong height or coastal ...) (process 1). This has largely been implemented in the work @meabhnicguidhir did to make the square neighbourhooding handle masked arrays, but may need adapting/factoring out as appropriate.

There may be several ways to do this. Here is a starting approach that uses a combination of the square neighbourhood processing functionality and array multiplication.

The neighbourhood processing here requires the output to be the sum of values in the neighbourhood and not a fraction. Note that the existing neighbourhood processing functionality assumes that the output should be a fraction.

**Aim**
To apply neighbourhood processing that is restricted to an area defined by a mask array. The mask array could be supplied from an external file, for example, containing topography bands (#43).

Step 1:
Multiply the 2-d array being processed [Input_array] (containing probabilities or values) with a binary 2-d mask array [mask] (or the mask could contain values between 0 and 1) to give a masked version of the array being processed: [Input_array_masked].
Step 2:
Apply neighbourhood processing to the array produced by step 1 [Input_array_masked] to obtain a summation over the non-masked-out grid squares (grid squares with values > 0 in the mask array) in the neighbourhood for every grid square: N[Input_array_masked].
Step 3:
Apply neighbourhood processing to the mask array [mask] to obtain a summation over the non-masked-out grid squares in the neighbourhood for every grid square (grid squares with values > 0 in the mask array): N[mask].
Step 4:
Divide the output array from step 2 N[Input_array_masked] by the output array from step 3 N[mask] to give a fraction/probability at each grid square that has only used the values from the array being processed [Input_array] that are not masked out according to the mask array [mask]. Gives array: NF[Input_array_masked]  (neighbourhood fractions of the masked input array). Note that this needs to deal with dividing by zero and set those grid squares to zero.
Step 5:
This step can be implemented as an option. By re-masking, this gets rid of probabilities that are not within your region of interest but this may not be desirable for a follow-on step to weight across topography bands (#283), where we would like to take into account probabilities from different bands. 
Multiply the fractions/probabilities array output from step 4 NF[Input_array_masked] by the mask array [mask] to get rid of all the fractions/probabilities that are not in the region of interest to give: NF[Input_array_masked_final]
Step 6:
Capability to apply the masked neighbourhood to all altitude bands and combine to give a field of probabilities for each of the altitude bands. This can then be blended to a single probability fields using the blending plugin.

Acceptance criteria:
 * Review existing masked neighbourhood functionality against the steps above.
 * Unit tests
 * Flexibility to deal with any neighbourhood size
 * Flexibility to deal with a binary mask or mask containing fractions 
 * Record speed for discussion.
 * Visual test on simple idealised field
 * Add as an option for neighbourhood to accept a mask.
 * CLI

**Comment by gavinevans** [comment]
For Process 1 (step 1 to step 6), most of this functionality already exists within `nbhood.py`, however, this functionality should be checked to make sure that it behaves as the description above recommends. For step 6, this should work but there's no unit test like this at the moment, so that would need adding. I don't think we've officially actually agreed a metadata convention for a netcdf file with orography bands, although a netcdf file with orography bands is created in [generate_ancillary.py](https://github.com/metoppv/improver/blob/master/lib/improver/generate_ancillaries/generate_ancillary.py ).

Process 2 wraps the functionality developed in #202.

**Comment by bayliffe** [comment]
Now closed.
