### ISSUE TITLE
Apply lapse rate needs limit when a temperature inversion is present

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#1885]
As an IMPROVER Scientist, I want our temperature lapse rate adjustments to adhere to the technique documented in [Sheridan 2010](https://rmets.onlinelibrary.wiley.com/doi/abs/10.1002/met.177), [Sheridan 2013](https://doi.org/10.1002/qj.2159) and [Sheridan 2018](https://doi.org/10.1175/JAMC-D-17-0140.1). 

IMPROVER calculates the temperature lapse rate according to Sheridan 2010, and applies the prescribed limits of DALR and -3.DALR. The value of -3.DALR represents a strongly-inverted temperature lapse rate. Such inverted lapse rates occur in cold air pooling (CAP) in valleys, especially if the valley has a narrow exit, restricting the egress of cold air. The papers discuss the depth of the cold air pool but stop short of prescribing a hard limit. In the Met Office's UKPP and SSPS (a.k.a. BestData) a limit of 70m is applied to the vertical adjustment in inversion conditions as this represents the maximum likely cold air pool depth in the UK. Exceeding 100m is globally rare.

This limit is not applied in IMPROVER which can result in mountainous forecasts with unphysical temperatures. This ticket will enforce this limit such that the first ~~70m~~ 50m of lapse rate adjustment uses the inverted lapse rate value, and subsequent adjustment uses a standard atmosphere lapse rate. 

IMPROVER can be used to adjust both gridded and spot temperatures. The Sheridan 70m limit ought to apply to the cumulative adjustment, not each one individually. @bayliffe has pointed out that when we have blended multiple models together, this is impossible. So I have updated the paragraph above to propose a 50m limit to both the gridded and spot adjustments. This should stop really silly values while still allowing some useful corrections.

Acceptance criteria:
 * Temperature inversions result in a cap to how much lapse rate correction is applied (50m), with remaining adjustments using the standard atmosphere lapse rate
 * Ideally, the two lapse rate adjustment plugins will be refactored into one to reduce maintenance.

**Comment by MoseleyS** [comment]
Recommend building on this refactoring PR: https://github.com/metoppv/improver/pull/1880/files

**Comment by gavinevans** [comment]
Pull request: https://github.com/metoppv/improver/pull/1886
Acceptance test data branch: improver_1885_lapse_rate_limit
