### ISSUE TITLE
Time weighting functionality

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#189]
Prerequisite #202

As the product owner I want IMPROVER to have the capability to include times outside the time of interest or the time window of interest in the generation of probabilities.

Here we will use the triangular weighting function written in #202.

Two variations of this are needed
1. A weighted probability was included in the demo suite and this should be incorporated into IMPROVER (unless it has already)

2. There is also a requirement to find the weighted maximum in the time window in order to give a more appropriate probability for the occurrence at a time if the exact timing doesn't matter. Here we are asking: what is the probability of an occurrence sometime around a time or period of interest?
For example, if a high probability is given that it will rain at 15.00 and it starts to rain at 15.10 (or stops at 14.50), that is still a decent forecast for most people. Or if the probability is specifically stated to be the probability that rain will occur sometime around 15.00 then, again, it is a decent forecast. Or it might be giving a non-zero probability of rain occurring sometime within the time period 12.00 to 18.00 and it rains at 18.10.

Document about time windows for precipitation accumulations: 
[time_windowing_accumulations.pdf](https://github.com/metoppv/improver/files/1161842/time_windowing_accumulations.pdf)

Task 1:
To incorporate the time weighting used in the demo suite into IMPROVER. This is a triangular weighting function centred around the time of interest or a period of time. It can be applied either before or after neighbourhood processing. The probability of occurrence is the **mean** of all the time-weighted probabilities.
Task 2:
As for task 1, except that the probability of occurrence is the **maximum** of all the time-weighted probabilities.

Acceptance criteria:
 * Unit tests
 * Triangular time-based weighting support in `improver weighted-blending`
 * Acceptance test for above
 * [ NOT ESTIMATED ] Separate utility to find the maximum for each grid cell across a set of input files `improver stats --max`? Bash script using nco tools?
 * Acceptance test for above

-------------------------------------------------------------------------------------------------------------------

![time_weighting_function](https://user-images.githubusercontent.com/28624745/28531622-4e9a7428-708f-11e7-938d-72bdc341857c.png)

**Comment by gavinevans** [comment]
The core functionality of a triangular weighting function is developed in #202. This work wraps that functionality to calculate "Probability of an occurrence at a time" and "Probability of an occurrence sometime within a time window or around a time". For the CLI, triangular weighting function will provide an alternative to the existing `BasicWeightedAverage` plugin.

**Comment by fionaRust** [comment]
Part one in PR #248

**Comment by fionaRust** [comment]
2nd PR: Refactoring ready for next part: PR #253

**Comment by fionaRust** [comment]
Final PR: #254

**Note:**
This meets the acceptance criteria on the ticket, but does not cover everything in Nigel's attached pdf. Most of the cases could be provided the right data in in the cube that is passed into the plugin created for this ticket. In order to process all the cases in Nigel's pdf we will probably need a pre-processing step to get the data in the right format, especially for other time periods like 3-hourly.

**Comment by fionaRust** [comment]
Slide in the usual place.

**Comment by fionaRust** [comment]
@TomekTrzeciak also had some idea's for future improvements:
* Ignoring points at the end, for the case where time data is chunked up, and only part of the forecast is in one cube.
* Possible speed ups - maybe using numpy convolution functions.

**Comment by gavinevans** [comment]
This has now been completed.
