### ISSUE TITLE
Errors from unit-tests using conda-forge environment with pandas 2.0.0

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#1896]
Automated tests have started failing since the `conda-forge` environment started picking up [Pandas version 2.0.0 (released 3rd April 2023)](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html). This major release has removed some deprecated functionality and requires fixing.

An example of the failures is here: https://github.com/MoseleyS/improver/actions/runs/4730944769/jobs/8395284604

Of the three failures, two are easy to fix (replace `df.append()` with `df.concat()`), the third is not as the new version appears to have identified an out-of-range index which it then is unable to `df.drop()`.

Acceptance criteria:
 * All tests pass in all environments

**Comment by cpelley** [comment]
I would suggest pinning pandas right now and creating a new issue on supporting pandas 2.0

**Comment by gavinevans** [comment]
improver PR: https://github.com/metoppv/improver/pull/1899
