### ISSUE TITLE
Audit current GPP outputs for use in IMPROVER

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#193]
As the product owner I want the best use to be made of the existing GPP functionality in a time-frame that can deliver the Minimum Viable Product and give the best products within a probabilistic framework.

Related issues: #I, #J

Stage 1:
Examine precipitation type diagnostics and decide for each:
Is it required - how does it fit in with existing customer needs?
How well does it work?
When is it needed?
How easy is it to incorporate?
Is there an alternative?
Is there a further discussion or workshop needed?
Can it be done in the visualisation project?

Acceptance criteria:
 * Include the views of several people - particularly the experts in this area (which may also be outside the IMPROVER team). 
 * Document that answers the questions above (and flags those that are not easy to answer).

**Comment by fionaRust** [comment]
Closing as we will no longer be doing this in this form (and it is an internal ticket).
