### ISSUE TITLE
A plugin to calculate vertical wet-bulb temperature integrals

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#195]
Part of Snow melt Epic #191

Pre-requisite: #194

As an IMPROVER developer, I need a plugin to calculate integrals over wet bulb temperature vertically downwards to provide information about the melting of precipitation.

This method is used in the current UKPP system. For each slice between levels, we multiply the positive web-bulb temperature by the depth of the layer, then each layer contains the sum of positive values above that layer. The resulting units are Kelvin metres.

An example of this being done can be found in the Fortran code of the UKPP system. Look in precip/precip_type.f90 at lines 898-916 (direct link in Jira ticket), which includes examples that handle the transition across the wet-bulb freezing level.

Acceptance criteria:
* Write a plugin to calculate wet bulb temperature integrals from ~2000m above orography down to each layer.
* Use model height levels.
* Add suitable tests.

**Comment by MoseleyS** [comment]
# Calculating the positive wet-bulb integral.
For each 1D vetical profile, we want the amount of melting taking place. So for each slice between levels, we multiply the positive web-bulb temperature by the depth of the layer, then each layer contains the sum of positive values above that layer. The resulting units are Kelvin metres. An example of this being done can be found in the Fortran code of the UKPP system. Look in `precip/precip_type.f90` at lines 898-916 (direct link in Jira ticket), which includes examples that handle the transition across the wet-bulb freezing level.
The resulting data will be used to derive a slice from the vertical axis where the wet-bulb integral is at a certain value, yielding a height above sea level.

**Comment by bayliffe** [comment]
Complete.
