### ISSUE TITLE
Speed up square neighbourhooding

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#198]
As an Improver user I want square-neighbourhooding to be a lot faster, particularly when using larger neighbourhoods.

The current bottleneck is the treatment of edge cells that are calculated individually, rather than by the vectorised scheme. This can be resolved by padding the initial grid such that the vectorised scheme can be applied to all cells; see comment https://github.com/metoppv/improver/issues/2#issuecomment-315770066

Acceptance criteria:
 * Use information above to ensure domain edge cells are calculated in the same way as other cells.
 * Check that results calculated by the new method and old method are the same.
 * Add/amend unit tests.

**Comment by gavinevans** [comment]
Slide added.
