### ISSUE TITLE
Neighbourhood processing: handle masked arrays

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#2]
As a scientist, I want the SquareNeighbourhood processing to handle masked arrays so that I can perform orographic neighbourhooding.

A document outlining an example of the expected process is attached.
[Masked_Neighbourhooding.pdf](https://github.com/metoppv/improver/files/1145552/Masked_Neighbourhooding.pdf)

Acceptance criteria:
 * Current plugin updated to handle masked data as outlined in the attached document.
 * Acceptance tests updated with masked example.

**Comment by meabhnicguidhir** [comment]
**Notes**
* I have assumed that the masking of the data occurs at an earlier stage ie: the neighbourhood processing CLI is reading a file containing already masked data and passing this into the `SquareNeighbourhood` class.

* For the new bats test, the landmask ancillary mask is applied to the `basic-square` test data to use as input data.

* If the input is masked, the neighbourhood has to be calculated for both the mask and the data*mask. This effectively doubles the processing time and accentuates the existing issues with neighbourhood processing efficiency.

**Comment by bayliffe** [comment]
Sounds like we definitely need to improve our algorithm to handle the edges, rather than doing it cell by cell. I'll make sure this is somewhere in the pipeline.

**Comment by meabhnicguidhir** [comment]
Notes re NaN data in arrays:
* A more recent version of numpy (1.12.0) will contain `numpy.nancumsum' which will allow the `cumulate_array` method to carry out sums and treat the nans as appropriate. Until this is available, we will set Nan values -> 0 ahead of carrying out sums and then remask after calculating the neighbourhood.

**Comment by meabhnicguidhir** [comment]
Regarding the edge cases, one possible solution would be to pad the iris cube before entering cumulate_array and chop off the unwanted edge parts after the neighbourhood has been calculated. I've played around with this a bit and it produces the same data array as the current method and is a lot faster: processing the same fields as above takes ~0.4 seconds (compared to previously where masked took 48s and non-masked took 23s).

**Comment by bayliffe** [comment]
Meabh has implemented all that's required for this ticket. It is likely to be revisited in #188.
