### ISSUE TITLE
Update unit test class names for PEP8 conformance

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#208]
As an IMPROVER developer I want unit test class naming to follow PEP8 so that our global code style is followed

Acceptance criteria:
 * Name unit test classes in CamelCaseLikeThis
 * Run unit tests and check they succeed

**Comment by fionaRust** [comment]
We are not using camel case for classes, we are following the style guide here: https://github.com/metoppv/improver/wiki/Code-Style-Guide#unit-test-structure

**Comment by fionaRust** [comment]
Partial PR: https://github.com/metoppv/improver/pull/228

**Comment by fionaRust** [comment]
Still to do:
- [ ] Check and fix spot data unit tests
- [ ] Fix unit tests for wind downscaling, hopefully this will be covered by  the other technical debt issues to fix wind downscaling unit tests.
- [ ] Change docstrings to '''First sentence'''' format

**Comment by bayliffe** [comment]
Actually merged PR #229 following some rebase shenanigans.
