### ISSUE TITLE
Utility to merge cubes

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#209]
As an IMPROVER developer I want a utility to merge cubes so that I don't have to reinvent it in many places

Related to #166 

Acceptance criteria:
 * Look at Gavin's concatenate cubes functionality
 * Write a function or adapt Gavin's to merge cubes in a generic way, wrapping Iris.
 * Use the function where cubes are currently merged
 * Make sure metadata is appropriately treated during merge (some may need to be removed or rewritten)
 * Handle cubes with realizations from archive and percentile cubes from percentile plugin.

**Comment by carolinejjones** [comment]
I anticipate that there may need to be changes to merge_cubes as we start using the code in anger but what they might be will only be established once we start using it. The current pull request #268 will hopefully give us a structure to build on.

**Comment by gavinevans** [comment]
A slide has been added.

**Comment by bayliffe** [comment]
Completed.
