### ISSUE TITLE
Utility to enforce coordinate order

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#237]
As an IMPROVER developer, I want a single utility that consolidates existing functionality that orders coordinates so that I can easily pass a cube into the utility and be confident that the resulting cube has coordinates in the correct order.

Related issues: #209, #166, #236  

Existing utilities:
* Investigate the `make_stat_coordinate_first` method in #236.
* Investigate the `ensure_dimension_is_the_zeroth_dimension` function within [ensemble_calibration_utilities.py ](https://github.com/metoppv/improver/blob/master/lib/improver/ensemble_calibration/ensemble_calibration_utilities.py)
* Investigate `check_cube_coordinates` method.

Things to consider:
* Order of preference for realization, percentiles, thresholds. Note that there can be both realizations and percentiles on a cube.
* Vertical coordinates: height, pressure.
* Time.
* Equal preference for projection_x_coordinate, longitude and grid_longitude.
* Equal preference for projection_y_coordinate, latitude and grid_latitude.

This utility will be extended in the future, as use cases emerge.

Acceptance criteria:
 * Make sure that the coordinate ordering follows the agreed temporary conventions for probabilistic data.
 * Identify use cases for the existing utilities and identify whether this use case can be served by a single utility or that there is a requirement for multiple utilities. 
 * Consolidate existing utilities, if possible.
 * Unit tests.

**Comment by gavinevans** [comment]
**Use case:**
In [circular_kernel.py](https://github.com/gavinevans/improver/blob/45edcef321d36435aba35a1ff80795023d0720ac/lib/improver/nbhood/circular_kernel.py#L369), there is a section of code that reorders the resulting cube. This could be factored out and potentially generalised, as at the moment, it is hard-coded to use the `percentiles_over_neighbourhood` coordinate. There is some similar functionality existing in [check_cube_coordinates](https://github.com/metoppv/improver/blob/master/lib/improver/utilities/cube_checker.py#L59) for modifying coordinates within an output cube to match the coordinates within the input cube. However, the function suggested in this issue would order the coordinates within an output cube without the need for an input cube.

**Comment by bayliffe** [comment]
Work completed.
