### ISSUE TITLE
Full multi-model suite prototype

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#239]
As an IMPROVER suite developer I want to have a running trial suite so that I can start adding more and more scientific processing.

Work on multi-model suite, continuing from #153.

Acceptance criteria:
 * Extend work in #153 and refactor as necessary
 * All included diagnostics should be processed to percentiles or thresholds
 * Ensure gridded verification of all included diagnostics (may need to pull in extra verification obs tasks)
 * Include model-and-cycle-time-decoupled blending tasks in a separate include file (may want to run them completely separately in real time)
 * Include time lag blending
 * Optionally include site-specific verification if available and if there is time
 * Optionally include another source of model data if available and if there is time

**Comment by gavinevans** [comment]
This issue has been closed, as we'll manage this suite work elsewhere.
