### ISSUE TITLE
Wind downscaling: option to only output a particular height level

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#241]
As an IMPROVER developer I want wind downscaling to have the option to provide just a single height level that I need rather than all of them so that I can save disk space and make further processing simpler.

Acceptance criteria:
 * Add a CLI option to improver wind-downscaling to only output a particular height level e.g. the 10 metre height level
 * Add plugin functionality in wind_downscaling.py to extract a particular level (or set of levels) (or this could be done at the CLI level?).
 * Add CLI and unit tests
 * Also test invalid choice of level (e.g. one that is not provided - 5.567 metres, etc)
 * If an invalid choice of level is made, indicate the nearest available level which could be chosen.

**Comment by bayliffe** [comment]
Completed.
