### ISSUE TITLE
Move find_required_lead_times to be a top-level utility

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#245]
As a IMPROVER developer, I want to be able make use of functionality to determine the lead times within a cube so that I can apply different algorithms at different lead times.

The find_required_lead_times method in [nbhood.py](https://github.com/metoppv/improver/blob/master/lib/improver/nbhood/nbhood.py) is generic functionality, which should be moved to be a top-level utility.

Acceptance criteria:
 * Ensure neighbourhood processing works correctly after moving the method.
 * Move unit tests.

**Comment by bayliffe** [comment]
Completed.
