### ISSUE TITLE
Reduce warnings in `improver tests` output

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#249]
As an IMPROVER developer, I want fewer non-problem warnings in my test output so that I don't miss anything important. This ticket primarily covers unit tests and acceptance tests.

Acceptance criteria:
 * Investigate warnings and find out if they are justified (likely not)
 * Reduce number of warnings in `improver tests` output
 * Determine if there is a sensible way to ignore specific iris warnings that we do not wish to see.

**Comment by bayliffe** [comment]
Completed.
