### ISSUE TITLE
Wind downscaling: temporarily clip highest wind

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#251]
As an IMPROVER developer I want the maximum wind clipped to a maximum realistic value so that my ECC doesn't fall over!

The wind downscaling, given our input ancillaries (which may be at fault), can produce excessively high winds where large source/target orography differences are found. These need to be clipped at, say, 50 ms-1 as a temporary measure.

Acceptance criteria:
 * Add an option to the wind downscaling CLI to limit the maximum wind speed output (e.g. `--clip-max`)
 * Use this option to clip the wind downscaling output cube within the CLI code
 * Note that we will be removing this option shortly
 * Test it, but no need for a CLI test

**Comment by bayliffe** [comment]
No longer required. Closed.
