### ISSUE TITLE
Neighbourhood gust diagnosis

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#256]
As the product owner I want IMPROVER to have the capability to choose the most appropriate wind value to use for gust forecasting based on a neighbourhood comparison of the gust diagnostic and the 10m wind outputs

This will involve the following steps for each realization:
1. Extract relevant percentiles from the gust diagnostic (which will have either been read in from level 1 or computed within IMPROVER) over a square neighbourhood (e.g. 40x40km). Important percentiles are: 50th, 95th, 99th and maximum.
2. Extract relevant percentiles from the 10m wind speed (which will have been read in from level 1 and adjusted) over the same square neighbourhood. Important percentiles are 95th, 99th and maximum.
3. To determine a typical gust compare percentiles and find the maximum. 
The typical gust is MAX(gust(50th), Speed10m(95th) 
An extreme gust is MAX(gust(95th), Speed(max))   or could use combinations including gust(99th) or speed(99th) (Choose one for testing, but code needs to enable selection of a different percentile value). 
4. Write out the most appropriate typical gust and most appropriate severe gust at every grid square based on the comparisons in step 3.

Extension to this processing are:
1. To use orography-banded neighbourhoods 
2. To incorporate the convective precipitation diagnosis

Related issues: #I, #J

See context here: 
[WindGustChallenge_v2.pdf](https://github.com/metoppv/improver/files/1244828/WindGustChallenge_v2.pdf)

Acceptance criteria:
 * Write plugin and CLI. 
 * Put the processing steps listed above together in a sensible way.
 * Visualise example output to ensure that the output looks sensible.
 * Add Unit and CLI tests
 * Add sensible metadata
 * Output cube is of typical wind/gust values. 
 * Percentile as an argument to allow selection from CLI.

**Comment by fionaRust** [comment]
As part of PR #305 @gavinevans noticed that there was an inconsistency between when we are raising ValueErrors and TypeErrors when we check that the input is a cube. This is fixed in PR: #309

**Comment by fionaRust** [comment]
PRs merged and issue closed on JIRA
