### ISSUE TITLE
Modify the threshold plugin to allow specification of fuzziness as lower and upper bounds

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#263]
As an Improver scientist, I want to be able to specify fuzzy thresholds that are asymmetric or spanning zero so that it can be sensibly used on fields of data that span zero, such as the convection diagnostic "lifted index".

The threshold plugin should retain the ability to specify fuzziness as a factor relating to the threshold.
I envisage also being able to specify in the plugin a lower-bound, below which the function returns zero; a threshold, at which the function returns 0.5 and an upper-bound, above which the function returns one. The function will return a linear value between these three points.

Acceptance criteria:
 * Plugin continues to return the same results for fuzzy factor thresholds.
 * Plugin can also accept lower and upper fuzziness bounds (plugin should fail if factor is also supplied as this would be ambiguous).
 * New unit and CLI tests.
 * CLI modified to allow these new arguments to be applied.
 * Make sure that any existing functionality e.g. for calculating linear weights, is used as appropriate.

**Comment by fionaRust** [comment]
As part of this ticket we should make extra care to check the docstrings describing the  fuzzy factors. At the moment there are mistakes in the docstrings for the factor we are using, which is described as a percentage.

**Comment by bayliffe** [comment]
Complete.
