### ISSUE TITLE
Scope porting to Python 3

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#265]
As an IMPROVER developer I want to know how difficult it would be to port IMPROVER to Python 3 so that I can plan migration timescales.

Acceptance criteria:
 * Use `2to3` tool on improver code 
 * Alter Travis config in a branch to use Python 3 and run tests
 * Investigate failures and fix if trivial to do so
 * Report on amount of time estimated to port to Python 3
 * Recommend what we could do to make sure future development can be easily ported to Python3

**Comment by gavinevans** [comment]
Ported to Python 3 in #558.
