### ISSUE TITLE
Add CLI for extracting percentiles from probabilities using ECC

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#278]
As a IMPROVER developer, I want to modify the percentile CLI to support the conversion of probabilities to percentiles using ECC so that I can generate percentile output.

Related issues:  #54 

The plugins to convert from probabilities to percentiles already exists. This issue just adds a call to this plugin from the improver-percentile CLI when it is provided with cube of probability. The plugin interface must be modified to accept a pre-defined list of percentiles, as well as providing the option to create a list of percentiles, if these aren't provided.

Acceptance criteria:
 * Need the ability to extract a single percentile and a list of percentiles.
 * Retain support for supplying the number of percentiles to the plugin.
 * The CLI will only support providing the plugin with a list of percentiles, where there may be a single percentile in the list, rather than the number of percentiles.
 * CLI tests.

**Comment by bayliffe** [comment]
Completed.
