### ISSUE TITLE
Migrate functionality for merging cubes from suite to IMPROVER

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#284]
As IMPROVER developers we need to improve the merge_cubes utility to handle situations that have been identified during the implementation of grid blending and move untested suite code into suitable IMPROVER plugins and CLIs, so that the suite is easier to maintain.

Implement the changes to plugins and utilities suggested in IMPRO-429.

INFO:

We have created patch scripts within our suites to aid with cycle and grid blending. IMPRO-429 will provide a strategy for migrating this code into IMPROVER. We should move the code according to this strategy and test the suite with the migrated code.

Writing CLIs and updating the suite will be covered by IMPRO-345 / IMPRO-857 and IMPRO-691
Acceptance criteria:
* Implement the plugins to cover the code IMPRO-429 suggested should be moved into IMPROVER.
 * Update confluence documentation regarding use of model_id coordinate in blended metadata
 * Acceptance criteria from IMPRO-585 (see comments below)

Description:
Main changes for this ticket are to the cube manipulation and metadata utilities, and to weights.py.

**Comment by carolinejjones** [comment]
As part of #366 merge_cubes was amended to deal with unmatched cell methods. Currently it just removes mismatching cell methods so it may need revisiting if creating new metadata may be more appropriate.

**Comment by fionaRust** [comment]
The scope of this ticket has now changed to be an implement ticket and any other information has been moved to IMPRO-429
