### ISSUE TITLE
Find the maximum and minimum values in a square neighbourhood

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#287]
As the Product Owner I want IMPROVER to have the capability to compute the maximum and minimum values in a square neighbourhood around every grid square and be built into the capability to use a masked neighbourhood. 

This will be useful for many applications. To start with it will provide an alternative to using percentiles for the wind gust approach if necessary.

Related issues: #188 

Note that the 4-point neighbourhood processing approach for the mean/expected value is not applicable.

This user story only requires the maximum and minimum values. It is also necessary to calculate the mean value. However, this is already computed when computing the fraction/probability in a square neighbourhood. 

Acceptance criteria:
 * Unit test
 * CLI
 * Visual inspection

**Comment by gavinevans** [comment]
The case of maximum values within a square neighbourhood may be satisfied by this [maximum_within_vicinity](https://github.com/metoppv/improver/blob/master/lib/improver/utilities/spatial.py#L307) method.

**Comment by fionaRust** [comment]
Have the functionality to do maximum in square neighbourhood. Don't have a use case for minimum so closing.
