### ISSUE TITLE
Investigate weather symbols decision tree

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#289]
As an IMPROVER developer I need to develop a decision tree to enable me to implement weather symbols.

* Look as current SSPS system/documentation to get weather symbol numbers, and to assess current implementation. 
* Use list of L3 inputs to design tree for various symbols.
* Should include basic sun/rain symbols for now.
* Decide and document initial probability thresholds for making decisions.
* Precipitation scenarios require thought! Convective/dynamic discrimination, ensemble precip distribution vs showery distribution degeneracy.

Acceptance criteria:
 * Reviewed by Nigel Roberts, Simon Jackson and Paul Abernethy
 * Spend no more than 13 working days, including reviews
 * Document whole decision tree, and make available on Confluence

**Comment by fionaRust** [comment]
Closed on Jira - internal only.
