### ISSUE TITLE
Plugin to calculate wet bulb temperatures.

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#290]
As an IMPROVER developer, I want the ability to calculate wet-bulb temperatures from pressure, temperature and relative humidity data.

Epic #191 
Related issues: #194 #291

The method should follow that of the UM. A Newton iterator will be used to find the wet bulb temperature based on the relevant psychromatic calculations, with saturated vapour pressure a requirement in this process. The saturated vapour pressure may be calculated directly or obtained from a lookup table; if the latter, the code used to produce the table must be included within IMPROVER.

Acceptance criteria:
 * Create a plugin to use the Goff-Gratch method to calculate saturated vapour pressures.
* Use this plugin to create a lookup table of saturated vapour pressure data for use by IMPROVER.
* Create a means of querying the look up table, and implement a means of linearly interpolating using this data.
* Implement a plugin to calculate wet bulb temperatures from pressure, temperature, and relative humidity data (3 cubes in, 1 cube out).
* Note the timings of using the Goff-Gratch method directly to calculate SVPs versus using the table and interpolating.
* Choose an approach based on this timing information.
* Compare the output of the plugin with the UM to ensure the results are correct and provide details of this comparison.
* Create a CLI to call the wet bulb temperature plugin.

**Comment by fionaRust** [comment]
Pull Request: #307 307

**Comment by fionaRust** [comment]
Closed on Jira, all PRs closed and everything's done.
