### ISSUE TITLE
Adapt wet-bulb temperature plugin to use vertical pressure level information.

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#291]
As an IMPROVER developer, I want to be able to use the web-bulb temperature plugin created in #290 (IMPRO-337)  to calculate wet bulb temperatures for multi-level data stored on pressure levels.

Epic #191 
Related issues: #194 
Prerequisite:  #290 

Points to note:
- Modify the wet bulb temperature plugin and/or CLI to work with temperature and relative humidity data that is provided on pressure levels, such that no separate pressure diagnostic cube is necessary, rather the pressure information can be obtained from the vertical coordinate information of the other two cubes.
- The plugin must continue to support multi-level data where the vertical coordinate is height. 

Acceptance criteria:
 * Modify the plugin and/or CLI to calculate wet-bulb temperatures for multi-pressure level cubes without the need for a separate pressure cube.
 * Continue to support vertical height coordinates.
 * Extend test coverage as appropriate.

**Comment by fionaRust** [comment]
Won't need this any time soon so closing.
