### ISSUE TITLE
Implement weather symbol decision tree

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#292]
As an IMPROVER developer, I want to implement the weather symbol decision tree, created in #289, so that a sensible weather symbol can be created as an output from the IMPROVER processing chain.

Related issues: #289 

Create a plugin that implements the weather symbol decision tree. Ensure all the required weather symbols can actually be produced using the decision tree.

Acceptance criteria:
 * Implement the weather symbol decision tree.
 * Ensure that the plugin can cope with either spot data or gridded data.
 * Sensible unit tests that capture the scenarios that are possible based on the decision tree.

**Comment by bayliffe** [comment]
Completed.
