### ISSUE TITLE
Implement a utility to distinguish between day and night

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#293]
As an IMPROVER developer, I want to be able to easily determine whether it is day or night so that different processing can be applied depending upon whether it is day or night.

Related issues: #292 

Develop a plugin that can take in a cube with a time coordinate with time in UTC and convert this into a binary day/night grid of output data. 

Calculation would follow:
- Find the sign of the sine of the solar elevation angle. If it's greater than or equal to zero, it's day, otherwise it's night.
- To find solar elevation angle need to know latitude-longitude of the location, the time of day and the day of year.

As we are dealing with gridded data, calculating whether it is day or night at each point might not be the best approach, as it could be quite slow. A vectorised approach may therefore be preferable, see daynight.py for an example.

Acceptance criteria:
 * Take in a cube with UTC time and convert to day/night.
 * Record any assumptions that you've made for determining that it is night time.
 * Unit tests

**Comment by bayliffe** [comment]
Completed.
