### ISSUE TITLE
Decide on and implement a metadata convention for weather symbols

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#294]
As an IMPROVER developer, I want to be able to store weather symbols within a netCDF file in a consistent way so that they can be read in and interpreted correctly.

Related issues: #292 

This issue should : 
- Document the existing metadata convention using the existing weather symbol relationships, for example, 0 = Clear night, 1 = Sunny day, 2 = Partly cloudy night.
- Create a utility that applies this convention. This utility will be used for creating a cube containing weather symbol information, such that the values that have been attributed to a particular site or grid point, can be cross-referenced to the meaning of the weather symbol easily. 

Acceptance criteria:
 * Document the existing metadata convention for weather symbol codes and their description in Confluence.
 * Create a utility that can be used for creating a cube and applying the metadata convention.
 * **New criteria: Generate sample data for verification, over several cycles.**

**Comment by fionaRust** [comment]
There were two PRs for this change: #302  & #306

**Comment by fionaRust** [comment]
PR merged and closed on Jira
