### ISSUE TITLE
Cycle and model blending output metadata

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#296]
As an IMPROVER developer I need the metadata on cubes that have been blended, either across cycles or models, to be sensible and useful for later processing steps. This can best be described with some examples:

1. I need the forecast reference time on a cycle blended or model blended cube to be reflect the cycle time of the blending process: 01Z, 02Z, 03Z, and 04Z UKVx cycles blended into a cube with a FRT of 04Z, and modify forecast period relative to new forecast reference time.
2. I need to remove redundant model identifiers from model blended cubes, e.g. model_id which is a combination of various integers and model_realization.
3. Deal with any scalar coordinate bounds that look odd.

(Elsewhere: I need to do something more sensible with realizations, ideally we would implement the source_realizations metadata discussed in the temporary conventions. Alternatively the realizations should simply be removed, as by this point they have little value.)

Related issues: #284, IMPRO-304 (patch scripts).

Acceptance criteria:
 * Rationalise metadata resulting from blending cubes over cycles and models.
 * Update any CLI acceptance tests that may be affected.
 * Extend unit test coverage.
 * Document resulting metadata and its meaning.
 * Record any potential issues that are outstanding for merging.

**Comment by fionaRust** [comment]
We will need to make sure that this  metadata (especially the forecast lead times) make sense from the verification point of view.

**Comment by wxtim** [comment]
Current unit tests do not try to blend across forecast reference times (frt).
I've hacked it such that they do (replacing the time with an frt coord)
The hack is visible at https://github.com/metoppv/improver/compare/master...wxtim:IMP-347-Metadata_on_blending
The result is that we get a combined coord where the upper bound corresponds to the most recent frt

**Comment by bayliffe** [comment]
Completed.
