### ISSUE TITLE
Neighbourhood processing: handle domain edge effects

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#3]
As an IMPROVER scientist, I want the neighbourhood processing to produce the same values around a point regardless of whether the point is near the edge of the domain or not, so that the scientific integrity of the processing is higher.

Acceptance criteria:
 * points near or on the edges and corners of the domain should not produce any different result values after neighbourhood processing.
 * may require linear extrapolation creation of a halo
 * unit tests that note this edge behaviour should be altered to reflect this

**Comment by bayliffe** [comment]
Work completed as part of other tickets.
