### ISSUE TITLE
Slicing in realization collapse

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#300]
As an IMPROVER user I need the realization collapse method, when applied to cubes with many thresholds, to avoid memory errors by performing the operation using threshold slices.

Examples of this can be found elsewhere in the code, including in nbhood.

Acceptance criteria:
 * Ensure weighted-blending slices multi-threshold data.
 * Update or extend tests as appropriate.

**Comment by fionaRust** [comment]
Closing as PR: #301 has been merged
