### ISSUE TITLE
Load data wrapper function(s) in Improver

### ISSUE THREAD

**Issue by fionaRust** [metoppv/improver#31]
As a developer I want to be able to load standard netCDF input with Iris using a central wrapper or wrappers so that functionality is kept in common.

This wrapper is seen as a first step and is not required to greatly extend the functionality of iris.load. The currently expected additional features are:
- Ensure a statistical coordinate if present is the first in the cube.
- Ensure y and x coordinates are the last in the cube.

Related issues: StaGE DD-820, DD-746, #237 

Acceptance criteria:
 * Create a lightweight wrapper function that sensibly wraps iris.load
 * Preserve ability to pass kwards to iris.load
 * Replace the load call in all CLIs and ensure they work as expected.
 * Check that the probabilistic dimension is first and the y and x dimensions are last - warn otherwise (Links with #237)
 * CLI acceptance tests should pass

# Past discussion
*Extra info*

**Needs more input and discussion!**
Gavin @gavinevans has made a start to this work although this work was not refined before he started it, so we have not agreed an approach. Gavin's code is based on what we have implemented in StaGE, which is a good starting point but probably needs more work. There are choices about whether constraints are used upon load, or afterwards using extract. We also may need to load data from different places and we need to think about how this will work.

**Within StaGE, the Load plugin is currently set up to constrain based:**
Stash code
lbproc
The period of the time averaging from the cell method
Forecast period
Pressure
This constraints are applied on load.
**For IMPROVER,** there are a number of additional constraints that will be desirable, as observed in DD-746 - Creation of Ensemble Calibration plugins. These include:
Hour of day
Realization
Height
Time range for constraining over multiple cycletimes
Is the aim to have a single flexible Load plugin, which will support  constraining upon load, or will constraining after load be appropriate? (See the RestrictTrainingPeriod plugin for a rather complicated example of constraining after loading.)

**Comment by fionaRust** [comment]
@benfitzpatrick What is the requirement for this? How much of this should be done?

**Comment by bayliffe** [comment]
Can we please ensure that 32 bit ints that are going to be manipulated are converted to in64s during load. I am primarily thinking about int32 datetimes that could cause issues if they are not increased.

**Comment by bayliffe** [comment]
Completed.
