### ISSUE TITLE
Investigate areas to refactor in IMPROVER code

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#317]
As an IMPROVER developer I want some main areas of technical debt identified in the IMPROVER codebase so that I can plan work to address them.

Acceptance criteria:
- Look at areas of duplicate code across the whole codebase, proposing a few big easy things to fix.
- Look at ways of reorganising existing code
- Look at whether CLIs need rejigging for clarity, following the https://en.wikipedia.org/wiki/Unix_philosophy
- Recommend approaches after discussions with authors of the code to be modified and propose tickets
- Spend no more than 5 days on this

**Comment by gavinevans** [comment]
Closing this issue, although further discussion is required to agree the recommended approaches.
