### ISSUE TITLE
CLI for vicinity plugin

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#319]
As an IMPROVER developer, I need a CLI for the vicinity plugin (#145) so that this can be added into processing chains that provide data to the weather symbols decision tree (which uses precipitation within vicinity fields). 

NB Unweighted mode in vicinity.py should be changed to weighted_mode as part of this work, that will make it consistent with the kernels.

Related issues: #145, #292 

CLI Input is (see vicinity.py doc string for more)
distance, neighbourhood_method, radii, lead_times (None if single radius used for radii), weighted_mode (Needs a default if unset).

Plus the cube to take as input.

Acceptance criteria:
 * Write CLI for vicinity plugin.
 * Add suitable acceptance tests.

**Comment by carolinejjones** [comment]
Created pull request #334 for this issue.

**Comment by bayliffe** [comment]
Completed.
