### ISSUE TITLE
Investigate and implement virtual board

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#32]
As an IMPROVER developer I want a virtual board with columns for various states of progress for issues so that I can have the same virtual experience as in the physical board.

Acceptance criteria:
 * Investigate waffle.io GitHub extension and demo informally to team members
 * If team agrees, implement it for IMPROVER

**Comment by benfitzpatrick** [comment]
We are using the GitHub project board - it is agreed to be OK, at least for now

**Comment by arh89** [comment]
@bayliffe suggested that https://www.zenhub.com/ might be more suited to our workflow, and could possibly be used to reduce duplicated items on the project board (when there are pending PRs in addition to the original ticket.)

ZenHub also seems to have story point estimation, which might also reduce the number of labels that we have.
