### ISSUE TITLE
Write first draft archive retrieval utility

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#33]
As an IMPROVER scientist I want a utility to handle fetching of Level 1 data from the in-house archive so that I can get Level 1 data in a nice form without coding my own stuff.

Main story: #101.

Acceptance criteria:
 * Write standalone utility with configurable output directory(ies) to place Level 1 data in a standard directory structure
 * Agree final form of Level 1 data with Ben F (suite directory structure for everything else to work from)
 * Fetch data from in-house archive

**Comment by benfitzpatrick** [comment]
Inputs:
 * destination directory - should be `share/cycle/CYCLE_POINT/DIAG_GROUP/level_1/BATCH/`, e.g. `share/cycle/20170530T0300Z/precip/level_1/PT12H/`
 * cycle point
 * diagnostic group (e.g. `precip`)
 * forecast lead time globs (e.g. `PT0010H* PT0011H* PT0012H*`)

Optional inputs:
 * diagnostic name (e.g. `rainfall_rate`)

**Comment by gavinevans** [comment]
@benfitzpatrick has confirmed that the suite aspect of this issue is not the focus of the review, with the focus being the script used to do the archive retrieval.

**Comment by gavinevans** [comment]
After speaking with @TomekTrzeciak , additional comments have been added to the `archive_retrieve` script to explain some of the more advanced bash syntax. This now seems to work for the intention that it was developed for.
