### ISSUE TITLE
Continuous snowfall level CLI

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#330]
As an IMPROVER developer I need a CLI to call the calculation of the continuous snow melting level. This will call the plugin to calculate wet bulb temperature integrals and the plugin to convert these into a continuous snow melting level. 

Related issues: IMPRO-173, IMPRO-372

Acceptance criteria:
 *  CLI that takes in temperature, pressure and relative humidity on height levels and an orography field.
 * Returns a single cube to a file of snow melting level.
 * Add acceptance tests.

**Comment by wxtim** [comment]
First draft created https://github.com/metoppv/improver/compare/master...wxtim:382_falling_snow_cli?expand=1

**Comment by bayliffe** [comment]
Completed.
