### ISSUE TITLE
Use pycodestyle instead of pep8 on Travis

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#332]
As an IMPROVER developer I want to migrate to pycodestyle to avoid deprecation problems with pep8.

Acceptance criteria:
 * migrate to pycodestyle in the Travis setup and improver-tests
 * preserve compatibility with sites like ours which don't have pycodestyle
 * alter any files that fail with the newer pycodestyle

**Comment by bayliffe** [comment]
Completed.
