### ISSUE TITLE
improver CLI help: fewer references to cube

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#348]
As a third-party developer, I want IMPROVER CLI documentation to be more NetCDF-general rather than Iris-specific, so that I can easily understand the commands.

It is fine to refer to cubes inside the source code, but users of the utilities may not know (or need to know) what they are. In the CLI help, it would be good to be more aligned with general terminology.

Acceptance criteria:
 * In the `improver-` commands in the bin directory, rephrase mentions of 'cube' to files or diagnostics or phenomena as appropriate
 * Update CLI acceptance tests

**Comment by bayliffe** [comment]
Completed.
