### ISSUE TITLE
Weighted blending plugin

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#35]
As a scientist I want a weighted blending plugin so that I can later experiment with time lagging and windowing.

Acceptance criteria:
 * Create a weighted blending plugin
 * The plug-in should be 'model agnostic' and be able to blend ensemble members from the same model and validity time, different runs of the same model (different validity times), or data from different models with overlapping validity times.  
 * The output is on the same grid as the input fields (which are assumed to be on a common grid)
 * Different weights can be used against the different inputs - these will be supplied by #39 
 * Consult with Tomek for his approach
 * Unit tests

**Comment by benfitzpatrick** [comment]
Assigned Simon (but meaning Caroline)

**Comment by fionaRust** [comment]
@carolinejjones  @simonjackson900 could we have a bit more detail in the acceptance criteria to define what the requirements are for this plugin. This should help people reviewing the code to check the right functionality has been implemented. ( @bayliffe @gavinevans)

**Comment by carolinejjones** [comment]
It would also have helped to have some more detail in the acceptance criteria when writing the plugin but I can hardly write my own acceptance criteria retrospectively. @simonjackson900 @benfitzpatrick would you like to add more details on what you are expecting from this plugin. If you can get it to match what I have done that would be most helpful ( @fionaRust @gavinevans @bayliffe )

**Comment by simonjackson900** [comment]
I've added to the acceptance criteria at the top of the ticket - is that enough to be going on with?
Shall try to do better next time!

( @fionaRust @gavinevans @bayliffe @benfitzpatrick )

**Comment by benfitzpatrick** [comment]
Closed by #60.
