### ISSUE TITLE
Neighbourhood processing: Configurable radius by lead times

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#36]
As an IMPROVER developer I want the command line interface for basic neighbourhood processing to have configurable lead-time-dependent kernel radii so that I can later experiment with increasing radius with lead times.

Acceptance criteria:
 * Start after #5 is closed
 * Specify an optional lead time radius option to `bin/improver-nbhood`
 * This option should somehow refer to a configuration file which matching lead times vs specific radii (e.g. a flat 2 column text file)
 * Lead times not mentioned in the configuration file should be derived by linear interpolation
 * Write a CLI acceptance test (consult Ben F for guidelines)

**Comment by gavinevans** [comment]
Discussed the usage of a lookup file, as opposed to the current implementation in #52, which passes in the radii and lead times as arguments with @benfitzpatrick and Nigel Roberts. The current implementation involving passing arguments seems fine with a future neighbourhood processing ticket required to deal with adding functionality for ensemble members.

**Comment by gavinevans** [comment]
A follow-on issue (#59) focuses on the development of acceptance tests for the neighbourhood processing.

**Comment by fionaRust** [comment]
Pull Request merged (#54) and was in May demo.
