### ISSUE TITLE
Metadata checks in the CLIs

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#363]
As an IMPROVER developer I want most CLIs to check their input cube metadata so that I can be confident this will be treated sensibly by the plugin and not cause errors or problems downstream. 

Acceptance criteria:
 * For each CLI, check that the input cube has expected metadata for the plugin, and fail if this is not appropriate.

**Comment by bayliffe** [comment]
To be replaced by the ticket to which it was split.
