### ISSUE TITLE
Custom aggregator for topographic zone weighted collapse

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#365]
As product owner I want the functionality to blend across topography bands after neighbourhooding, in order to account for points which are close to the edges of the topography bands. Two preliminary steps will be completed in #283 (IMPRO-329).

Related issues: #283 (IMPRO-329)
Pre-requisite: IMPRO-379,  #283 (IMPRO-329)

The remaining step is to write our own custom aggregator that collapses a topographic band coordinate using provided weights, adjusting these weights if a NaN is found in the neighbourhooded data. This ensures that a lack of probability contributions from a neighbouring but relevant topographic band does not result in artificially lowered probabilities of occurrence at a site; e.g. a hill top close to the top of the topographic zone that contains it.

Acceptance criteria:
- Write an aggregator that collapses a topographic band using custom weights.
- Aggregator must re-adjust the weights when a topographic zone contains a NaN, so that the topographic zone containing a non-NaN value has a weight of 1 for the grid point.
- Unit tests
- CLI with acceptance tests.
- Record speed for discussion.
- Visual test on simple idealised field.
- Plot output, preferably within a shareable jupyter notebook.

**Comment by gavinevans** [comment]
Completed in #399 and #407.
