### ISSUE TITLE
Replace DimCoords with AuxCoords for integration

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#373]
As an IMPROVER scientist I want the bounds on the integrated coordinate to represent the range that has been integrated over so that the metadata for integrated coordinates is clear.

Replacing DimCoords with AuxCoords allows overlapping bounds to be supported.

Related issues: #290, https://github.com/metarelate/statistical-process/issues/11

Acceptance criteria:
 * Make the change so that integrated coordinates are AuxCoords.
 * Remove this TODO statement: https://github.com/metoppv/improver/blob/master/lib/improver/utilities/mathematical_operations.py#L163.
 * Update acceptance tests.

**Comment by fionaRust** [comment]
Don't have a use case for this so closing.
