### ISSUE TITLE
Document governance process (L-1) - first draft

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#38]
To be assigned to Bruce.

As a X I want Y so that Z

Related issues: #I, #J

Optional extra information text goes here

Acceptance criteria:
 * A
 * B
 * C

**Comment by fionaRust** [comment]
What's the status of this? I'm making it into a story so it's easier to flag up, but needs way more detail in the description.

**Comment by fionaRust** [comment]
@bjwheltor Can this be closed?

**Comment by bjwheltor** [comment]
Closed, as not specific to IMPROVER. Will be taken forward as part of the Solutions Architecture work, with any specific tickets under StaGE.
