### ISSUE TITLE
Develop Blending Weights function

### ISSUE THREAD

**Issue by simonjackson900** [metoppv/improver#39]
As a scientist I want a function that generates a set of blending weights so that the weighted blending plugin can use them

Related issues: #35 

Acceptance criteria:
 * Create a function that will generate a simple set of blending weights
 * Blending weights can be used by the blending plugin
 * Consult with Tomek for his approach
 * Unit tests

**Comment by benfitzpatrick** [comment]
Assigned Simon (but meaning Caroline)

**Comment by carolinejjones** [comment]
Closed by #70
