### ISSUE TITLE
Generic save wrapper

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#393]
As an IMPROVER developer I want a generic save wrapper so that I can centralise common saving options.

Related issues: #31, #374

Currently when Iris saves a netCDF file with a single cube, attributes associated with the variable are recorded as global attributes within the file. This may be undesirable, and potentially cause confusion when interpreting the netCDF file. To avoid this, the `local_keys` keyword argument available within [iris.fileformats.netcdf.save](http://scitools.org.uk/iris/docs/latest/iris/iris/fileformats/netcdf.html#iris.fileformats.netcdf.save) can be used, so the ability to save variable attributes, in addition to global attributes.

Acceptance criteria:
 * Replace `iris.save` calls in the CLI with a central wrapper as was done for #31.
 * Add unit tests
 * Make sure all the attributes that we want to promote to be variable attributes are covered.
 * Document how we to add additional variable attributes in the future.

**Comment by bayliffe** [comment]
Work completed.
