### ISSUE TITLE
Chunk by x-y in generic save wrapper and compress

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#394]
As an IMPROVER developer I want my files chunked by 2D x-y/lat-long slice so that my read costs for common CLI operations are lower.

Follows on from #393, #31.

Acceptance criteria:
 * Using the generic save wrapper, add chunking by 2D x-y slice by default if the cube contains x and y (1 chunk == 1 lat-long slice in the cube)
 * Add unit tests for the chunk determination if possible
 * Acceptance tests should pass and re-chunk existing netCDF files
 * Report timings for acceptance tests (should generally improve)
 * Add at least one acceptance test using `ncdump -hs` to grep for chunking information
 * Add lossless NetCDF built in compression at lowest compression level

**Comment by LaurenceBeard** [comment]
addressed by #874
