### ISSUE TITLE
Review/assess/define Business Group requirements into Post Processing Requirements

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#40]
To be assigned to Bruce as well
As Business Group I want a final list of diagnostics that will be provided through StaGE so that I am confident that our requirements will be met.

Related issues: #41 

Business Group have a set of additional requirements for level 1 data. We want to rationalise this this, to make sure we can provide the requested diagnostics and we understand the requirements fully. We will need to work with Business group in an iterative process until we have a final list.

Acceptance criteria:
 * Produce a first set of agreed diagnostics out of those provided by business group
 * Get Business group approval
 * (Bruce to add more info?)

**Comment by fionaRust** [comment]
We have produced a spreadsheet detailing the agreed diagnostics from each model, and those we will not be providing. We will not provide diagnostics if there are no suitable level 0 input or they can be easily derived from other standard diagnostics. @benfitzpatrick Will have a look at the list and we will then pass it on to business group for initial feedback, along with a few questions asking for clarification.

**Comment by bjwheltor** [comment]
First the first response has been provided to the Business Group on their request to extend the level 1 data. This takes the form of an updated spreadsheet where the majority of the requested additional diagnostics have been assessed and either provisionally accepted as extensions to the list of level 1 diagnostics, rejected as they are either impossible to provide directly from the model or do not conform to the principles of the standard diagnostics - in the later case, an alternate is often proposed. The small set of diagnostics that have not yet been assessed are some fo the more specialist (e.g. Aviation-specific ones) the need more detailed consideration. A meeting scheduled for 18 May will discuss this initial response and how to proceed.

**Comment by fionaRust** [comment]
@bjwheltor can this be closed now?

**Comment by bjwheltor** [comment]
Covered as part of StaGE work, so IMPROVER issue can be closed.
