### ISSUE TITLE
Neighbourhood processing bugs

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#405]
As an IMPROVER developer, I want to be confident that the neighbourhood processing is producing the correct results.

A couple of issues have arisen following the investigation into #365 :

- For precipitation accumulation, negative numbers are being produced from neighbourhood processing.
- There are probabilities greater than 1.0 at the edges of the domain when using thresholded input data and a large neighbourhood.

Related issues: #365 and related jupyter notebooks

These bugs need to be fixed. They may be resulting from the same underlying bug, or they may be caused by different bugs.

Agree the fix that is to be implemented with your review buddy.

Acceptance criteria:
 * Identify the cause of the misbehaviour in neighbourhood processing.
 * Fix the misbehaviour.
 * Update unit tests, as required, and update acceptance data.
 * Remove the clipping from the nbhood-iterate-with-mask CLI and updata acceptance tests if need.

**Comment by bayliffe** [comment]
Completed.
