### ISSUE TITLE
Add code maintainability scores to pull requests

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#406]
As an IMPROVER developer I want code complexity / maintainability scores for my pull requests so that I can make the best judgements about code structure.

Acceptance criteria:
 * Explore third-party GitHub hooks that give a score on each pull request (not a tick/cross) based on code complexity or maintainability
 * Implement and demonstrate to the rest of the team
 * Time-boxed to ? days

**Comment by LaurenceBeard** [comment]
implemented with codacy and codecov
