### ISSUE TITLE
Ensure wildcard expansion occurs within shell, rather than within CLI

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#409]
As an IMPROVER developer, I would like the CLI acceptance tests for the improver-combine CLI to use shell expansion of the wildcards, rather than expand the wildcards within the CLI, because there is no need for the CLI to do this operation.

Related issues: #389, #400

An example of this exists in improver-combine e.g.

```python
input_filenames = []
for filename_globlist in args.input_filenames:
for filename in glob(filename_globlist):
input_filenames.append(filename) 
```

This handling can be removed and quotes can be removed from the wildcarded paths within the CLI acceptance tests, so that shell expansion is used.

Acceptance criteria:
* Modify improver-combine CLI to remove expansion of wildcarded paths.
* Update or add acceptance tests for this functionality.

**Comment by bayliffe** [comment]
Completed.
