### ISSUE TITLE
Update the form_of_difference attribute for metadata compliance

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#412]
As a IMPROVER developer, I want the non-CF standard metadata that we have added so far within IMPROVER to be namespaced (spp__form_of_difference) and updated to not involve modifying cell methods so that these variables can be linked to project-specific metadata definitions that will be hosted at http://reference.metoffice.gov.uk/statistical-process.

Related issues: #414 

Following the examples regarding the [difference calculation](https://github.com/metarelate/statistical-process/issues/7#issuecomment-344976905), the form_of_difference attribute should be updated, so that it does not modify the cell method, and instead a "with_respect_to" attribute is used to describe that, for example, a one grid point difference has been calculated along the projection_x_coordinate.

Acceptance criteria:
 * Update the metadata as advised in the [difference calculation](https://github.com/metarelate/statistical-process/issues/7#issuecomment-344976905) issue.
 * Update any relevant unit tests and acceptance tests. 
 * The resulting cube should not have a cell method associated with form_of_difference.

**Comment by bayliffe** [comment]
Work completed.
