### ISSUE TITLE
Prototype metadata cube saving

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#414]
As an IMPROVER developer, I want to be able to insert attributes that provide a link to a metadata description of the IMPROVER project specific metadata so that collaborators and users of the resulting files will be able to understand the meaning of the metadata.

Related issues: #412,  #393 

The existing load wrapper can be used in the prototype. 

Following the example in https://github.com/metarelate/statistical-process/issues/7#issuecomment-344976905, where a separate metadata cube is specified prior to saving all other cubes to a netCDF file. This metadata cube acts as a container for the references to the metadata registry. 

Note that when loaded in using Iris v1.13.0, the metadata cube will not appear as a separate cube, but rather the attributes will appear as attributes on all the other cubes in the file, see https://github.com/metarelate/statistical-process/issues/7#issuecomment-344976905 for an example. This behaviour should be checked and Mark Hedley consulted to check whether this behaviour will be retained with different versions of Iris, so this behaviour should be tested with Iris v1.13.0 and possibly more experimental Iris versions. 

Acceptance criteria:
 * Create this in a branch and agree with the team that this approach is sensible.
 * Modify the load wrapper, so that only the data cube is loaded, rather than the metadata container. 
 * Re-create acceptance results related to the "form of difference" attribute to prototype how this would work.
 * Do not recreate every single known good output acceptance test. This will be captured in a follow-on issue, if appropriate.
 * Talk through results with Mark Hedley.

**Comment by bayliffe** [comment]
Work completed.
