### ISSUE TITLE
Generate percentiles from a neighbourhood for a single percentile

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#415]
As an IMPROVER developer I want to be able to generate percentiles from a neighbourhood for a single percentile so that I can, for example, generate a wind gust diagnostic successfully, where I want to focus on processing a single percentile.

Related issues: #408

Currently, it is the case that when using the generate percentiles from a neighbourhood code ([GeneratePercentilesFromACircularNeighbourhood](https://github.com/metoppv/improver/blob/master/lib/improver/nbhood/circular_kernel.py#L218)) with a single percentile value there is a shape mismatch due to the promotion/demotion of what effectively becomes a scalar coordinate within pad_and_unpad_cube function. This needs to be fixed, so that the wind_gust_diagnostic processing chain can complete properly.

Acceptance criteria:
 * Fix the known bug.
 * Add unit tests and/or acceptance tests, so that this bug would be caught in future testing.

**Comment by bayliffe** [comment]
Completed.
