### ISSUE TITLE
Define fields (Spot Data and Neighborhood processing

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#42]
To be assigned to Nigel Roberts

As a X I want Y so that Z

Related issues: #I, #J

Optional extra information text goes here

Acceptance criteria:
 * A
 * B
 * C

**Comment by benfitzpatrick** [comment]
Assign to Sean but meaning Nigel

**Comment by fionaRust** [comment]
What's the status of this? I'm making it into a story so it's easier to flag up, but needs way more detail in the description.

**Comment by fionaRust** [comment]
Closed as we there is no description and no more work we want to do under this ticket.
