### ISSUE TITLE
Ancillary generation: land-sea mask and orographic bands

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#43]
As a developer I want access to ancillary datasets for the land-sea mask and the orography band masks for spot data and neighbourhood processing routines so that developers don't have to regenerate these fields each time they are required.

Related issues: 
This user story falls under the Epic: Ancillary Generation for Improver (#97)

Acceptance criteria:
 * Develop a flexible script(s) that can be called from the command line, in order to generate the required ancillary files
 * Develop plugins to generate the required ancillary with unit tests 
 * Generate the following ancillaries (initial list, subject to change):
1. Orography band masks
2. Land-Sea mask
(note: some ancillaries have been removed from this issue, see Epic #97 for other ancillaries)

**Comment by meabhnicguidhir** [comment]
A pull-request has been submitted for this user story here: #94.
This PR includes plugins and CLI scripts to generate ancillary land mask and topography band fields.

**Note that StaGE does not produce the necessary input ancillaries yet**

**Comment by meabhnicguidhir** [comment]
A slide has been prepared for the June demo.

**Comment by gavinevans** [comment]
@benfitzpatrick has confirmed that issues already exist within StaGE for producing land mask and orography for all standard grids.

**Comment by fionaRust** [comment]
* Merged pull request #94 
* Made sure Bruce and Nigel are aware of the status of ancillary generation.
* Slides available
