### ISSUE TITLE
improver CLI: centralised option parser 

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#433]
As an IMPROVER developer I want a centralised option parser so that I can reduce the amount of duplication in IMPROVER CLIs.

See e.g.  Rose (https://github.com/metomi/rose/blob/0215af/lib/python/rose/opt_parse.py, https://github.com/metomi/rose/blob/0215af/lib/python/rose/app_run.py#L456)

Acceptance criteria:
 * Centralise the option parsing by creating a central class that all CLIs use with predefined options and some common options across all of them (for now, leave common options as an empty list).
 * Show this works with at least one CLI. Updating other CLIs will be a follow-on user story.
 * If help text differs between same-name options, converge where possible.
 * Acceptance tests should pass

**Comment by bayliffe** [comment]
Completed.
