### ISSUE TITLE
Remove cell method customisation when blending

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#436]
As an IMPROVER developer, I want the netCDF files that I create to be CF-compliant so that when the files are shared with users, there is no non CF-compliant metadata

Currently within the blending calculation a bespoke cell method is added e.g. "weighted_mean" to indicate that a weighted mean has been applied. Within the CF standards, the cell methods are a protected variable, so we shouldn't be adding our own cell method. 

Adding any additional metadata is out of scope of this issue.

Acceptance criteria:
 * Remove the cell method customisation when blending.
 * Replace weighted_mean with "mean", which is CF-compliant.
 * Update unit tests and CLI tests.

**Comment by bayliffe** [comment]
Completed.
