### ISSUE TITLE
Chose cases for L1 data

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#44]
Assign to Nigel Roberts

As someone who wants to be able to see the impacts of the post processing on particular aspects of the weather, I would like some suitable events to use for evaluation.

Main story: #101.

Related issues: #I, #J

The cases should be recent enough to be available in the fieldsfile archive

Acceptance criteria:
 * Cases are agreed to be sensible
 * The data is available in MASS
 * C

List of initial IMPROVER case studies
Nigel Roberts	31/05/17
Below is an initial list of cases to use to test IMPROVER. They are all from 2017 so that there will (or should be) suitable data stored in the MASS fieldsfile archive.
Forecast will be required for analysis times from 00UTC (or earlier) of the day previous to the day(s) of interest.
Unexpected snow	11th February 2017
This case was highlighted by the project board because it was a situation in which the public perception of Met Office forecasts was poor. Light snow fell in the southwest and other areas without any indication that snow would fall.
This case covers:
•	Nowcasting (the UKV had little precipitation)
•	Snow
•	Rain
•	Frontal
Storm Doris	22- 23rd February 2017
23rd Strong winds associated with a deep cyclone (Doris) crossing the UK. On the previous day (22nd) there were strong winds in Yorkshire associated with lee waves
This case covers:
•	Damaging winds
•	Rain
•	Frontal
•	Sting jet (possibly)
•	Showers
•	Snow
•	Lee waves
Low cloud 	5-6th April 2017
The UKV (and perhaps MOGREPS-UK) over-forecast low cloud
This case covers:
•	Low cloud
•	Sunshine
•	Model error

Wintry showers and wind gusts 	25-26th April 2017
Unusually cold air-mass brought wintry showers and gusty winds associated with showers
•	Showers
•	Rain/snow/graupel mix
•	Convective gusts
Deep convection with lightning 	27-28th May 2017
An organised band of thunderstorms moved NE through SW England in the early hours of the 27th and tended to die out over SE England, but with a squall line forming over East Anglia. Further storms developed over NW England in the afternoon. On the 28th heavy rain moved north from France as a weakening Mesoscale Convective System.
•	Showers
•	Heavy rain
•	Lightning
•	Organised convection
31st May - 1st June 2017
Sea fog along south coast and some hill fog probabilities
•	Sea fog
•	Hill fog

There is still a need for a case study to deal with clear skies with local fog and cold overnight temperatures.
[IMPROVER_case_studies_310517.pdf](https://github.com/metoppv/improver/files/1041345/IMPROVER_case_studies_310517.pdf)

**Comment by benfitzpatrick** [comment]
Assigned to Sean but meaning Nigel

**Comment by benfitzpatrick** [comment]
I am provisionally going to put up February 2017 and March 2017 data

**Comment by benfitzpatrick** [comment]
Decided to include February, March, April, and May 2017 to cover the above cases. Will investigate late December 2016 fog as well.

**Comment by fionaRust** [comment]
Closing as @NigelRoberts is happy that this has been done.
