### ISSUE TITLE
improver nbhood: migrate percentiles-from-nbhood to improver percentile

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#459]
As an IMPROVER developer I want percentile generation from neighbourhoods located under the `generate-percentiles` CLI so that `nbhood*` CLIs are simpler and more logical.

Acceptance criteria:
 * Move call to the `GeneratePercentilesFromANeighbourhood` plugin from nbhood CLI to generate-percentiles CLI
 * Add a new e.g. `--radius` option to `generate-percentiles` CLI to invoke this
 * Assume fixed radius with lead time
 * Restructure acceptance tests (answers should not change)
 * Make corresponding suite change

**Comment by fionaRust** [comment]
Closing as not a priority and would need to be included in a wider piece of work to rationalise CLIs.
