### ISSUE TITLE
Arrange kick-Off Workshop for Gusts

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#46]
As a X I want Y so that Z

Related issues: #I, #J

Optional extra information text goes here

Acceptance criteria:
 * A
 * B
 * C

**Comment by fionaRust** [comment]
What's the status of this? I'm making it into a story so it's easier to flag up, but needs way more detail in the description.

**Comment by fionaRust** [comment]
Closed as not needed as a ticket.
