### ISSUE TITLE
Agree approach to Nowcasting with Stephen

### ISSUE THREAD

**Issue by seanpcoultas** [metoppv/improver#47]
To be assigned to Nigel Roberts
As a X I want Y so that Z

Related issues: #I, #J

Optional extra information text goes here

Acceptance criteria:
 * A
 * B
 * C

**Comment by fionaRust** [comment]
What's the status of this? I'm making it into a story so it's easier to flag up, but needs way more detail in the description.

**Comment by fionaRust** [comment]
Stephen has agreed this has been documented and can be closed.
