### ISSUE TITLE
Tidy up neighbourhood processing CLI arguments

### ISSUE THREAD

**Issue by cgsandford** [metoppv/improver#480]
As an IMPROVER developer I want a clear neighbourhood processing interface so that it is easy to work with.

The current neighbourhood CLIs have a mixture of options, some of which are not used, and for which the defaults are different between CLIs.  This ticket is to update the available options and defaults in the four existing "nbhood" CLIs.  The requirements are:

- Remove "re_mask" and recursive-filter-only behaviour as options for each CLI
- Merge "radius" and "radii_by_lead_time" arguments, avoiding space separation for lead times
- Rename "topographic band" related options as "zone" or "band", removing the explicit reference to topography
- Set default for "coord_for_masking" option as "topographic_zone"
- Invert "collapse_dimension" so that it is always true

Related issues: #352, #459 (prerequisite), #460

Acceptance criteria:
 * Update the nbhood CLIs using the options above
 * Update bats tests to reflect the new options and defaults

**Comment by fionaRust** [comment]
Superseded by https://github.com/metoppv/mo-blue-team/issues/157
