### ISSUE TITLE
Start porting to Python 3

### ISSUE THREAD

**Issue by arh89** [metoppv/improver#487]
As an IMPROVER developer, I want to know how difficult it will be to port IMPROVER to Python 3, so that I can plan migration timescales to ensure that the necessary work is completed before Python 2 is no longer supported.

Related issues: Epic #265

Prerequisites: The code should already have been ported to Iris 2: See Epic #215

Acceptance criteria:
 * Use the `2to3` tool on the existing IMPROVER codebase.
 * Make simple updates to upgrade the codebase to be Python 3 compatible. Backwards compatibility to Python 2 is not required.
 * If complex compatibility issues exist, then these can be captured in follow-on work.
 * Estimate the amount of time required to port the remainder of the code to Python 3 – update this ticket with a plan if appropriate (non-trivial).

**Comment by gavinevans** [comment]
Ported to Python 3 in #558
