### ISSUE TITLE
Utility to ensure cube.collapsed output type matches the input type

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#494]
As an IMPROVER developer, I want the output type of cube.collapsed to match the input type so that an unexpected change in type from a numpy array to a numpy MaskedArray doesnt break the code.

Related issues: #419 

#419 fixed the unit tests including for neighbourhood processing to deal with a numpy array being input to cube.collapsed returning a numpy MaskedArray. A utility for wrapping cube.collapsed should be created, so that this change in type can be avoided, in case it could cause unexpected side effects.

Acceptance criteria:

 * Create a simple utility for wrapping cube.collapsed; ensuring that the input type matches the output type.
 * Ensure the neighbourhood processing modified in #419 uses the new utility.
 * Add unit tests.

**Comment by fionaRust** [comment]
Fixed, no longer an issue and no longer get float64 out of collapse
