### ISSUE TITLE
IMPROVER CLIs: Further centralisation

### ISSUE THREAD

**Issue by arh89** [metoppv/improver#496]
As an IMPROVER developer I want to further centralise common CLI functionality, so that I reduce the development effort required to create new CLIs, add new functionality to all CLIs, and expose our plugins to the suite.

Related issues: #433 

Acceptance criteria:
 * Use the new centralised ArgParser (building on IMPRO-503).
 * Follow the general spirit and requirements of the Office365 document on JIRA
 *  Centralise the common CLI functionality (e.g: creating ArgParser instances, loading and saving netCDF files, creating and using instances of plugins etc) to a common place. This could be e.g: from a common CLI class, where the plugin is passed in as an argument when creating an instance.
 * Port at least 1 of the “straightforward” CLIs (where they only follow the load -> process -> save pattern) as a demonstration for how this may be used.
 * More complex CLIs are out of scope, but when creating the solution, consider how they may be incorporated in later work. (Possibly by creating more simple CLIs, or removing unnecessary functionality from the complex ones).
 * Discuss possible approaches with Aaron.
 * Do what you can, spend no more than 5 days. 

A proposed solution might be to:
Create a new `CLI` class: When creating CLIs, the plugin class and some argument mapping ({‘cli_argument’: ‘plugin_method.argument’ }) can be passed into the constructor (optionally with a `loader` and a `saver`, which default to the IMPROVER `load_cube` and `save_netcdf` functions). The constructor sets up the `ArgParser` instance and the state required to map arguments passed in from the CLI to the `__init__` and `process` methods of the plugin.
This class could also have an `execute`/`process` instance method, which ultimately calls `parse_args` on the `ArgParser` instance to get the options passed in from the command line, then calls the `loader` (with appropriate filepath), creates the instance of the plugin (with the arguments passed in from the command line) – calls `process` on the plugin instance (passing in the cube returned from the `loader`), finally passing the resulting cube into the `saver`, which writes the output file to the output filepath.)

**Comment by TomekTrzeciak** [comment]
Superseded by #955 and #1101.
