### ISSUE TITLE
Set up and run November trial with multiple neighbourhood sizes

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#501]
As a Scientist I want to find the optimum neighbourhood size for temperature data so that I can configure IMPROVER to be more skilful.

Prerequisites:
 * Method for trialling multiple neighbourhood sizes

Related issues:
 * Epic IMPRO-554

Follow-on work:
 * Examine verification results (#508)

To make the results easier to interpret, the suite should run neighbourhooding with radii that do not vary with forecast lead time.
Include non-topographic neighbourhood(s) as a control.

Acceptance criteria:
 * Suite runs temperature chains, which include verification, with multiple neighbourhood sizes.
 * Plot the verification results for use in the follow-on ticket.

**Comment by bayliffe** [comment]
Not a github ticket.
