### ISSUE TITLE
Determine optimal neighbourhood size for temperature

### ISSUE THREAD

**Issue by MoseleyS** [metoppv/improver#508]
As a Scientist I want to find the optimum neighbourhood size for temperature data so that I can configure IMPROVER to be more skilful.

Prerequisite:
 * #501 

#501 will have produced verification plots showing the skill and impact of a range of neighbourhood sizes on temperature forecasts. Discussion with Jonathan Flowerdew is recommended.

Acceptance criteria:
 * A short report detailing the optimum neighbourhood sizes for temperature forecasts including any variation required with lead times.
 * Create follow-on ticket to implement this configuration in the IMPROVER suite.
 * Note down any improvements to this process that you think would be useful for similar future science investigations.

**Comment by bayliffe** [comment]
Done.
