### ISSUE TITLE
Factor out concatenating cubes functionality from ensemble calibration utilities

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#51]
As a developer, I want to be able to use some the utilities, originally written as part of the ensemble calibration work, so that I can easily deal with cube concatenation issues, such as, enabling concatenation with differing scalar coordinates.

Related issues: #36 , #18 

Acceptance criteria:
 * Factor out the concatenating cubes functionality from the ensemble calibration utilities into a top-level set of utilities for usage by other features, which are under development.
 * Ensure that existing usages of the utilities within ensemble calibration are supported.
 * Ensure unit tests still work.

**Comment by bayliffe** [comment]
-[x] Slide added?

**Comment by bayliffe** [comment]
Swiftly done. Superb.
