### ISSUE TITLE
Implement grid-to-grid interpolation.

### ISSUE THREAD

**Issue by MarkWorsfold** [metoppv/improver#510]
As the IMPROVER product owner I would like IMPROVER to have the capability to interpolate from one grid to another using the iris linear interpolation method. This will be used to regrid the standard global grid(s) on to the standard UK grid(s), and to regrid radar data onto the UK grid(s) (whilst it is unavailable from service hub on the correct projection). 

This work is to create a wrapper, most likely as a CLI, to the IRIS cube.regrid method, for use in IMPROVER. 

Related issues: An investigation to look at refining or changing interpolation methods exists in IMPRO-617. This investigation will take place at a later date.

Acceptance criteria:
* Create an IMPROVER wrapper to the iris regrid method, exposing relevant options as configurable.
* Add unit tests/acceptance tests as appropriate.
* Plot some output of the resulting regridding to demonstrate its utility.

**Comment by bayliffe** [comment]
Done.
