### ISSUE TITLE
Implement improved snow falling level functionality in a plugin

### ISSUE THREAD

**Issue by arh89** [metoppv/improver#511]
As the IMPROVER product owner I would like IMPROVER to have the capability to compute rain/snow probabilities robustly: this requires implementing the improved snow-melting (falling) level functionality (which is able to extrapolate below ground for all temperature profiles).

Related issues: #IMPRO-558

Prerequisites: #IMPRO-616

Acceptance criteria:
 * Following on from IMPRO-616, which uses the wet bulb temperature profile directly in calculating the falling snow level below sea level - implement the suggested solution (following confirmation from Nigel that we wish to go ahead). This might involve modifying the existing plugin, or creating a new plugin entirely.
 * Create new unit tests as required.
 * (If creating a new plugin) update the CLI (to use the new plugin).
 * CLI/acceptance tests may need updating - but plot the differences between new and old data and check that it is sensible.
 * Plot the output on a cold day when the falling snow level will be below sea level.
 * If the CLI changes, create a follow-on ticket to capture the work required to update the suite to use this new interface.

**Comment by bayliffe** [comment]
Done.
