### ISSUE TITLE
IMPROVER CLIs: Further centralise common CLI capabilities

### ISSUE THREAD

**Issue by LaurenceBeard** [metoppv/improver#518]
As an IMPROVER developer I want to further centralise common CLI functionality, so that I can make it easier to change and create CLIs, improving maintainability and reducing duplication. 

Related issues: #496 

This ticket builds on work done in #433 in finishing the current implementation and porting an existing CLI to this new implementation.

Refer to #496 for a proposed approach to this implementation.

Acceptance criteria:
* Follow the spirit of #496 proposal, including the requirements section. 
* Finish development work required for a working, tested implementation. Only implement enough for it to work with simple, single input, single plugin, single output CLIs. Adding new compulsory arguments or options (for example profiling #442 is out of scope. 
* Add unit tests and docstrings where required.
* Port at a single CLI (loading, processing, saving) using the new centralised ArgParser (building on #433).
 * Do what you can - spend no more than 5 days

**Comment by TomekTrzeciak** [comment]
Superseded by #1101.
