### ISSUE TITLE
Neighbourhood processing: use radius in metres

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#53]
As an IMPROVER developer I want the command line interface for neighbourhood processing to use SI units so that units are consistent and the names are shorter.

Related issues: #52

Acceptance criteria:
 * Change plugin arguments to be in metres, ditch `_in_km` names
 * Change CLI options to be in metres, ditch `_in_km`
 * Update unit and CLI acceptance tests
 * Add checking for neighbourhood radii larger than domain size.

**Comment by meabhnicguidhir** [comment]
Note that the acceptance criterion to "Add checking for neighbourhood radii larger than domain size" is already met by checks in the `get_neighbourhood_width_in_grid_cells` utility.

**Comment by bayliffe** [comment]
- [x] Slide?

**Comment by bayliffe** [comment]
All done.
