### ISSUE TITLE
Cube slice iterator and merger

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#533]
As an IMPROVER developer I want repeated patterns of slicing, merging, and dimensions checking to be centralised so that my code is more reliable and maintainable.

Acceptance criteria:
 * Ensure there is a utility that: slices a cube (over given coordinate(s)), applies an operation on each slice, and then recombines the slices to form a cube with the dimensions of the output cube identical to the original.
 * The utility should build upon existing code where possible.
 * Ensure there are associated unit tests, and that they capture the existing use cases (for an example, see description).
 * Update the existing code to use the generic functionality wherever possible (if this is not possible, note on the ticket)
 * If appropriate, comment on if this functionality could be ported to Iris.

Ideas from User Story splitting meeting:
The first 3 of the acceptance criteria might be done in one PR, with the updating of the existing use cases being a second PR.

Description:
An example use case of slicing a cube, applying an operation, then recombining it (requiring the original dimensions) is: https://github.com/metoppv/improver/blob/05ebd97/bin/improver-wind-downscaling#L120-L136

**Comment by fionaRust** [comment]
Not sure we have a generic use case for this functionality any more or that there is a lot to gain for a generalised utility.
