### ISSUE TITLE
Investigate options for parallelisation capability

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#534]
As an IMPROVER developer I want an easy-to-use parallelisation capability inside IMPROVER code so that my code runs faster and makes good use of available resources.

Related issues: #9 

Acceptance criteria:
 * Parallelise loops over cube slices
 * Demonstrate by implementing it for a utility that loops over cube slices
 * Demonstrate utility speedup
 * Exception handling should remain the same (i.e. printing to stderr and then making the whole Python session fail)

Description:
It may be useful to approach this by mocking up a simple implementation of cube slicing with Dask first and consult with @benfitzpatrick.

**Comment by LaurenceBeard** [comment]
#714 provides a simple interface to parallelism, demonstrated with wind_downscaling.

For wind downscaling this achieves a 50% speedup, but uses 300% memory.
It would be good to have the ability monitor the performance changes vs. resource usage across the suite before implementing something like this for existing plugins.

The threading is currently implemented at several levels, it is used a lot more heavily in the newer Iris version as it (as it uses Dask a lot more internally).
We want a way to control this threading, so we don't reduce performance across processes or increase memory use dramatically. This is covered by another ticket.
