### ISSUE TITLE
Ensure ECC GeneratePercentilesFromProbabilities plugin follows CF conventions

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#54]
**Updated 20/09/2017**

As an IMPROVER developer I want the GeneratePercentilesFromProbabilities plugin to follow the same temporary CF conventions as other parts of the code so it can be used in conjunction with other plugins.

The code should already work with the temporary conventions for percentile data. This ticket should update GeneratePercentilesFromProbabilities to work with the conventions for probabilistic data.

Related issues: #49 , #30 

Acceptance criteria:
 * Implement agreed temporary CF conventions for probabilistic data to plugin.
 * Test with probability cubes from the suite (with a threshold dimension and the correct temporary metatdata).
 * Update unit tests and any affected ECC CLI tests.

**Comment by bayliffe** [comment]
Completed.
