### ISSUE TITLE
Plugin to calculate diagnostic lapse rates with height

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#547]
As the IMPROVER product owner I want to be able to generate temperature lapse rates from single-level screen temperature fields following the method of Sheridan et al. 2010. This involves using an orography  field and a neighbourhood of points to calculate the rate with which temperature varies with altitude. The resulting lapse rate will enable site specific temperature forecasts to be adjusted to better represent conditions at the sites altitude.

A plugin is needed to calculate and return a cube of lapse rates. This could be made by refactoring and updating the orography_derived_temperature_lapse_rate method from extract_data in spot_data which is similar to the Sheridan method. Note that the Sheridan method imposes sensible limits on what the lapse rate can be, and this is currently missing from the spotdata implementation.

NB. We are not intending to immediately make use of the resulting lapse rate cubes in spotdata as it stands; this will be implemented in a later ticket. As such, code may be copied from within spotdata, but the original should be left in place so that the spotdata code is left unchanged by this work.

Acceptance criteria:
 * Write a plugin to calculate diagnostic lapse rates with altitude based on a neighbourhood of grid points.
 * Units of lapse rate should be K m-1.
 * If reusing code from extract_data.py, leave existing code in place for later removal (so spot data keeps working as before).
 * Add unit tests to cover both stable and unstable atmospheric conditions.

**Comment by MarkWorsfold** [comment]
Pull request created:
https://github.com/metoppv/improver/pull/603
