### ISSUE TITLE
Fix triangle time blending for cldlow

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#644]
As an improver developer I would like to be able to run the suite on all variables to generate products and verification.

Triangle time blending is failing for the cldlow chain with a value error.  This is thrown from this line: [https://github.com/metoppv/improver/blob/master/lib/improver/blending/blend_across_adjacent_points.py#L175] when the new data is copied into central_point_cube, because central_point_cube has an extra scalar dimension.  It can be fixed by demoting scalar dimension coordinates on the central input cube before blending.
Acceptance criteria:
* Scalar coordinates are demoted in TriangularWeightedBlendAcrossAdjacentPoints.process() before blending
 * Unit tests to confirm this works for an input cube with an additional scalar dimension
 * Test suite triangular time blending step works in the cldlow chain and at least one other chain

**Comment by MoseleyS** [comment]
PR #655 addresses this issue.
