### ISSUE TITLE
Create informal Level 1 archive

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#66]
As an IMPROVER developer I want a Level 1 archive with data in a nice format so that I can run case studies

Related issues: #33 

Acceptance criteria:
 * Write some code to combine StaGE level 1 data over ensemble members and slice over times
 * Create a feature branch of the suite to run this and add push-to-archive capability
 * Create archive for February to May 2017

**Comment by TomekTrzeciak** [comment]
This ticket meets the acceptance criteria and is ready to close.
TODO: add some info to the developer guide about where is the archive and how to use it.
