### ISSUE TITLE
Add up array from bottom left to top right - square neighbourhood part 1

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#73]
As the product owner I want IMPROVER to have the capability to do neighbourhood processing quickly using square neighbourhoods and this is the first of the two-part step to do that.

Related issues: #74 

This functionality is to be applied to regular 2-d arrays. It will typically be applied to arrays that contain values between 0 and 1 after a thresholding step has been performed, but it could be applied to any 2-d array for other applications. It could potentially be extended to more than 2 dimensions (3-d array).
Fortran code for doing this is attached here [addup_array_fortran.pdf](https://github.com/metoppv/improver/files/1047939/addup_array_fortran.pdf)

The addition follows the example below where the arrays are summed vertically and summed horizontally:
```bash
1  1  0                   2  4  5
0  1  0           =>      1  2  3   
1  0  1                   1  1  2
```

This relates to "Square neighbourhood functionality" in the roadmap

Acceptance criteria:
 * Create an interface to the new neighbourhood processing functionality either as a separate plugin (e.g. SquareNeighbourhoodProcessing), or by using options for a top-level NeighbourhoodProcessing class.
 * Separate out any shared functionality and consider creating utilities classes as appropriate.
 * After refactoring, create a method that will add up 2-d array from one corner to the diagonally opposite 
 * The output array can be used by the function to find the neighbourhood fraction using the 4-point algorithm (step two) #74 
 * Unit tests
 * Code review

**Comment by meabhnicguidhir** [comment]
In progress. Will be documented on June Sprint User Story #104

**Comment by MoseleyS** [comment]
Completed by Pull Request #114
