### ISSUE TITLE
4-point square neighbourhood algorithm - square neighbourhood part 2

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#74]
As the product owner I want IMPROVER to have the capability to do neighbourhood processing quickly using square neighbourhoods and this is the second of the two-part step to do that.

Related issues: #73 

This functionality is to be applied to regular 2-d arrays that have been through stage 1 #73 

This relates to the "Square neighbourhood functionality" in the roadmap
An example of how to do this in Fortran is attached here 
[neighbourhood_4-point.pdf](https://github.com/metoppv/improver/files/1047994/neighbourhood_4-point.pdf)

The capability to do neighbourhood processing using squares is very important for a two reasons:
1. It is easily exactly specified what the contribution of each of the neighbouring grid squares is to the central grid square for which the neighbourhood probabilities are generated. There is no weighted or Gaussian function with tails to disentangle.
2. It will allow the incorporation of a masking approach so that only selected grid squares within a neighbourhood are used - for example, only grid squares below 50m.

Acceptance criteria:
 * Create a function that will find the average grid-square value in a square neighbourhood using the 4-point algorithm
 * Capability to read files created by step 1 #73 (values added up from one corner to diagonally opposite)
 * Have a combined capability using #73 followed by #74 to create square neighbourhood fractions from the 2-d array provided into #73 with a CLI for both that allows them to be called independently and a CLI for both combined.
 * Unit tests
 * Code review

**Comment by fionaRust** [comment]
Closed by pr #156
