### ISSUE TITLE
Unit test helper functions - times in integer seconds

### ISSUE THREAD

**Issue by bayliffe** [metoppv/improver#742]
None

Acceptance criteria:
None

Description:
There are helper functions in some unit tests that create cubes or add coordinates. Where these helper functions are dealing with times we want the coordinates to be in seconds, and of type int64.

This task is to modify local unit test helper functions that deal with times be formatted as integer seconds, to replace imported set up functions with the single cube setup utilities developed in IMPRO-228, and to modify tests that rely upon them where necessary.

Since this work involves changes to a large number of unit tests (at least 150, possibly more), this will be done over a number of sprints as a series of small PRs.  Work in each sprint will be pursued so as not to disrupt or conflict with other tickets (ie avoiding unit tests that others are likely to be working on).  Progress and further work will be appended to comments below.

When this work is complete the {{convert_time_to_seconds}} function can be deleted from {{tests/utilities/test_temporal.py}} as can the calls to this function in the same file. (/) (in #750)

 

*Test checklist*

(/) changes complete

(*g) no changes required

(!) work in progress

(x) won't fix

Directories under lib/improver/tests:
 * argparser (*g)
 * blending (/)
 * convection (*g)
 * cube_combiner (/)
 * *ensemble_calibration*
 * *ensemble_copula_coupling*
 * feels_like_temperature [(/)|https://github.com/metoppv/improver/pull/821]
 * generate_ancillaries [(/)|https://github.com/metoppv/improver/pull/821]
 * lapse_rate (/)
 * *nbhood*
 * nowcasting (/)
 * orographic_enhancement (/)
 * percentile (*g)
 * psychrometric_calculations (/)
 * spotdata (/)
 * threshold (/)
 * utilities (except cube_manipulation) (/)
 * utilities/cube_manipulation (/)
 * uv_index (*g)
 * *wind_calculations*
 * *wxcode*

**Comment by fionaRust** [comment]
Done
