### ISSUE TITLE
Functionality to adjust neighbourhood size according to ensemble size

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#75]
As the product owner I want IMPROVER to have the capability to adjust the neighbourhood size according to the number of ensemble members so that the same amount of smoothing is applied.

Related issues: #36 
Part of User Story #104 

This functionality is in addition to the function to have  neighbourhood radii that are configurable with lead time #36.
The formula in words is:
New neighbourhood radius (km) = Factor x ( Square root of (Single forecast radius (#36) squared / Number of ensemble members) )
If "Factor" = 1 this essentially conserves ensemble members if every neighbourhood grid square is considered to be an ensemble member
A document describing the formula is attached here 
[neighbourhood_radius_ens_size_adjust.pdf](https://github.com/metoppv/improver/files/1048384/neighbourhood_radius_ens_size_adjust.pdf)

Note - this is really an extension of issue #36 that wasn't included in the May sprint and therefore relates to the "Configure radius by lead time" in the roadmap

Acceptance criteria:
 * Start after #36 is closed
 * Create a function that will adjust the neighbourhood radii according to ensemble size (number of members)
 * Add to work done in #36 with new command line option.

**Comment by MoseleyS** [comment]
Having partially reviewed PR #129, I have proposed modifying this ticket's scope. There is no provision here for where the ensemble member (or realization) count will come from and @carolinejjones has made the assumption that the cube passed in to this function will have a realization coordinate to represent this. Having spoken to @NigelRoberts, we have agreed that it makes sense mathematically to collapse the cube along the realization coordinate before using the neighbourhood algorithm, so therefore the number of ensemble members that the input cube represents needs to come from somewhere - ideally the cube meta-data. This ticket is therefore blocked until we can agree a standard method for representing this information.

**Comment by carolinejjones** [comment]
As a temporary solution we have assigned an attribute to the cube, source_realizations = list of ensemble numbers, to represent a cube which has been collapsed along the realization coordinate.

**Comment by fionaRust** [comment]
This was closed by pull request #129
