### ISSUE TITLE
Calculate gradients between adjacent grid squares

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#83]
As the product owner I want IMPROVER to have the capability to decide whether precipitation is convective or stratiform based on the precipitation texture. The calculation of gradients between adjacent grid squares is the first part of that functionality. It is also a functionality need for topographic gradients.

Epic link: #97 
Related issues: #76 

Once gradients have been found, the ratio of the number of grid squares with high precipitation-rate gradients to the number of grid squares with any non-zero precipitation-rate gradients in a region (or square neighbourhood) can be used as a tool to deduce whether the precipitation is convective, partly convective or stratiform. This can also be applied to other variables and will also have use in detecting convective gusts. The gradients need only be found in the x and y directions (not diagonally). It can be essentially the same function as for #76 and therefore they could be combined.

Note - this is bringing forward the convection diagnosis in the roadmap because EMOS for temperature is already in place. 

We should not need a convention for the information in the array as it should be part of a cube with accurate metadata.
~~Suggest a convention that the x-direction gradient specified for a grid square relates to the gradient on the eastern edge of that square and the y-direction gradient specified for a grid square relates to the northern edge of that square. However, this convention does not need to be followed if a different one proves to be better.~~

Acceptance criteria:
 * Create a plugin to return a Cube with the correct metadata.
 * Create a function that finds the gradients between adjacent grid squares in x and y directions
 * Outputs array with 2x2d fields containing gradients - one 2-d field for x and one 2-d field for y 
 * Create unit test to handle missing data.

**Comment by meabhnicguidhir** [comment]
This issue has been superseded by the Epic: Ancillary Generation for Improver (#97) and will be included in a User Story under this Epic.

**Comment by fionaRust** [comment]
Reopened issue as a user story related to the  Epic: Ancillary Generation for Improver (#97)

**Comment by gavinevans** [comment]
As a technical note, the current working assumption of this ticket is that it will use `np.diff` to yield the discrete differences between adjacent grid squares, rather than `np.gradient`.

**Comment by fionaRust** [comment]
Pr #147  was merged which superceed  pr #142.

Slides have been created and there are no follow on issues. So this item is being closed. All outstanding questions about cf metadata should be covered by #91
