### ISSUE TITLE
Capability to read radar fields for nowcasting

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#84]
As the product owner I want IMPROVER to have the capability to read radar fields so that they can be used for precipitation nowcasting.

Related issues: #108 

Once radar fields can be read, they can be put on the standard grid and the optical flow algorithm can be used to extrapolate in time.

It is assumed that the interpolation to the standard grid will not be done in this issue. Discussion needed to clarify.

Acceptance criteria:
 * Capability to read radar fields 
 * Write a new plugin
 * @MoseleyS to add more information.

**Comment by MoseleyS** [comment]
Useful information:
 * MetDB can be accessed using the [Met Office MetDB Python module](http://www-avd/sci/metdb/index.html). The required data for this plugin appear to be under subtype RADRRATE.
 * Other gridded data are likely to be required in future issues, such as satellite data and 3D radar composites.
 * Site data will be required from the MetDB in future issues. Probably as a separate plugin?

Acceptance criteria:
 * Output should be a Cube with appropriate meta data.
 * Multiple retrievals for different data times should result in cubes that can be merged into a single cube with a time dimension.

**Comment by fionaRust** [comment]
Task to investigate this has been created in #108

**Comment by fionaRust** [comment]
For now we won't do this so closing this ticket.
