### ISSUE TITLE
Detect sea/land grid squares on standard grid in which there is land/sea

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#85]
As the product owner I want IMPROVER to have the capability to be able to diagnose grid squares that are classed as sea in which there is actually some land or land in which there is some sea. If this is calculated once it can be used later to improve spot forecasts.

Related issues: #43 #76 #77 #78 #79 #80 #81 (all to do with ancillary creation)

This relates to "Sub-grid topography ancillaries" in the roadmap.

A further extension to this will be an ancillary that points to the nearest appropriate land or sea grid square for a land point in a "sea square" or a sea point in a "land square".

Acceptance criteria:
 * Ability to produce an ancillary file (or files) that flags all grid squares that are specified as sea/land on the standard UK grid, but have some land/sea in reality  
 * Develop a flexible script(s) that can be called from the command line, in order to generate the required ancillary file 
 * Develop plugins to generate the required ancillary with unit tests

**Comment by meabhnicguidhir** [comment]
This issue has been superseded by the Epic: Ancillary Generation for Improver (#97) and will be included in a User Story under this Epic.
