### ISSUE TITLE
Provide Command Line Interface for Ensemble Calibration

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#87]
As a post-processing suite trialler, I want to be able to run ensemble calibration in a suite so that I can verify whether it makes any improvement.

Related issues: #56

Check the wind speed suite from the IMPROVER demo to try to use the existing CLI from this suite.
Review functionality added by #72 to see how it may be possible to use known good outputs.

Acceptance criteria:
 * Ensure a Command Line Interface exists for ensemble calibration. This should include both the calibration step and the optional Ensemble Copula Coupling step to convert from calibrated ensemble mean and variance back to ensemble member.
 * Add appropriate acceptance tests (for wind and temperature).

**Comment by gavinevans** [comment]
This CLI should interface with the `EnsembleCalibration` plugin. Temperature should use the Gaussian distribution, whilst wind speed should use the Truncated Gaussian distribution.

The interfaces for the `EnsembleCalibration` plugin are:
```python
    def __init__(self, calibration_method, distribution, desired_units,
                 predictor_of_mean_flag="mean"):
    def process(self, current_forecast, historic_forecast, truth):
```

* The calibration method is `nonhomogeneous gaussian regression` or `ensemble model output statistics`. 
* Distribution is either `gaussian` (temperature) or `truncated_gaussian` (wind_speed). 
* Desired units is the units that you would like the calibration to work in. The current forecast, historical forecasts and truth will be converted into this unit for calibration.
* `predictor_of_mean_flag` is set as a default to be `mean` but can be either `mean` or `members`.
* `current_forecast` is a cube or cubelist containing the input forecast for the current cycle.
* `historic_forecast` is a cube or cubelist containing the input historical forecasts.
* `truth` is a cube or cubelist containing the truth for dates matching the historical forecasts.

For example `historic_forecast` will be a cube containing T+12 forecasts at 03Z for 5 days in a row. `truth` contains T+0 analyses for 03Z for 5 days in a row. `current_forecast` is a cube for T+12 at 03Z for 1 day after the end of the dates in the `historic_forecast`.

**Comment by meabhnicguidhir** [comment]
Test data for acceptance tests taken from archive:
1. Gaussian uses temperature_at_screen_level
2. Truncated Gaussian uses wind_speed_at_10m

Current forecast cycle: 20170605 03Z
Historic forecasts: 20170604, 20170603, 20170602 03Z
Truth data: 0th realization from 20170604, 20170603, 20170602 15Z

**Comment by bayliffe** [comment]
[] Slide added?

**Comment by bayliffe** [comment]
Good work. Thanks.
