### ISSUE TITLE
Documentation for local development build

### ISSUE THREAD

**Issue by kinow** [metoppv/improver#883]
Hi, I tried to build Improver locally for development without much luck. Couldn't find in readthedocs or in the GitHub Wiki a file saying how I should set up my environment... `environment.yml` didn't work (even trying to follow the instructions in the header comment).

Wondering if there is some simple docs for that, please? 

Thanks!
Bruno

**Comment by kinow** [comment]
Also, the `requirements.txt` seems out of sync with the dependencies in `environment.yml`? And `.travis.yml` is installing dependencies via `conda install`, without using either files from what I could tell.

**Comment by LaurenceBeard** [comment]
Hey Bruno. It doesn't look like anyone is keeping those up to date, or indeed using them, the .travis.yml is probably the best to follow at the mo, as that's working.
 It's nice to have an external perspective! 
Cheers, Laurence

**Comment by LaurenceBeard** [comment]
Now we have an environment.yml which is working and used for CI testing (w/ Github actions) we can probably close this.
