### ISSUE TITLE
Issues with `pip install git+`. "Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by MorningGlory747** [metoppv/improver#888]
My experience with downloading github packages is lackluster hence perhaps this is why I am confronted with this error. 

I am running Python v3.7.3 on Anaconda v4.6.14 on a Windows 10 64x. When going directly unto the anaconda prompt, I type the following command:

`pip install git+git://github.com/metoppv/improver.git`

And I receive the following traceback error:

```
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\***\AppData\Local\Continuum\anaconda3\lib\tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\***\\AppData\\Local\\Temp\\pip-req-build-_z6qrbbh\\setup.py'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\***\AppData\Local\Temp\pip-req-build-_z6qrbbh\
```

Has improver ever been tested on a Windows before? If so, then what could be the issue / important step that I am missing?

Thank you!

**Comment by benfitzpatrick** [comment]
Hi, we don't have setup.py / pip support yet, although it would be good to sort out. As it's pure Python and we're basically in a development mode, we just clone the repository and work from there.

Windows support - it might work, maybe with a minor change or two - but we don't develop or test there ourselves, so I couldn't guarantee it.

**Comment by MorningGlory747** [comment]
Good to know. I'll try to see what I can do. Thank you for your time!

**Comment by kinow** [comment]
@benfitzpatrick 

>Hi, we don't have setup.py / pip support yet, although it would be good to sort out.

The `setup.py` for improver looks easy/simple. Except for `iris`. It looks like they release 2.x to Conda only, without releasing it to PYPI. Which, I think, means there is no easy way to get improver built with Setuptools.

**Comment by kinow** [comment]
Here's an example of a possible `setup.py` for improver, based on the `requirements.yml`: https://github.com/metoppv/improver/compare/master...kinow:setuppy

But not usable without the dependencies on PYPI. The requirements.yml can be used to set up an environment in Conda, but for others to install improver it would need a recipe too.

**Comment by fionaRust** [comment]
@MorningGlory747 we now have IMPROVER available through conda. Hopefully this will allow you to create the create the correct environment. Please feel free to raise another issue in the future if you have any further problems.
