### ISSUE TITLE
Code documentation: format docstrings to Google standard and avoid Sphinx warnings

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#89]
As an IMPROVER developer I want docstrings in Google format and parsable by Sphinx without warnings so that I can be confident that I have well-presented code documentation. I want to capture warnings as part of the testing process of new code.

Related issues: #88

The docstring style should be in line with the [Code Style Guide](https://github.com/metoppv/improver/wiki/Code-Style-Guide#plugins).

Acceptance criteria:
* Fix any remaining inconsistencies with the code style guide above so that no warnings are produced by "improver tests doc" on master.
 * Alter `improver tests` such that any warnings fail the test
 * Check that the resulting documentation renders correctly.

**Comment by arh89** [comment]
Suggestion: To enforce Google style docstrings (and disallow Numpy style), `napoleon_numpy_docstring = False` can be added to `doc/source/conf.py` (http://www.sphinx-doc.org/en/stable/ext/napoleon.html)

**Comment by arh89** [comment]
When determining that there are no warnings,, even with perfectly formatted docstrings, the current setup will generate 2 warnings:

`/net/home/h02/ahopk/src/improver/doc/source/modules.rst:: WARNING: document isn't included in any toctree
WARNING: html_static_path entry u'/net/home/h02/ahopk/src/improver/doc/source/_static' does not exist`

These should either be fixed or filtered out when checking for warnings.

**Comment by gavinevans** [comment]
When completing this issue, please ensure that the result is compliant with the [docstring section](https://github.com/metoppv/improver/wiki/Code-Style-Guide#docstrings) and the [plugin section](https://github.com/metoppv/improver/wiki/Code-Style-Guide#plugins) from the Code Style Guide.
