### ISSUE TITLE
Technical: Consolidate the unit test directory structure

### ISSUE THREAD

**Issue by fionaRust** [metoppv/improver#90]
As a developers of IMPROVER we want our unit tests to be in a sensible directory structure so that we can easier to find unit tests and we have a common standard

Related issues: 

Restructure the unit test directory to match Anna's suggestion.
`improver/lib/improver/`
`improver/lib/improver/tests/`
`improver/lib/improver/tests/ensemble_calibration/ensemble_calibration/`
`improver/lib/improver/tests/ensemble_calibration/ensemble_calibration_utilities/`
`improver/lib/improver/tests/constants/`
`improver/lib/improver/tests/nbhood/`
`improver/lib/improver/tests/threshold/`
`improver/lib/improver/tests/weighted_blend/`
`improver/lib/improver/tests/wind_downscaling/`
 
` # e.g. individual test`
`improver/lib/improver/tests/ensemble_calibration/ensemble_calibration/test_concatenate_cubes.py`

Acceptance criteria:
 * Make sure unit tests are still discoverable using unit tests (and nosetests?)
 * Make sure unit tests still run.

**Comment by bayliffe** [comment]
Tests moved and tested. PR created: #112

**Comment by fionaRust** [comment]
Blocked until after ECC ticket merged as it will need the same change to the unit test structure,

**Comment by fionaRust** [comment]
Pull Request #112 was replaced by #124 as other things were merged before it.
@TomekTrzeciak raised further questions about where some of the bats tests should go and unit tests. It was decided this is out of scope of the original ticket, but contains useful information. @benfitzpatrick Could you look at creating a new technical debt ticket to cover these extra moves.

**Comment by bayliffe** [comment]
Slide added.

**Comment by fionaRust** [comment]
Closed, follow up discussion in a developer catch up if appropriate.
