### ISSUE TITLE
Agree approach for encoding probabilistic data in the CF convention

### ISSUE THREAD

**Issue by simonjackson900** [metoppv/improver#91]
As a developer I want to encode probabilistic data (thresholds, percentiles) in a CF-compliant manner, so that all our data is CF-compliant and uses a consistent approach.

Related issues: #54, #69, #102 

Acceptance criteria:
 * Agreed approach with Mark Hedley (AVD team)
 * Agree what forms of probabilistic data we will address first
 * sign off by ???
 * documented in wiki pages, etc

**Comment by simonjackson900** [comment]
See also this comment from Jonathan Flowerdew
https://github.com/metoppv/improver/pull/49#issuecomment-305209846

**Comment by fionaRust** [comment]
Most of the issues with this are captured on confluence in **Temporary conventions for probabilistic data** under Developer resources.

There are a lot of problems already cropping up, and more we haven't come across yet. The main things we need conventions for, both for cubes and NetCDF files, that we have come across so far:
* percentiles
* probabilities and thresholds
* spot data
* Combinations of these things
* Ancillary files
* A way of combining useful metadata when different models are merged, like total number of ensemble members and which models they come from
* Provenance metadata

We should also pay attention to how Iris currently handles some of these things, as if we want to change/ignore default Iris behaviour then that could require some work.
