### ISSUE TITLE
Remove OSGB grid

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#93]
As an IMPROVER developer I want to remove the misleading OSGB grid from the codebase so that my code is simpler and clearer in purpose.

Acceptance criteria:
 * Replace osgb grid in unit tests with a preferred approach for setting up a cube for unit testing, keeping in mind the proposed changes in #50.
 * Remove the osgb file
 * Close #7 

Subtasks
- [ ] implement code changes to deal with removing osgb
- [x] close #7

**Comment by gavinevans** [comment]
The current OSGB grid is incorrect. Unit test changes will be required in Neighbourhood processing to change the numbers when this grid is removed.

**Comment by bayliffe** [comment]
Completed.
