### ISSUE TITLE
CLI for threshold plugin

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#98]
As a suite developer I want a command line interface to the fuzzy threshold plugin functionality so that I can write a nice suite that generates probabilities.

Related Issues: #130 

Acceptance criteria:
 * Write a new `bin/improver-threshold` utility
 * This should take in options for threshold and fuzzy factor, and arguments for input and output files 
 * Should support multiple thresholds at once
 * Add a CLI acceptance test
 * Make sample data (1 netcdf file), slicing temperature data into thresholds every 1C. Create a set of data from deterministic and a set of data from ensemble input data.

**Comment by gavinevans** [comment]
Note that we may well need to apply the threshold plugin to multiple thresholds, so the CLI may need to support this, and potentially merge the resulting cube list.

**Comment by benfitzpatrick** [comment]
Yes, it should accept a list of thresholds - modified the acceptance criteria to make that clear

**Comment by fionaRust** [comment]
Points 1-4 have been addressed in PR #270. 
We will do another PR to account for multiple thresholds within the plugin in a following PR, to avoid accumulating technical debt.

**Comment by benfitzpatrick** [comment]
I am actually OK with the threshold plugin only doing one threshold at a time, for what it's worth. The loop over thresholds has to be somewhere, after all.

**Comment by fionaRust** [comment]
PR closed, ticket closed on JIRA
