### ISSUE TITLE
DEFAULT_UNITS constant modified by unit tests, causes later tests to fail

### ISSUE THREAD

**Issue by tjtg** [metoppv/improver#981]
As an IMPROVER developer, I want unit tests to not affect global state so that they are independent of each other and can safely be run in parallel or in any given order.

Tests in the `Test__find_dict_key` and `Test__get_required_units_and_dtype` classes of `lib/improver/tests/metadata/test_enforce_datatypes_units.py` assign to DEFAULT_UNITS from `lib/improver/metadata/constants/units.py` via `lib/improver/metadata/enforce_datatypes_units.py`. The all-caps name means this variable should be constant rather than being modified in code.

Save, load and CLI acceptance tests use DEFAULT_UNITS as part of their metadata operations, and this fails when it has been altered by `test_enforce_datatypes_units` running beforehand.

This bug is not immediately apparent as unittest default ordering runs tests from lib/improver/tests/metadata/test_enforce_datatypes_units.py after the save and load tests.
Pytest default ordering does encounter the bug.

Acceptance criteria:
* Unit test suite passes with default ordering
* Unit test suite passes when run in random order such as by using unittest [sortTestMethodsUsing](https://docs.python.org/3.8/library/unittest.html#unittest.TestLoader.sortTestMethodsUsing) or pytest [random ordering plugin](https://pypi.org/project/pytest-random-order/)

**Comment by tjtg** [comment]
As mentioned in https://github.com/metoppv/improver/pull/982#issuecomment-544593482, this issue is expected to be fixed as part of #977.

**Comment by cgsandford** [comment]
Fixed as part of #977
